---
title: "MUSA 5080 Portfolio"
format: html
editor: visual
---

# Welcome to My Portfolio

This portfolio documents my learning journey in **Public Policy Analytics (MUSA 5080)** at the University of Pennsylvania.\
It includes **weekly reflections, lab assignments, and a final project**.

## About This Course

This course introduces advanced spatial analysis and data science for urban planning and public policy.\
Through hands-on labs and projects, I will use tools such as **R, dplyr, tidycensus, and Quarto** to analyze policy-relevant data.\
Key focus: reproducibility, version control, and transparent policy analytics.

## Portfolio Structure

-   **Weekly Notes:** Reflections on learning, key takeaways, and challenges\
-   **Labs:** Applied assignments and data-driven policy analysis\
-   **Final Project:** A capstone policy modeling challenge

## About Me

-   **Name:** Zhe Fang\
-   **Program:** Master of Urban Spatial Analytics (MUSA), University of Pennsylvania\
-   **Interests:** Spatial data science, public policy, reproducible analytics for decision-making

## Contact

-   **Email:** [fang6\@upenn.edu](mailto:fang6@upenn.edu)\
-   **GitHub:** [\@Mayaano](https://github.com/Mayaano)
