<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="">
<meta name="dcterms.date" content="2025-12-01">

<title>Eviction Predictor – Zhe Fang - MUSA 5080 Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Zhe Fang - MUSA 5080 Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-weekly-notes" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Weekly Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-weekly-notes">    
        <li>
    <a class="dropdown-item" href="../../weekly-notes/index.html">
 <span class="dropdown-text">All Notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-01-notes.html">
 <span class="dropdown-text">Week 1 - Course Intro</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-02-notes.html">
 <span class="dropdown-text">Week 2 - Algorithms &amp; Census Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-03-notes.html">
 <span class="dropdown-text">Week 3 - Data Visualization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-04-notes.html">
 <span class="dropdown-text">Week 4 - Spatial Data &amp; GIS</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-05-notes.html">
 <span class="dropdown-text">Week 5 - Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-06-notes.html">
 <span class="dropdown-text">Week 6 - Spatial ML &amp; Fixed Effects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-07-notes.html">
 <span class="dropdown-text">Week 7 - Model Diagnostics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-09-notes.html">
 <span class="dropdown-text">Week 9 - Predictive Policing Ethics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-10-notes.html">
 <span class="dropdown-text">Week 10 - Logistic Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-11-notes.html">
 <span class="dropdown-text">Week 11 - Space-Time Prediction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-12-notes.html">
 <span class="dropdown-text">Week 12 - Neighborhood Change</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-assignments" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Assignments</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-assignments">    
        <li>
    <a class="dropdown-item" href="../../assignments/assignment1/assignment1.html">
 <span class="dropdown-text">Assignment 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../assignments/assignment2/Fang_Zhe_Assignment2.html">
 <span class="dropdown-text">Assignment 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../assignments/assignment3/Yang_Chen_Fang_Gao_Xiang_Zhao_Appendix.html">
 <span class="dropdown-text">Midterm</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../assignments/assignment4/Fang_Zhe_Assignment4.html">
 <span class="dropdown-text">Assignment 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../assignments/assignment5/HW5.html">
 <span class="dropdown-text">Assignment 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../assignments/final_project_analysis_process/eviction_data_analysis.html">
 <span class="dropdown-text">Final Project Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../assignments/final_project_presentation/eviction_presentation.html">
 <span class="dropdown-text">Final Project Presentation</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#project-setup-and-environment" id="toc-project-setup-and-environment" class="nav-link active" data-scroll-target="#project-setup-and-environment">Project Setup and Environment</a></li>
  <li><a href="#policy-problem-research-question" id="toc-policy-problem-research-question" class="nav-link" data-scroll-target="#policy-problem-research-question">Policy Problem &amp; Research Question</a>
  <ul class="collapse">
  <li><a href="#problem-statement" id="toc-problem-statement" class="nav-link" data-scroll-target="#problem-statement">Problem Statement</a></li>
  <li><a href="#stakeholders-affected" id="toc-stakeholders-affected" class="nav-link" data-scroll-target="#stakeholders-affected">Stakeholders Affected</a></li>
  <li><a href="#decision-use-case" id="toc-decision-use-case" class="nav-link" data-scroll-target="#decision-use-case">Decision Use Case</a></li>
  </ul></li>
  <li><a href="#data-overview-and-data-imports" id="toc-data-overview-and-data-imports" class="nav-link" data-scroll-target="#data-overview-and-data-imports">Data Overview and Data Imports</a></li>
  <li><a href="#exploratory-data-analysis---tract-fillings-and-predictors" id="toc-exploratory-data-analysis---tract-fillings-and-predictors" class="nav-link" data-scroll-target="#exploratory-data-analysis---tract-fillings-and-predictors">Exploratory Data Analysis - Tract Fillings, and Predictors</a></li>
  <li><a href="#join-tracts-to-filings" id="toc-join-tracts-to-filings" class="nav-link" data-scroll-target="#join-tracts-to-filings">Join Tracts to Filings</a></li>
  <li><a href="#trends" id="toc-trends" class="nav-link" data-scroll-target="#trends">trends</a></li>
  <li><a href="#trends-1" id="toc-trends-1" class="nav-link" data-scroll-target="#trends-1">trends</a></li>
  <li><a href="#choice-of-dependent-variable" id="toc-choice-of-dependent-variable" class="nav-link" data-scroll-target="#choice-of-dependent-variable">Choice of Dependent Variable</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a></li>
  <li><a href="#assess-if-data-cleaning-worked" id="toc-assess-if-data-cleaning-worked" class="nav-link" data-scroll-target="#assess-if-data-cleaning-worked">Assess if Data Cleaning Worked</a></li>
  <li><a href="#creating-the-model" id="toc-creating-the-model" class="nav-link" data-scroll-target="#creating-the-model">Creating the Model</a></li>
  <li><a href="#step-1-creating-the-model-data-set" id="toc-step-1-creating-the-model-data-set" class="nav-link" data-scroll-target="#step-1-creating-the-model-data-set">Step 1: Creating the Model Data Set</a></li>
  <li><a href="#step-2-fit-regression-model" id="toc-step-2-fit-regression-model" class="nav-link" data-scroll-target="#step-2-fit-regression-model">Step 2: Fit Regression Model</a></li>
  <li><a href="#important-finding" id="toc-important-finding" class="nav-link" data-scroll-target="#important-finding">Important Finding</a>
  <ul class="collapse">
  <li><a href="#why-predict-percentage-diff-why-ols" id="toc-why-predict-percentage-diff-why-ols" class="nav-link" data-scroll-target="#why-predict-percentage-diff-why-ols">Why Predict Percentage Diff? Why OLS?</a>
  <ul class="collapse">
  <li><a href="#choice-of-dependent-variable-1" id="toc-choice-of-dependent-variable-1" class="nav-link" data-scroll-target="#choice-of-dependent-variable-1">Choice of Dependent Variable</a></li>
  <li><a href="#why-ols-is-appropriate" id="toc-why-ols-is-appropriate" class="nav-link" data-scroll-target="#why-ols-is-appropriate">Why OLS is Appropriate</a></li>
  </ul></li>
  <li><a href="#feature-engineering-strategy" id="toc-feature-engineering-strategy" class="nav-link" data-scroll-target="#feature-engineering-strategy">Feature Engineering Strategy</a>
  <ul class="collapse">
  <li><a href="#features-implemented" id="toc-features-implemented" class="nav-link" data-scroll-target="#features-implemented">Features Implemented</a></li>
  <li><a href="#features-tested-but-excluded" id="toc-features-tested-but-excluded" class="nav-link" data-scroll-target="#features-tested-but-excluded">Features Tested but Excluded</a></li>
  <li><a href="#justification" id="toc-justification" class="nav-link" data-scroll-target="#justification">Justification</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#calculating-errors---root-mean-squared-error-and-mean-average-error---this-evaluates-in-sample-error" id="toc-calculating-errors---root-mean-squared-error-and-mean-average-error---this-evaluates-in-sample-error" class="nav-link" data-scroll-target="#calculating-errors---root-mean-squared-error-and-mean-average-error---this-evaluates-in-sample-error">Calculating Errors - Root Mean Squared Error and Mean Average Error - This evaluates in sample error</a></li>
  <li><a href="#model-validation-and-error-analysis" id="toc-model-validation-and-error-analysis" class="nav-link" data-scroll-target="#model-validation-and-error-analysis">Model Validation and Error Analysis</a></li>
  <li><a href="#test-train-split-validation---this-is-our-control-for-out-of-sample-validation" id="toc-test-train-split-validation---this-is-our-control-for-out-of-sample-validation" class="nav-link" data-scroll-target="#test-train-split-validation---this-is-our-control-for-out-of-sample-validation">Test Train Split Validation - this is our control for out of sample validation</a></li>
  <li><a href="#step-1---create-train-and-test-splits" id="toc-step-1---create-train-and-test-splits" class="nav-link" data-scroll-target="#step-1---create-train-and-test-splits">Step 1 - Create Train and Test Splits</a></li>
  <li><a href="#step-2---fit-model-on-training-data" id="toc-step-2---fit-model-on-training-data" class="nav-link" data-scroll-target="#step-2---fit-model-on-training-data">Step 2 - Fit Model on Training Data</a></li>
  <li><a href="#step-3---predict-on-test-data" id="toc-step-3---predict-on-test-data" class="nav-link" data-scroll-target="#step-3---predict-on-test-data">Step 3 - Predict on Test Data</a></li>
  <li><a href="#comparison-of-in-sample-and-out-of-sample-errors" id="toc-comparison-of-in-sample-and-out-of-sample-errors" class="nav-link" data-scroll-target="#comparison-of-in-sample-and-out-of-sample-errors">Comparison of in-sample and out-of-sample Errors</a>
  <ul class="collapse">
  <li><a href="#morans-i-test-results" id="toc-morans-i-test-results" class="nav-link" data-scroll-target="#morans-i-test-results">Moran’s I Test Results</a></li>
  </ul></li>
  <li><a href="#bias-equity-considerations" id="toc-bias-equity-considerations" class="nav-link" data-scroll-target="#bias-equity-considerations">Bias &amp; Equity Considerations</a>
  <ul class="collapse">
  <li><a href="#geographic-disparities-in-eviction-risk" id="toc-geographic-disparities-in-eviction-risk" class="nav-link" data-scroll-target="#geographic-disparities-in-eviction-risk">Geographic Disparities in Eviction Risk</a></li>
  </ul></li>
  <li><a href="#implementation-recommendations" id="toc-implementation-recommendations" class="nav-link" data-scroll-target="#implementation-recommendations">Implementation Recommendations</a>
  <ul class="collapse">
  <li><a href="#operationalizing-the-eviction-prediction-system" id="toc-operationalizing-the-eviction-prediction-system" class="nav-link" data-scroll-target="#operationalizing-the-eviction-prediction-system">Operationalizing the Eviction Prediction System</a></li>
  <li><a href="#monthly-forecast-dashboard" id="toc-monthly-forecast-dashboard" class="nav-link" data-scroll-target="#monthly-forecast-dashboard">Monthly Forecast Dashboard</a></li>
  <li><a href="#targeted-eviction-prevention-strategy" id="toc-targeted-eviction-prevention-strategy" class="nav-link" data-scroll-target="#targeted-eviction-prevention-strategy">Targeted Eviction Prevention Strategy</a></li>
  <li><a href="#resource-allocation-timeline" id="toc-resource-allocation-timeline" class="nav-link" data-scroll-target="#resource-allocation-timeline">Resource Allocation Timeline</a></li>
  <li><a href="#safeguards-against-misuse" id="toc-safeguards-against-misuse" class="nav-link" data-scroll-target="#safeguards-against-misuse">Safeguards Against Misuse</a></li>
  <li><a href="#potential-harms-from-model-misspecification" id="toc-potential-harms-from-model-misspecification" class="nav-link" data-scroll-target="#potential-harms-from-model-misspecification">Potential Harms from Model Misspecification</a></li>
  <li><a href="#safeguards-recommendations" id="toc-safeguards-recommendations" class="nav-link" data-scroll-target="#safeguards-recommendations">Safeguards &amp; Recommendations</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Eviction Predictor</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 1, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="project-setup-and-environment" class="level1">
<h1>Project Setup and Environment</h1>
<p>This code chunk loads all required R packages and sets a global chunk option for reproducibility. Tidyverse and dplyr are used for data cleaning, reshaping, and merging multiple datasets, which is key given the integration of eviction records, economic indicators, and demographic data. Spatial components are handled using sf and tigris to manipulate census geographies and enable tract-level analysis, while tidycensus facilitates the integration of standardized Census attributes where applicable. Visualization and diagnostic tasks rely on ggplot2, patchwork, and scales, allowing for consistent exploratory data analysis and error assessment. Finally, broom supports tidy model output for interpretation, and readxl is used to import Excel-formatted documents that could not be reliably converted to CSV. Together.</p>
</section>
<section id="policy-problem-research-question" class="level1">
<h1>Policy Problem &amp; Research Question</h1>
<section id="problem-statement" class="level2">
<h2 class="anchored" data-anchor-id="problem-statement">Problem Statement</h2>
<p>Philadelphia faces persistent, geographically concentrated eviction pressure that disproportionately affects low-income communities, particularly historically Black neighborhoods in North and West Philadelphia. Evictions destabilize families, increase homelessness risk, and strain municipal services including emergency shelter systems, legal aid, and social support networks. Despite the severity of this problem, city officials currently lack a reliable, predictive mechanism to anticipate spikes in eviction activity and pre-position prevention resources.</p>
</section>
<section id="stakeholders-affected" class="level2">
<h2 class="anchored" data-anchor-id="stakeholders-affected">Stakeholders Affected</h2>
<ul>
<li><strong>Renters at risk</strong>: Low-income households vulnerable to displacement</li>
<li><strong>Community-based organizations</strong>: Nonprofits providing legal aid, mediation, and rental assistance</li>
<li><strong>Philadelphia Housing Authority</strong>: Public housing and housing support programs</li>
<li><strong>Office of Homeless Services</strong>: Emergency shelter and prevention coordination</li>
<li><strong>City Council &amp; Policy Staff</strong>: Resource allocation and program design</li>
</ul>
</section>
<section id="decision-use-case" class="level2">
<h2 class="anchored" data-anchor-id="decision-use-case">Decision Use Case</h2>
<p>A month-ahead forecast of eviction pressure enables city officials to:</p>
<ol type="1">
<li>Anticipate demand surges for rental assistance, legal aid, and mediation services</li>
<li>Allocate prevention resources equitably across neighborhoods before filings occur</li>
<li>Intervene before households reach eviction, rather than responding after displacement</li>
</ol>
</section>
</section>
<section id="data-overview-and-data-imports" class="level1">
<h1>Data Overview and Data Imports</h1>
<p>This code chunk imports all primary datasets used in the analysis, bringing together eviction records, demographic context, economic indicators, and measures of household financial vulnerability. The core eviction data are sourced from evictionlab.org . Multiple eviction tables are loaded to support different analytical needs, including raw filing counts (tract_filings), normalized filing rates (tract_filing_rate), and citywide temporal patterns relative to historical baselines (eviction_trends). These complementary formats allow the project to examine evictions at both the spatial (tract-level) and temporal (month-to-month) scales, which is critical for understanding changes in eviction activity.</p>
<p>To contextualize eviction behavior within broader economic and social conditions, the project incorporates several external data sources. Monthly unemployment rates and Consumer Price Index (CPI) data capture macroeconomic conditions that directly affect households’ ability to meet rent obligations. This data is sourced from the Bureau of Labor Statistics. The Urban Institute financial health dataset provides indicators of underlying financial vulnerability, such as debt burdens, housing cost stress, and labor market engagement. Additional datasets from the eviction lab describing neighborhood demographics, eviction hotspots, and deviations from historical filing baselines support exploratory analysis and feature engineering during later modeling stages. These datasets enable a transparent, multi-source approach to integrate diverse data sources in support of a policy-relevant predictive model.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Changes in Claim Amount</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>claim_change <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"eviction_data/changes_claims.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Demographics</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>demographics <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"eviction_data/demographics.csv"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Hotspots</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>hotspots <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"eviction_data/eviction_hotspots.csv"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Evictions Relative to Baseline</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>evictions_baseline <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"eviction_data/filings_relative_baseline.csv"</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Tract Level Filings</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>tract_filings <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"eviction_data/tract_level_filings.csv"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Tract Level Filing Rate</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>tract_filing_rate <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"eviction_data/tract_level_filing_rate.csv"</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Eviction Trends</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>eviction_trends <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"eviction_data/trends_eviction.csv"</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Monthly Unemployment Rates</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>unemployment_monthly <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"eviction_data/unemployment_rate_montly.xlsx"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...2`
• `` -&gt; `...3`
• `` -&gt; `...4`
• `` -&gt; `...5`
• `` -&gt; `...6`
• `` -&gt; `...7`
• `` -&gt; `...8`
• `` -&gt; `...9`
• `` -&gt; `...10`
• `` -&gt; `...11`
• `` -&gt; `...12`
• `` -&gt; `...13`</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Consumer Price Index</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>consumer_price_index <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"eviction_data/consumer_price_index_monthly.xlsx"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...2`
• `` -&gt; `...3`
• `` -&gt; `...4`
• `` -&gt; `...5`
• `` -&gt; `...6`
• `` -&gt; `...7`
• `` -&gt; `...8`
• `` -&gt; `...9`
• `` -&gt; `...10`
• `` -&gt; `...11`
• `` -&gt; `...12`
• `` -&gt; `...13`
• `` -&gt; `...14`
• `` -&gt; `...15`
• `` -&gt; `...16`</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Financial Health Data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>financial_health <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"eviction_data/financial-health-of-residents-data.xlsx"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...2`
• `` -&gt; `...3`
• `` -&gt; `...4`
• `` -&gt; `...5`
• `` -&gt; `...6`
• `` -&gt; `...7`
• `` -&gt; `...8`
• `` -&gt; `...9`
• `` -&gt; `...10`
• `` -&gt; `...11`
• `` -&gt; `...12`
• `` -&gt; `...13`
• `` -&gt; `...14`
• `` -&gt; `...15`
• `` -&gt; `...16`
• `` -&gt; `...17`
• `` -&gt; `...18`</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis---tract-fillings-and-predictors" class="level1">
<h1>Exploratory Data Analysis - Tract Fillings, and Predictors</h1>
<p>To begin we examine tract filing data.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Investigate the data set</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tract_filings, <span class="dv">50</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           id month_date month_filings  month_rate month_rate_scale_max
1  4.2101e+10 01/11/2024            11 0.012835473            0.1248843
2  4.2101e+10 01/11/2024             8 0.006950478            0.1248843
3  4.2101e+10 01/11/2024             5 0.008503401            0.1248843
4  4.2101e+10 01/11/2024            51 0.030520646            0.1248843
5  4.2101e+10 01/11/2024             9 0.007594937            0.1248843
6  4.2101e+10 01/11/2024             3 0.013761468            0.1248843
7  4.2101e+10 01/11/2024             6 0.005067568            0.1248843
8  4.2101e+10 01/11/2024            37 0.038988409            0.1248843
9  4.2101e+10 01/11/2024            24 0.028846154            0.1248843
10 4.2101e+10 01/11/2024            11 0.011022044            0.1248843
11 4.2101e+10 01/11/2024             7 0.005723630            0.1248843
12 4.2101e+10 01/11/2024             9 0.014876033            0.1248843
13 4.2101e+10 01/11/2024            11 0.009548611            0.1248843
14 4.2101e+10 01/11/2024             2 0.001339585            0.1248843
15 4.2101e+10 01/11/2024            16 0.014311270            0.1248843
16 4.2101e+10 01/11/2024            18 0.012775018            0.1248843
17 4.2101e+10 01/11/2024             6 0.005016722            0.1248843
18 4.2101e+10 01/11/2024             1 0.001876173            0.1248843
19 4.2101e+10 01/11/2024            12 0.018237082            0.1248843
20 4.2101e+10 01/11/2024            10 0.006925208            0.1248843
21 4.2101e+10 01/11/2024             5 0.006345178            0.1248843
22 4.2101e+10 01/11/2024             2 0.001863933            0.1248843
23 4.2101e+10 01/11/2024             3 0.003787879            0.1248843
24 4.2101e+10 01/11/2024            11 0.008849558            0.1248843
25 4.2101e+10 01/11/2024             7 0.025547445            0.1248843
26 4.2101e+10 01/11/2024             5 0.005917160            0.1248843
27 4.2101e+10 01/11/2024             3 0.003070624            0.1248843
28 4.2101e+10 01/11/2024             8 0.011004127            0.1248843
29 4.2101e+10 01/11/2024             3 0.004587156            0.1248843
30 4.2101e+10 01/11/2024             1 0.001956947            0.1248843
31 4.2101e+10 01/11/2024            14 0.016990291            0.1248843
32 4.2101e+10 01/11/2024            18 0.025862069            0.1248843
33 4.2101e+10 01/11/2024            14 0.032183908            0.1248843
34 4.2101e+10 01/11/2024             2 0.006410256            0.1248843
35 4.2101e+10 01/11/2024            22 0.036974790            0.1248843
36 4.2101e+10 01/11/2024             7 0.012433393            0.1248843
37 4.2101e+10 01/11/2024            21 0.016733068            0.1248843
38 4.2101e+10 01/11/2024            18 0.022304833            0.1248843
39 4.2101e+10 01/11/2024             6 0.007662835            0.1248843
40 4.2101e+10 01/11/2024             4 0.007207207            0.1248843
41 4.2101e+10 01/11/2024             1 0.001288660            0.1248843
42 4.2101e+10 01/11/2024             2 0.001970443            0.1248843
43 4.2101e+10 01/11/2024             3 0.003880983            0.1248843
44 4.2101e+10 01/11/2024             3 0.005145798            0.1248843
45 4.2101e+10 01/11/2024             5 0.008833922            0.1248843
46 4.2101e+10 01/11/2024            25 0.030637255            0.1248843
47 4.2101e+10 01/11/2024            43 0.064275037            0.1248843
48 4.2101e+10 01/11/2024            69 0.046030687            0.1248843
49 4.2101e+10 01/11/2024            56 0.053639847            0.1248843
50 4.2101e+10 01/11/2024            25 0.028280543            0.1248843
   month_diff pct_white  pct_black pct_hispanic
1   0.6315789 0.7502917 0.03733956  0.075845974
2   0.6428571 0.7801911 0.07819288  0.078192876
3   1.0000000 0.3163265 0.00000000  0.224489796
4   1.2380952 0.5188510 0.04727708  0.052663076
5   0.4444444 0.5021097 0.25485232  0.033755274
6   1.0000000 0.9128440 0.00000000  0.000000000
7   0.7000000 0.6748311 0.06081081  0.016891892
8   0.8941176 0.4868282 0.14963119  0.050579557
9   1.6666667 0.6826923 0.08293269  0.049278846
10  0.6857143 0.7785571 0.02304609  0.050100200
11  1.2307692 0.3924775 0.05887163  0.080948487
12  1.3333333 0.7504132 0.00000000  0.069421488
13  0.7500000 0.6545139 0.03472222  0.072048611
14  0.4615385 0.6945747 0.00000000  0.050904220
15  1.2142857 0.7504472 0.01967800  0.057245081
16  1.1875000 0.7537260 0.08161817  0.044712562
17  1.0000000 0.6446488 0.07692308  0.040133779
18  0.5000000 0.9249531 0.00000000  0.016885553
19  1.5294118 0.9270517 0.02127660  0.031914894
20  0.9166667 0.6821330 0.10595568  0.038088643
21  0.9230769 0.7677665 0.05837563  0.015228426
22  0.7500000 0.8462255 0.05684995  0.027027027
23  2.0000000 0.7462121 0.02146465  0.157828283
24  1.1428571 0.7272727 0.05390185  0.049074819
25  0.9411765 0.5510949 0.35766423  0.000000000
26  1.2000000 0.6071006 0.25562130  0.056804734
27  0.5333333 0.5527124 0.36028659  0.015353122
28  1.2857143 0.5997249 0.14305365  0.038514443
29  0.5000000 0.8562691 0.09174312  0.000000000
30  0.2666667 0.7534247 0.13894325  0.086105675
31  1.1538462 0.7257282 0.14563107  0.009708738
32  1.1515152 0.5775862 0.34339080  0.040229885
33  0.8333333 0.2068966 0.69425287  0.011494253
34  0.3750000 0.4679487 0.38782051  0.060897436
35  1.0000000 0.4672269 0.42352941  0.013445378
36  1.0666667 0.7353464 0.01776199  0.177619893
37  1.2941176 0.6199203 0.18486056  0.075697211
38  0.5671642 0.3308550 0.48946716  0.099132590
39  0.6086957 0.5683269 0.07279693  0.204342273
40  0.7142857 0.7747748 0.13333333  0.082882883
41  0.4444444 0.4909794 0.01159794  0.295103093
42  0.4285714 0.7517241 0.12807882  0.150738916
43  1.0000000 0.8201811 0.02846054  0.119016818
44  0.7272727 0.4322470 0.14236707  0.174957118
45  0.8000000 0.5812721 0.30565371  0.070671378
46  0.9122807 0.2132353 0.60416667  0.064950980
47  1.2054795 0.1793722 0.72944694  0.065769806
48  0.9333333 0.5150100 0.36691127  0.099399600
49  0.9421488 0.1475096 0.83429119  0.000000000
50  0.8125000 0.2692308 0.58597285  0.083710407</code></pre>
</div>
</div>
<p>Next We import census geometry to join and visualize tract filing data</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import Census Tract Geometry</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tigris_use_cache =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Import for Philadelphia </span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>philadelphia_tracts <span class="ot">&lt;-</span> <span class="fu">tracts</span>(<span class="at">state =</span> <span class="st">"PA"</span>, <span class="at">county =</span> <span class="st">"Philadelphia"</span>, <span class="at">year =</span> <span class="dv">2022</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at Results</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(philadelphia_tracts<span class="sc">$</span>geometry)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="eviction_data_analysis_files/figure-html/Census Tracts-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="join-tracts-to-filings" class="level1">
<h1>Join Tracts to Filings</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make Sure Format Matches</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>philadelphia_tracts<span class="sc">$</span>GEOID <span class="ot">&lt;-</span> <span class="fu">as.character</span>(philadelphia_tracts<span class="sc">$</span>GEOID)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>tract_filings<span class="sc">$</span>id <span class="ot">&lt;-</span> <span class="fu">as.character</span>(tract_filings<span class="sc">$</span>id)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Join</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>evictions_geo <span class="ot">&lt;-</span> philadelphia_tracts <span class="sc">%&gt;%</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(tract_filings, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"GEOID"</span> <span class="ot">=</span> <span class="st">"id"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Here a map is made of tract filings.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(evictions_geo) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> month_rate), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option =</span> <span class="st">"magma"</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Eviction Rate by Census Tract"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Eviction Rate"</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="eviction_data_analysis_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>OTHER EDAS GO HERE</p>
<p>#Hotspots</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Read CSV</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>hotspots <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"hotspots/philadelphia_hotspots_media_report.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 75 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): time_period, end_date, xplaintiff, xstreet_clean
dbl (5): position, filings, top100, lat, lon

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Convert to sf object</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>hotspots_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  hotspots,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"lon"</span>, <span class="st">"lat"</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">crs =</span> <span class="dv">4326</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Read tract boundary</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>tracts <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"border/Census_Blocks_2010.geojson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `Census_Blocks_2010' from data source 
  `D:\pen\MUSA5080PublicPolicyAnalytics\portfolio-setup-Mayaano\assignments\final_project_analysis_process\border\Census_Blocks_2010.geojson' 
  using driver `GeoJSON'
Simple feature collection with 408 features and 27 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -75.28027 ymin: 39.86705 xmax: -74.95578 ymax: 40.13799
Geodetic CRS:  NAD83</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Reproject hotspots to match tracts CRS</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>hotspots_sf <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(hotspots_sf, <span class="fu">st_crs</span>(tracts))</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Map tracts + hotspots</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> tracts, <span class="at">fill =</span> <span class="st">"grey95"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> hotspots_sf,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">size =</span> filings),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.7</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">name =</span> <span class="st">"Eviction filings"</span>) <span class="sc">+</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Eviction Hotspots over Census Tracts"</span>,</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Top 100 buildings in Philadelphia"</span>,</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: Eviction Tracking System, ACS, Census tracts"</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="eviction_data_analysis_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Eviction filings exhibit marked geographic concentration in Philadelphia. North Philadelphia (40.05°N-40.15°N) shows the densest clustering with 100+ filings, reflecting historically disinvested, predominantly Black neighborhoods. West Philadelphia and South Philadelphia display secondary hotspots (50-75 filings), while Northeast suburbs show minimal activity. This stark contrast demonstrates housing instability is geographically concentrated among vulnerable populations. For predictive modeling, spatial clustering indicates temporal lag effects and racialized patterns reflecting structural inequality. The geographic specificity enables targeted prevention interventions in highest-need areas, though we acknowledge filings may reflect both tenant vulnerability and landlord enforcement variation.</p>
</section>
<section id="trends" class="level1">
<h1>trends</h1>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="trends.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="100"></p>
</figure>
</div>
</div>
</div>
<p>Dataset contains 72 monthly observations from January 2020 to December 2024 (5 years) with eviction filing counts, historical averages, and deviation metrics. Key Findings Temporal Trends: Eviction filings show clear recovery pattern post-2020. 2020-2021 experienced dramatic suppression (COVID-19 moratoriums), with filings dropping to near-zero in April-June 2020. Recovery accelerated from 2022 onwards, stabilizing around 1,000-1,200 filings monthly by 2023-2024. Seasonality: Weak seasonal pattern exists—January and August show slightly elevated filings (1.55× and 1.55× of average), while April-May show lower activity (0.20× and 0.16× of average 2020-2021 data). This reflects policy implementation timing. Year-over-Year Comparison: 2024 average (1,061 filings) closely mirrors 2023 (1,059 filings), indicating market stabilization post-recovery. 2025 preliminary data suggests continued stability with minor volatility. Volatility: Coefficient of variation decreased over time, showing market normalization after pandemic disruptions. Recent years exhibit more predictable patterns than 2020-2021 volatility. Implications Data supports stable eviction environment with predictable monthly volumes suitable for forecasting models.</p>
</section>
<section id="trends-1" class="level1">
<h1>trends</h1>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="price.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="100"></p>
</figure>
</div>
</div>
</div>
<p>hiladelphia Census Tracts: Geospatial Analysis These choropleth maps visualize key socioeconomic indicators across Philadelphia’s census tracts, revealing significant spatial disparities in poverty rates, unemployment, rent burden, and demographic composition. The darker regions indicate higher concentrations of economic vulnerability, with notable clustering in North and West Philadelphia tracts showing elevated poverty, unemployment, and rental cost burdens exceeding 30% of household income. Demographic analysis reveals stark residential segregation patterns, with distinct geographic concentrations of racial and ethnic populations. These spatial patterns align with historical inequities in housing access, economic opportunity, and community investment, providing critical context for understanding eviction vulnerability and housing instability across the city.</p>
</section>
<section id="choice-of-dependent-variable" class="level1">
<h1>Choice of Dependent Variable</h1>
<p>The dependent variable in this analysis is percentage_diff, which measures the monthly deviation of eviction filings from a long-term baseline. Rather than modeling raw eviction counts, this transformation captures relative change in eviction activity, allowing the analysis to focus on fluctuations around typical levels. This is particularly important in Philadelphia and other large cities, where eviction volumes vary seasonally and were disrupted by major economic disruptions such as the COVID-19. By using a normalized measure, the model isolates meaningful economic variation instead of conflating structural patterns with short-term dynamics.</p>
<p>From an economic perspective, percentage_diff is better suited than raw counts because it reflects marginal responses to changing conditions, which is the core interest of applied economic analysis. Labor market shocks, inflation, and household financial stress do not directly determine how many eviction cases exist in absolute terms; instead, they influence whether eviction pressure rises or falls relative to normal conditions. Modeling deviations from a baseline aligns the dependent variable with economic theory on cyclical stress, making the results more applicable for policy analysis and more appropriate for regression-based inference.</p>
</section>
<section id="data-cleaning" class="level1">
<h1>Data Cleaning</h1>
<p>This restructures the economic and financial datasets to make them analytically compatible with monthly eviction data. The Urban Institute financial health dataset comes in a report-style format rather than a machine-ready table, with multiple header and metadata rows embedded in the file. To correct this, we make row 4 the column headers, replace missing or blank column names with placeholders to allow selection and filtering, remove non-data rows, and isolate the row corresponding to Philadelphia. All remaining variables are then changed to numeric format, ensuring that these indicators—such as debt burden, housing cost stress, and labor force participation—can be used in regression-based modeling. These steps are necessary because model estimation and validation require numeric, consistently formatted inputs.</p>
<p>The Consumer Price Index and unemployment datasets require a different but similar cleaning approach because both are come in wide, month-column formats with extensive metadata. We identify the true header rows, remove non-data rows, convert month columns to numeric values, and reshape each dataset into a long format with one row per year–month observation. These transformations are important because the eviction outcome is measured monthly, and predictive modeling requires all time-varying variables to align. A month lookup table is made to convert month names into numeric values, ensuring consistent joins across datasets. The cleaned CPI and unemployment data are then merged into the monthly eviction trend dataset using year and month keys.</p>
<p>Finally, the cleaned Urban Institute financial indicators are appended to the eviction trends dataset using a dummy join, reflecting the fact that these measures describe baseline household financial vulnerability rather than month-specific disruptions. Lagged versions of key eviction outcome variables are then constructed to capture temporal lag in eviction activity, a main feature of eviction processes given legal delays and accumulated financial stress. These lag variables enable the model to distinguish between short-term economic fluctuations and ongoing eviction patterns.</p>
<p><strong><em>Note: Thus far we had not had any issues with the Urban Institute Data, later will reveal why it is more difficult for this analysis</em></strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data Cleaning</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean Financial Health Data</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>financial_health_clean <span class="ot">&lt;-</span> financial_health</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Use row 4 as header</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(financial_health_clean) <span class="ot">&lt;-</span> <span class="fu">as.character</span>(<span class="fu">unlist</span>(financial_health_clean[<span class="dv">4</span>, ]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `value` argument of `names&lt;-()` can't be empty as of tibble 3.0.0.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace blank/NA column names with placeholders</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>bad_name_index <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">is.na</span>(<span class="fu">names</span>(financial_health_clean)) <span class="sc">|</span> <span class="fu">names</span>(financial_health_clean) <span class="sc">==</span> <span class="st">""</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(bad_name_index) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(financial_health_clean)[bad_name_index] <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"col_"</span>, <span class="fu">seq_along</span>(bad_name_index))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove metadata rows 1–4, keep Philadelphia only</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>financial_health_clean <span class="ot">&lt;-</span> financial_health_clean[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>), ] <span class="sc">%&gt;%</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(City <span class="sc">==</span> <span class="st">"Philadelphia, PA"</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert all but City to numeric</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>financial_health_numeric_columns <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="fu">names</span>(financial_health_clean), <span class="st">"City"</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>financial_health_clean[financial_health_numeric_columns] <span class="ot">&lt;-</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(financial_health_clean[financial_health_numeric_columns], as.numeric)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean CPI Data</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>cpi_wide <span class="ot">&lt;-</span> consumer_price_index</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Real header is row 11</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cpi_wide) <span class="ot">&lt;-</span> <span class="fu">as.character</span>(<span class="fu">unlist</span>(cpi_wide[<span class="dv">11</span>, ]))</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>cpi_wide <span class="ot">&lt;-</span> cpi_wide[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>), ]</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>cpi_wide<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">as.numeric</span>(cpi_wide<span class="sc">$</span>Year))</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>cpi_month_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Jan"</span>,<span class="st">"Feb"</span>,<span class="st">"Mar"</span>,<span class="st">"Apr"</span>,<span class="st">"May"</span>,<span class="st">"Jun"</span>,</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Jul"</span>,<span class="st">"Aug"</span>,<span class="st">"Sep"</span>,<span class="st">"Oct"</span>,<span class="st">"Nov"</span>,<span class="st">"Dec"</span>)</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert month columns to numeric</span></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (col <span class="cf">in</span> cpi_month_names) {</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (col <span class="sc">%in%</span> <span class="fu">names</span>(cpi_wide)) {</span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>    cpi_wide[[col]] <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(cpi_wide[[col]])</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Month lookup table</span></span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a>month_lookup <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">month_name =</span> cpi_month_names,</span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">month =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span></span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert CPI to long format</span></span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a>cpi_long <span class="ot">&lt;-</span> cpi_wide <span class="sc">%&gt;%</span></span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Year, <span class="fu">all_of</span>(cpi_month_names)) <span class="sc">%&gt;%</span></span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">all_of</span>(cpi_month_names),</span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"month_name"</span>,</span>
<span id="cb19-48"><a href="#cb19-48" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"cpi"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-49"><a href="#cb19-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(cpi)) <span class="sc">%&gt;%</span></span>
<span id="cb19-50"><a href="#cb19-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(month_lookup, <span class="at">by =</span> <span class="st">"month_name"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-51"><a href="#cb19-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">year =</span> Year)</span>
<span id="cb19-52"><a href="#cb19-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-53"><a href="#cb19-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-54"><a href="#cb19-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-55"><a href="#cb19-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean Unemployment Data</span></span>
<span id="cb19-56"><a href="#cb19-56" aria-hidden="true" tabindex="-1"></a>unemployment_wide <span class="ot">&lt;-</span> unemployment_monthly</span>
<span id="cb19-57"><a href="#cb19-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-58"><a href="#cb19-58" aria-hidden="true" tabindex="-1"></a><span class="co"># Row 10 is the real header</span></span>
<span id="cb19-59"><a href="#cb19-59" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(unemployment_wide) <span class="ot">&lt;-</span> <span class="fu">as.character</span>(<span class="fu">unlist</span>(unemployment_wide[<span class="dv">10</span>, ]))</span>
<span id="cb19-60"><a href="#cb19-60" aria-hidden="true" tabindex="-1"></a>unemployment_wide <span class="ot">&lt;-</span> unemployment_wide[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>), ]</span>
<span id="cb19-61"><a href="#cb19-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-62"><a href="#cb19-62" aria-hidden="true" tabindex="-1"></a>unemployment_wide<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">as.numeric</span>(unemployment_wide<span class="sc">$</span>Year))</span>
<span id="cb19-63"><a href="#cb19-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-64"><a href="#cb19-64" aria-hidden="true" tabindex="-1"></a>unemployment_month_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Jan"</span>,<span class="st">"Feb"</span>,<span class="st">"Mar"</span>,<span class="st">"Apr"</span>,<span class="st">"May"</span>,<span class="st">"Jun"</span>,</span>
<span id="cb19-65"><a href="#cb19-65" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Jul"</span>,<span class="st">"Aug"</span>,<span class="st">"Sep"</span>,<span class="st">"Oct"</span>,<span class="st">"Nov"</span>,<span class="st">"Dec"</span>)</span>
<span id="cb19-66"><a href="#cb19-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-67"><a href="#cb19-67" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert month columns to numeric</span></span>
<span id="cb19-68"><a href="#cb19-68" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (col <span class="cf">in</span> unemployment_month_names) {</span>
<span id="cb19-69"><a href="#cb19-69" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (col <span class="sc">%in%</span> <span class="fu">names</span>(unemployment_wide)) {</span>
<span id="cb19-70"><a href="#cb19-70" aria-hidden="true" tabindex="-1"></a>    unemployment_wide[[col]] <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(unemployment_wide[[col]])</span>
<span id="cb19-71"><a href="#cb19-71" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb19-72"><a href="#cb19-72" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-73"><a href="#cb19-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-74"><a href="#cb19-74" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert unemployment data to long format</span></span>
<span id="cb19-75"><a href="#cb19-75" aria-hidden="true" tabindex="-1"></a>unemployment_long <span class="ot">&lt;-</span> unemployment_wide <span class="sc">%&gt;%</span></span>
<span id="cb19-76"><a href="#cb19-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Year, <span class="fu">all_of</span>(unemployment_month_names)) <span class="sc">%&gt;%</span></span>
<span id="cb19-77"><a href="#cb19-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">all_of</span>(unemployment_month_names),</span>
<span id="cb19-78"><a href="#cb19-78" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"month_name"</span>,</span>
<span id="cb19-79"><a href="#cb19-79" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"unemployment_rate"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-80"><a href="#cb19-80" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(unemployment_rate)) <span class="sc">%&gt;%</span></span>
<span id="cb19-81"><a href="#cb19-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(month_lookup, <span class="at">by =</span> <span class="st">"month_name"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-82"><a href="#cb19-82" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">year =</span> Year)</span>
<span id="cb19-83"><a href="#cb19-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-84"><a href="#cb19-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-85"><a href="#cb19-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-86"><a href="#cb19-86" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean Monthly Eviction Trend Data</span></span>
<span id="cb19-87"><a href="#cb19-87" aria-hidden="true" tabindex="-1"></a><span class="co"># Parse month and year</span></span>
<span id="cb19-88"><a href="#cb19-88" aria-hidden="true" tabindex="-1"></a>eviction_trends_clean <span class="ot">&lt;-</span> eviction_trends <span class="sc">%&gt;%</span></span>
<span id="cb19-89"><a href="#cb19-89" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-90"><a href="#cb19-90" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_num =</span> <span class="fu">as.integer</span>(<span class="fu">substr</span>(month, <span class="dv">1</span>, <span class="dv">2</span>)),</span>
<span id="cb19-91"><a href="#cb19-91" aria-hidden="true" tabindex="-1"></a>    <span class="at">year      =</span> <span class="fu">as.integer</span>(<span class="fu">substr</span>(month, <span class="dv">4</span>, <span class="dv">7</span>)),</span>
<span id="cb19-92"><a href="#cb19-92" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_date =</span> <span class="fu">paste0</span>(year, <span class="st">"-"</span>, month_num, <span class="st">"-01"</span>)</span>
<span id="cb19-93"><a href="#cb19-93" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-94"><a href="#cb19-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-95"><a href="#cb19-95" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge with unemployment and CPI</span></span>
<span id="cb19-96"><a href="#cb19-96" aria-hidden="true" tabindex="-1"></a>eviction_trends_merged <span class="ot">&lt;-</span> eviction_trends_clean <span class="sc">%&gt;%</span></span>
<span id="cb19-97"><a href="#cb19-97" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(unemployment_long,</span>
<span id="cb19-98"><a href="#cb19-98" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span> <span class="ot">=</span> <span class="st">"year"</span>, <span class="st">"month_num"</span> <span class="ot">=</span> <span class="st">"month"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb19-99"><a href="#cb19-99" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(cpi_long,</span>
<span id="cb19-100"><a href="#cb19-100" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span> <span class="ot">=</span> <span class="st">"year"</span>, <span class="st">"month_num"</span> <span class="ot">=</span> <span class="st">"month"</span>))</span>
<span id="cb19-101"><a href="#cb19-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-102"><a href="#cb19-102" aria-hidden="true" tabindex="-1"></a><span class="co"># Attach Urban Institute financial variables</span></span>
<span id="cb19-103"><a href="#cb19-103" aria-hidden="true" tabindex="-1"></a>eviction_trends_merged <span class="ot">&lt;-</span> eviction_trends_merged <span class="sc">%&gt;%</span></span>
<span id="cb19-104"><a href="#cb19-104" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dummy =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-105"><a href="#cb19-105" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(financial_health_clean <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">dummy =</span> <span class="dv">1</span>), <span class="at">by =</span> <span class="st">"dummy"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-106"><a href="#cb19-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>dummy)</span>
<span id="cb19-107"><a href="#cb19-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-108"><a href="#cb19-108" aria-hidden="true" tabindex="-1"></a><span class="co"># Add lag variables</span></span>
<span id="cb19-109"><a href="#cb19-109" aria-hidden="true" tabindex="-1"></a>eviction_trends_final <span class="ot">&lt;-</span> eviction_trends_merged <span class="sc">%&gt;%</span></span>
<span id="cb19-110"><a href="#cb19-110" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(year, month_num) <span class="sc">%&gt;%</span></span>
<span id="cb19-111"><a href="#cb19-111" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-112"><a href="#cb19-112" aria-hidden="true" tabindex="-1"></a>    <span class="at">l1_filings =</span> <span class="fu">lag</span>(month_filings, <span class="dv">1</span>),</span>
<span id="cb19-113"><a href="#cb19-113" aria-hidden="true" tabindex="-1"></a>    <span class="at">l1_percentage_diff =</span> <span class="fu">lag</span>(percentage_diff, <span class="dv">1</span>)</span>
<span id="cb19-114"><a href="#cb19-114" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="assess-if-data-cleaning-worked" class="level1">
<h1>Assess if Data Cleaning Worked</h1>
<p>Here we check to see if our new data sets are how we intended them.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check Financial Health</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Financial Health Clean"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Financial Health Clean</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">str</span>(financial_health_clean))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1 × 18] (S3: tbl_df/tbl/data.frame)
 $ City                                 : chr "Philadelphia, PA"
 $ Overall                              : num 628
 $ White areas                          : num 703
 $ Nonwhite areas                       : num 571
 $ col_1                                : num NA
 $ % with                               : num 0.466
 $ Median amount among those with       : num 1476
 $ col_2                                : num NA
 $ % with home foreclosure              : num 0.00435
 $ % housing-cost burdened, low-income  : num 0.68
 $ % unbanked, metro area               : num 0.041
 $ % with health insurance coverage     : num 0.857
 $ % received EITC, low-income          : num 0.415
 $ Unemployment rate                    : num 0.109
 $ Labor force participation rate       : num 0.604
 $ % below 200% of federal poverty level: num 0.46
 $ % population change, 2000–15         : num 0.0329
 $ Gini index of income inequality      : num 0.505
NULL</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(financial_health_clean))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 18
  City             Overall `White areas` `Nonwhite areas` col_1 `% with`
  &lt;chr&gt;              &lt;dbl&gt;         &lt;dbl&gt;            &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
1 Philadelphia, PA     628           703              571    NA    0.466
# ℹ 12 more variables: `Median amount among those with` &lt;dbl&gt;, col_2 &lt;dbl&gt;,
#   `% with home foreclosure` &lt;dbl&gt;,
#   `% housing-cost burdened, low-income` &lt;dbl&gt;,
#   `% unbanked, metro area` &lt;dbl&gt;, `% with health insurance coverage` &lt;dbl&gt;,
#   `% received EITC, low-income` &lt;dbl&gt;, `Unemployment rate` &lt;dbl&gt;,
#   `Labor force participation rate` &lt;dbl&gt;,
#   `% below 200% of federal poverty level` &lt;dbl&gt;, …</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check CPI Long Format</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"CPI Long Format"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>CPI Long Format</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">str</span>(cpi_long))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [64 × 4] (S3: tbl_df/tbl/data.frame)
 $ year      : int [1:64] 2015 2015 2015 2015 2015 2015 2016 2016 2016 2016 ...
 $ month_name: chr [1:64] "Feb" "Apr" "Jun" "Aug" ...
 $ cpi       : num [1:64] 242 244 246 245 244 ...
 $ month     : int [1:64] 2 4 6 8 10 12 2 4 6 8 ...
NULL</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(cpi_long))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
   year month_name   cpi month
  &lt;int&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;
1  2015 Feb         242.     2
2  2015 Apr         244.     4
3  2015 Jun         246.     6
4  2015 Aug         245.     8
5  2015 Oct         244.    10
6  2015 Dec         242.    12</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check Unemployment Long Format</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Unemployment Long Format"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Unemployment Long Format</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">str</span>(unemployment_long))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [128 × 4] (S3: tbl_df/tbl/data.frame)
 $ year             : int [1:128] 2015 2015 2015 2015 2015 2015 2015 2015 2015 2015 ...
 $ month_name       : chr [1:128] "Jan" "Feb" "Mar" "Apr" ...
 $ unemployment_rate: num [1:128] 6.2 6 5.7 5.2 5.7 5.7 6.1 5.7 5.1 4.9 ...
 $ month            : int [1:128] 1 2 3 4 5 6 7 8 9 10 ...
NULL</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(unemployment_long))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
   year month_name unemployment_rate month
  &lt;int&gt; &lt;chr&gt;                  &lt;dbl&gt; &lt;int&gt;
1  2015 Jan                      6.2     1
2  2015 Feb                      6       2
3  2015 Mar                      5.7     3
4  2015 Apr                      5.2     4
5  2015 May                      5.7     5
6  2015 Jun                      5.7     6</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check Eviction Data</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Eviction Trends Final After Macro UI Merge &amp; Lag"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Eviction Trends Final After Macro UI Merge &amp; Lag</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">str</span>(eviction_trends_final))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   70 obs. of  32 variables:
 $ month                                : chr  "01/2020" "02/2020" "03/2020" "04/2020" ...
 $ month_last_day                       : logi  NA NA NA NA NA NA ...
 $ month_filings                        : int  2015 1720 813 0 0 0 198 176 701 792 ...
 $ avg_filings                          : num  1294 1194 1142 925 1065 ...
 $ percentage_diff                      : num  1.557 1.441 0.712 0 0 ...
 $ month_num                            : int  1 2 3 4 5 6 7 8 9 10 ...
 $ year                                 : int  2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 ...
 $ month_date                           : chr  "2020-1-01" "2020-2-01" "2020-3-01" "2020-4-01" ...
 $ month_name.x                         : chr  "Jan" "Feb" "Mar" "Apr" ...
 $ unemployment_rate                    : num  4.3 4.2 4.9 13.9 13.4 12.9 12 10.4 8.6 7.4 ...
 $ month_name.y                         : chr  NA "Feb" NA "Apr" ...
 $ cpi                                  : num  NA 260 NA 256 NA ...
 $ City                                 : chr  "Philadelphia, PA" "Philadelphia, PA" "Philadelphia, PA" "Philadelphia, PA" ...
 $ Overall                              : num  628 628 628 628 628 628 628 628 628 628 ...
 $ White areas                          : num  703 703 703 703 703 703 703 703 703 703 ...
 $ Nonwhite areas                       : num  571 571 571 571 571 571 571 571 571 571 ...
 $ col_1                                : num  NA NA NA NA NA NA NA NA NA NA ...
 $ % with                               : num  0.466 0.466 0.466 0.466 0.466 ...
 $ Median amount among those with       : num  1476 1476 1476 1476 1476 ...
 $ col_2                                : num  NA NA NA NA NA NA NA NA NA NA ...
 $ % with home foreclosure              : num  0.00435 0.00435 0.00435 0.00435 0.00435 ...
 $ % housing-cost burdened, low-income  : num  0.68 0.68 0.68 0.68 0.68 ...
 $ % unbanked, metro area               : num  0.041 0.041 0.041 0.041 0.041 ...
 $ % with health insurance coverage     : num  0.857 0.857 0.857 0.857 0.857 ...
 $ % received EITC, low-income          : num  0.415 0.415 0.415 0.415 0.415 ...
 $ Unemployment rate                    : num  0.109 0.109 0.109 0.109 0.109 ...
 $ Labor force participation rate       : num  0.604 0.604 0.604 0.604 0.604 ...
 $ % below 200% of federal poverty level: num  0.46 0.46 0.46 0.46 0.46 ...
 $ % population change, 2000–15         : num  0.0329 0.0329 0.0329 0.0329 0.0329 ...
 $ Gini index of income inequality      : num  0.505 0.505 0.505 0.505 0.505 ...
 $ l1_filings                           : int  NA 2015 1720 813 0 0 0 198 176 701 ...
 $ l1_percentage_diff                   : num  NA 1.557 1.441 0.712 0 ...
NULL</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(eviction_trends_final))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    month month_last_day month_filings avg_filings percentage_diff month_num
1 01/2020             NA          2015      1294.5       1.5565856         1
2 02/2020             NA          1720      1193.5       1.4411395         2
3 03/2020             NA           813      1142.5       0.7115974         3
4 04/2020             NA             0       925.0       0.0000000         4
5 05/2020             NA             0      1065.0       0.0000000         5
6 06/2020             NA             0      1032.0       0.0000000         6
  year month_date month_name.x unemployment_rate month_name.y     cpi
1 2020  2020-1-01          Jan               4.3         &lt;NA&gt;      NA
2 2020  2020-2-01          Feb               4.2          Feb 259.694
3 2020  2020-3-01          Mar               4.9         &lt;NA&gt;      NA
4 2020  2020-4-01          Apr              13.9          Apr 256.353
5 2020  2020-5-01          May              13.4         &lt;NA&gt;      NA
6 2020  2020-6-01          Jun              12.9          Jun 257.983
              City Overall White areas Nonwhite areas col_1    % with
1 Philadelphia, PA     628         703            571    NA 0.4660742
2 Philadelphia, PA     628         703            571    NA 0.4660742
3 Philadelphia, PA     628         703            571    NA 0.4660742
4 Philadelphia, PA     628         703            571    NA 0.4660742
5 Philadelphia, PA     628         703            571    NA 0.4660742
6 Philadelphia, PA     628         703            571    NA 0.4660742
  Median amount among those with col_2 % with home foreclosure
1                           1476    NA             0.004345603
2                           1476    NA             0.004345603
3                           1476    NA             0.004345603
4                           1476    NA             0.004345603
5                           1476    NA             0.004345603
6                           1476    NA             0.004345603
  % housing-cost burdened, low-income % unbanked, metro area
1                           0.6803305                  0.041
2                           0.6803305                  0.041
3                           0.6803305                  0.041
4                           0.6803305                  0.041
5                           0.6803305                  0.041
6                           0.6803305                  0.041
  % with health insurance coverage % received EITC, low-income
1                        0.8566335                   0.4151677
2                        0.8566335                   0.4151677
3                        0.8566335                   0.4151677
4                        0.8566335                   0.4151677
5                        0.8566335                   0.4151677
6                        0.8566335                   0.4151677
  Unemployment rate Labor force participation rate
1         0.1093104                      0.6044449
2         0.1093104                      0.6044449
3         0.1093104                      0.6044449
4         0.1093104                      0.6044449
5         0.1093104                      0.6044449
6         0.1093104                      0.6044449
  % below 200% of federal poverty level % population change, 2000–15
1                             0.4603734                   0.03287668
2                             0.4603734                   0.03287668
3                             0.4603734                   0.03287668
4                             0.4603734                   0.03287668
5                             0.4603734                   0.03287668
6                             0.4603734                   0.03287668
  Gini index of income inequality l1_filings l1_percentage_diff
1                          0.5049         NA                 NA
2                          0.5049       2015          1.5565856
3                          0.5049       1720          1.4411395
4                          0.5049        813          0.7115974
5                          0.5049          0          0.0000000
6                          0.5049          0          0.0000000</code></pre>
</div>
</div>
</section>
<section id="creating-the-model" class="level1">
<h1>Creating the Model</h1>
</section>
<section id="step-1-creating-the-model-data-set" class="level1">
<h1>Step 1: Creating the Model Data Set</h1>
<p>This step constructs the modeling dataset used for regression analysis. Each row in the resulting dataset represents a single month, with aligned economic, financial, and temporal predictors. The dependent variable, percentage_diff, measures how eviction filings in a given month deviate from a historical average, making it a continuous outcome well suited for linear regression. Predictor variables include lagged eviction activity (l1_percentage_diff) to capture temporal lag, macroeconomic indicators (unemployment_rate, cpi) to reflect short-term economic conditions, and Urban Institute financial health indicators that quantify underlying household vulnerability. Observations with missing outcome values are removed to ensure valid model estimation and consistent sample sizes across all predictors.</p>
<p>Ordinary Least Squares (OLS) regression is an appropriate and intentional modeling choice for this dataset given both the structure of the outcome and the nature of the predictors. The dependent variable is continuous and approximately symmetric around its mean, rather than binary or integer-count based, ruling out logistic and Poisson-style models. The predictors are a mix of continuous economic measures and proportion-based indicators, all of which naturally conform to the linear framework assumed by OLS. OLS also offers transparent coefficient interpretation, allowing each variable’s association with eviction deviations to be directly assessed, an important requirement for a policy-focused project. Additionally, OLS performs well with moderate sample sizes and does not impose unnecessary distribution assumptions beyond linearity and conditional independence. This makes OLS regression suitable for evaluating how economic disruptions and financial vulnerability jointly shape month-to-month eviction dynamics.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare modeling dataset </span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>model_df <span class="ot">&lt;-</span> eviction_trends_final <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    year, month_num,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    month_filings,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    percentage_diff,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    l1_percentage_diff,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>    unemployment_rate,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    cpi,</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>    Overall,</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">White areas</span><span class="st">`</span>,</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Nonwhite areas</span><span class="st">`</span>,</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% with</span><span class="st">`</span>,</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Median amount among those with</span><span class="st">`</span>,</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% housing-cost burdened, low-income</span><span class="st">`</span>,</span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% with home foreclosure</span><span class="st">`</span>,</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% unbanked, metro area</span><span class="st">`</span>,</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% received EITC, low-income</span><span class="st">`</span>,</span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Labor force participation rate</span><span class="st">`</span>,</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% below 200% of federal poverty level</span><span class="st">`</span>,</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Gini index of income inequality</span><span class="st">`</span></span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(percentage_diff))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="step-2-fit-regression-model" class="level1">
<h1>Step 2: Fit Regression Model</h1>
<p>Here the model is fit with the predictors.</p>
</section>
<section id="important-finding" class="level1">
<h1>Important Finding</h1>
<p>The regression results revealed an important characteristic of the Urban Institute (UI) financial health variables. Although they are meaningful, they do not vary within the temporal unit used for modeling. Because remain constant across all rows in the monthly dataset, these variables are perfectly collinear with the model intercept and are therefore dropped during estimation due to singularities. This behavior is expected under Ordinary Least Squares. More time would be needed to fully assess and correct this issue or to source new data with the same measures. Despite not receiving individual coefficient estimates, the UI variables still play an important conceptual role in the analysis. They provide context for the economic environment in which evictions occur, anchoring short-term fluctuations in broader measures of financial vulnerability such as housing cost burden, foreclosure prevalence, and income inequality. Rather than being interpreted as predictors, these variables help frame the limits of month-to-month responsiveness by describing the underlying baseline risk faced by households in Philadelphia.</p>
<section id="why-predict-percentage-diff-why-ols" class="level2">
<h2 class="anchored" data-anchor-id="why-predict-percentage-diff-why-ols">Why Predict Percentage Diff? Why OLS?</h2>
<section id="choice-of-dependent-variable-1" class="level3">
<h3 class="anchored" data-anchor-id="choice-of-dependent-variable-1">Choice of Dependent Variable</h3>
<p>Several outcome variables were considered: - Raw filing counts (absolute numbers) - Filing rates (filings per capita) - Binary spike indicators (above/below threshold)</p>
<p>We selected <code>percentage_diff</code> (monthly deviation from historical baseline) because:</p>
<ol type="1">
<li><strong>Removes seasonality</strong>: Isolates economic stress changes from structural seasonal patterns</li>
<li><strong>Continuous &amp; symmetric</strong>: Produces normally distributed outcomes suitable for OLS regression</li>
<li><strong>Policy interpretability</strong>: Allows decision-makers to compare current risk to typical conditions</li>
<li><strong>Comparable across time</strong>: Baseline adjustment ensures year-to-year comparisons are meaningful</li>
</ol>
</section>
<section id="why-ols-is-appropriate" class="level3">
<h3 class="anchored" data-anchor-id="why-ols-is-appropriate">Why OLS is Appropriate</h3>
<p>OLS regression is the appropriate model because:</p>
<ol type="1">
<li><strong>Continuous outcome</strong>: <code>percentage_diff</code> is a continuous, unbounded variable (not count, not binary)</li>
<li><strong>Macroeconomic predictors</strong>: Our features (unemployment, CPI, financial vulnerability) are standard in linear economic models</li>
<li><strong>Interpretability over prediction</strong>: Policy use requires transparent coefficient estimates, not black-box predictions</li>
<li><strong>Sufficient sample size</strong>: 72 months of observations supports reliable OLS estimation</li>
</ol>
<p>Alternative models were rejected: - Logistic/probit: Not suitable for continuous percentage outcomes - Poisson/negative binomial: Designed for count data, not percentage deviations - Machine learning (random forest, neural nets): Sacrifices interpretability needed for policy briefings</p>
</section>
</section>
<section id="feature-engineering-strategy" class="level2">
<h2 class="anchored" data-anchor-id="feature-engineering-strategy">Feature Engineering Strategy</h2>
<section id="features-implemented" class="level3">
<h3 class="anchored" data-anchor-id="features-implemented">Features Implemented</h3>
<ol type="1">
<li><p><strong>Lagged eviction pressure</strong> (<code>l1_percentage_diff</code>): 1-month lag captures procedural delays in eviction filings and accumulation of financial strain across months</p></li>
<li><p><strong>Macroeconomic indicators</strong> (<code>unemployment_rate</code>, <code>cpi</code>): Month-aligned predictors of household financial stress and purchasing power</p></li>
<li><p><strong>Household financial vulnerability</strong> (Urban Institute indicators):</p>
<ul>
<li><code>% housing-cost burdened, low-income</code>: Direct measure of rent burden</li>
<li><code>% with home foreclosure</code>: Proxy for credit stress</li>
<li><code>% unbanked, metro area</code>: Financial system exclusion</li>
<li><code>% received EITC, low-income</code>: Indicator of low-income status</li>
<li><code>Labor force participation rate</code>: Employment access</li>
<li><code>% below 200% of federal poverty level</code>: Poverty concentration</li>
<li><code>Gini index of income inequality</code>: Income distribution stress</li>
</ul></li>
<li><p><strong>Claim amount</strong> (<code>Median amount among those with</code>): Direct measure of eviction filing severity</p></li>
</ol>
</section>
<section id="features-tested-but-excluded" class="level3">
<h3 class="anchored" data-anchor-id="features-tested-but-excluded">Features Tested but Excluded</h3>
<p>The following feature engineering approaches were explored but ultimately excluded:</p>
<ol type="1">
<li><strong>Spatial lags</strong> (adjacency-weighted filing pressure from neighboring tracts): High multicollinearity with baseline unemployment; excluded to preserve model interpretability</li>
<li><strong>Interaction terms</strong> (unemployment × financial burden): Overfitting concerns with limited sample size (n=72); would require out-of-sample validation</li>
<li><strong>K-means neighborhood clusters</strong>: Redundant with macroeconomic controls; added complexity without predictive gain</li>
<li><strong>Seasonality dummies</strong> (month fixed effects): Already removed by percentage_diff baseline adjustment</li>
<li><strong>ARIMA-style autoregressive terms beyond lag-1</strong>: Temporal autocorrelation was minimal post-lag inclusion</li>
</ol>
</section>
<section id="justification" class="level3">
<h3 class="anchored" data-anchor-id="justification">Justification</h3>
<p>The final feature set balances <strong>model parsimony</strong> (avoid overfitting with 72 observations) with <strong>policy relevance</strong> (interpretable economic mechanisms). Future work should explore spatial clustering and interaction effects with larger datasets or longer time series.</p>
<hr>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>eviction_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  percentage_diff <span class="sc">~</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>    l1_percentage_diff <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    unemployment_rate <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    cpi <span class="sc">+</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Median amount among those with</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% housing-cost burdened, low-income</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% with home foreclosure</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% unbanked, metro area</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% received EITC, low-income</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Labor force participation rate</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% below 200% of federal poverty level</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Gini index of income inequality</span><span class="st">`</span>,</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> model_df</span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(eviction_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = percentage_diff ~ l1_percentage_diff + unemployment_rate + 
    cpi + `Median amount among those with` + `% housing-cost burdened, low-income` + 
    `% with home foreclosure` + `% unbanked, metro area` + `% received EITC, low-income` + 
    `Labor force participation rate` + `% below 200% of federal poverty level` + 
    `Gini index of income inequality`, data = model_df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.39521 -0.06102 -0.00346  0.09482  0.57471 

Coefficients: (8 not defined because of singularities)
                                          Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                              0.5103766  0.6122573   0.834 0.411096
l1_percentage_diff                       0.5408035  0.1254763   4.310 0.000162
unemployment_rate                       -0.0663023  0.0192283  -3.448 0.001694
cpi                                      0.0006943  0.0019027   0.365 0.717740
`Median amount among those with`                NA         NA      NA       NA
`% housing-cost burdened, low-income`           NA         NA      NA       NA
`% with home foreclosure`                       NA         NA      NA       NA
`% unbanked, metro area`                        NA         NA      NA       NA
`% received EITC, low-income`                   NA         NA      NA       NA
`Labor force participation rate`                NA         NA      NA       NA
`% below 200% of federal poverty level`         NA         NA      NA       NA
`Gini index of income inequality`               NA         NA      NA       NA
                                           
(Intercept)                                
l1_percentage_diff                      ***
unemployment_rate                       ** 
cpi                                        
`Median amount among those with`           
`% housing-cost burdened, low-income`      
`% with home foreclosure`                  
`% unbanked, metro area`                   
`% received EITC, low-income`              
`Labor force participation rate`           
`% below 200% of federal poverty level`    
`Gini index of income inequality`          
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1821 on 30 degrees of freedom
  (因为不存在，36个观察量被删除了)
Multiple R-squared:  0.7975,    Adjusted R-squared:  0.7773 
F-statistic: 39.39 on 3 and 30 DF,  p-value: 1.59e-10</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="calculating-errors---root-mean-squared-error-and-mean-average-error---this-evaluates-in-sample-error" class="level1">
<h1>Calculating Errors - Root Mean Squared Error and Mean Average Error - This evaluates in sample error</h1>
</section>
<section id="model-validation-and-error-analysis" class="level1">
<h1>Model Validation and Error Analysis</h1>
<p>In-sample prediction error metrics were performed because the model includes lagged outcomes and economic predictors that are not observed for all periods, the regression was estimated using complete cases only. Validation was therefore first conducted on the same set of observations used in model estimation to ensure consistency between predicted and observed outcomes. Fitted values and residuals were extracted directly from the regression object to avoid misalignment caused by missing values.</p>
<p>Two standard error metrics were used to summarize model accuracy: Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE). MAE provides a measure of average deviation between predicted and observed eviction pressure, while RMSE penalizes larger errors more heavily and highlights sensitivity to extreme under- or over-prediction. Together, these metrics provide a concise assessment of model fit and establish a baseline level of predictive performance prior to out-of-sample validation.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model Validation: RMSE and MAE</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the data actually used by the model because of UI data issues</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>model_used <span class="ot">&lt;-</span> eviction_model<span class="sc">$</span>model</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract fitted values and residuals </span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> eviction_model<span class="sc">$</span>fitted.values</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> eviction_model<span class="sc">$</span>residuals</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute MAE</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(residuals))</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute RMSE</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(residuals<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Output results</span></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Model Performance Metrics:</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Model Performance Metrics:</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"MAE  ="</span>, <span class="fu">round</span>(mae, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>MAE  = 0.1225 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"RMSE ="</span>, <span class="fu">round</span>(rmse, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>RMSE = 0.1711 </code></pre>
</div>
</div>
</section>
<section id="test-train-split-validation---this-is-our-control-for-out-of-sample-validation" class="level1">
<h1>Test Train Split Validation - this is our control for out of sample validation</h1>
</section>
<section id="step-1---create-train-and-test-splits" class="level1">
<h1>Step 1 - Create Train and Test Splits</h1>
<p>This step implements a time-based train–test split to evaluate the model’s out-of-sample predictive performance. Observations are first ordered chronologically using numeric year and month variables. The dataset is then divided such that all observations prior to 2023 are used for model training, while observations from 2023 onward are reserved for testing. This corresponds to using approximately 75–80% of the available time series for training and the remaining 20–25% for out-of-sample evaluation, depending on the exact temporal coverage of the dataset. Unlike random splits, this approach mirrors real-world forecasting conditions by ensuring the model is evaluated only on future observations it has not seen during estimation.</p>
<p>This time-based split is intentionally chosen because the outcome of interest, (monthly changes in eviction activity) is inherently temporal. Randomly assigning observations to training and testing would risk temporal leakage, where the model indirectly learns from future data points. By training on earlier years and testing on later ones, this validation strategy provides a more realistic assessment of how well the model generalizes to new economic conditions. After splitting, complete-case filtering is applied consistently to both training and test sets to ensure the same variables are available in each, preventing estimation or prediction errors caused by missing values.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Train–Test Split</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Make numeric time variables</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>model_df_tt <span class="ot">&lt;-</span> model_df <span class="sc">%&gt;%</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">year_num  =</span> <span class="fu">as.integer</span>(year),</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_num =</span> <span class="cf">if</span> (<span class="st">"month_num"</span> <span class="sc">%in%</span> <span class="fu">names</span>(.)) month_num <span class="cf">else</span> <span class="fu">as.integer</span>(<span class="fu">substr</span>(month, <span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(year_num, month_num)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Train–test split by time</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>train_df <span class="ot">&lt;-</span> model_df_tt <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year_num <span class="sc">&lt;</span> <span class="dv">2023</span>)</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>test_df  <span class="ot">&lt;-</span> model_df_tt <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year_num <span class="sc">&gt;=</span> <span class="dv">2023</span>)</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables used in the model</span></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>model_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"percentage_diff"</span>,</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"l1_percentage_diff"</span>,</span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"unemployment_rate"</span>,</span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cpi"</span>,</span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Median amount among those with"</span>,</span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">"% housing-cost burdened, low-income"</span>,</span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">"% with home foreclosure"</span>,</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a>  <span class="st">"% unbanked, metro area"</span>,</span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a>  <span class="st">"% received EITC, low-income"</span>,</span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Labor force participation rate"</span>,</span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a>  <span class="st">"% below 200% of federal poverty level"</span>,</span>
<span id="cb53-28"><a href="#cb53-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Gini index of income inequality"</span></span>
<span id="cb53-29"><a href="#cb53-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-30"><a href="#cb53-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-31"><a href="#cb53-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only complete cases</span></span>
<span id="cb53-32"><a href="#cb53-32" aria-hidden="true" tabindex="-1"></a>train_df_clean <span class="ot">&lt;-</span> train_df <span class="sc">%&gt;%</span></span>
<span id="cb53-33"><a href="#cb53-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">if_all</span>(<span class="fu">all_of</span>(model_vars), <span class="sc">~</span> <span class="sc">!</span><span class="fu">is.na</span>(.)))</span>
<span id="cb53-34"><a href="#cb53-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-35"><a href="#cb53-35" aria-hidden="true" tabindex="-1"></a>test_df_clean <span class="ot">&lt;-</span> test_df <span class="sc">%&gt;%</span></span>
<span id="cb53-36"><a href="#cb53-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">if_all</span>(<span class="fu">all_of</span>(model_vars), <span class="sc">~</span> <span class="sc">!</span><span class="fu">is.na</span>(.)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="step-2---fit-model-on-training-data" class="level1">
<h1>Step 2 - Fit Model on Training Data</h1>
<p>We now fit the new split data on a model.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Model on Training Data</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>eviction_model_train <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  percentage_diff <span class="sc">~</span> </span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>    l1_percentage_diff <span class="sc">+</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>    unemployment_rate <span class="sc">+</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>    cpi <span class="sc">+</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Median amount among those with</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% housing-cost burdened, low-income</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% with home foreclosure</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% unbanked, metro area</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% received EITC, low-income</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Labor force participation rate</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% below 200% of federal poverty level</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Gini index of income inequality</span><span class="st">`</span>,</span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train_df_clean</span>
<span id="cb54-17"><a href="#cb54-17" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="step-3---predict-on-test-data" class="level1">
<h1>Step 3 - Predict on Test Data</h1>
<p>This step evaluates the predictive accuracy of the trained eviction model using the test dataset, which contains observations not used during model estimation. The model is applied to the test data to generate predicted values of monthly eviction changes, and these predictions are then compared to the observed outcomes. The differences between predicted and actual values (residuals) quantify how far the model’s forecasts deviate from reality when applied out of sample.</p>
<p>To summarize prediction error, we calculate Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE). MAE captures the average size of prediction mistakes, while RMSE places greater weight on larger errors, highlighting periods where the model performs particularly poorly. Reporting both metrics provides a robust assessment of out-of-sample performance and demonstrates that the model is not only statistically meaningful in-sample but also useful for forecasting future eviction trends.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Out-of-Sample Validation - Test Set</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on test set</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>test_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  eviction_model_train,</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> test_df_clean</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuals</span></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>test_residuals <span class="ot">&lt;-</span> test_df_clean<span class="sc">$</span>percentage_diff <span class="sc">-</span> test_predictions</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a><span class="co"># MAE</span></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>mae_test <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(test_residuals))</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a><span class="co"># RMSE</span></span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a>rmse_test <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(test_residuals<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Output</span></span>
<span id="cb55-19"><a href="#cb55-19" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Out-of-Sample Model Performance:</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Out-of-Sample Model Performance:</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"MAE  ="</span>, <span class="fu">round</span>(mae_test, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>MAE  = 0.1532 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"RMSE ="</span>, <span class="fu">round</span>(rmse_test, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>RMSE = 0.1833 </code></pre>
</div>
</div>
</section>
<section id="comparison-of-in-sample-and-out-of-sample-errors" class="level1">
<h1>Comparison of in-sample and out-of-sample Errors</h1>
<p>Here a new data frame is created to chart the difference between the in-sample, and out-of-sample error analyses.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare error data for comparison</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="co"># In-sample errors</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>in_sample_errors <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> eviction_model<span class="sc">$</span>residuals,</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_type =</span> <span class="st">"In-sample"</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Out-of-sample errors</span></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>out_sample_errors <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> test_residuals,</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_type =</span> <span class="st">"Out-of-sample"</span></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine</span></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>error_compare_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(in_sample_errors, out_sample_errors)</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(error_compare_df, <span class="fu">aes</span>(<span class="at">x =</span> residual, <span class="at">fill =</span> sample_type)) <span class="sc">+</span></span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span>,</span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">30</span>,</span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">"identity"</span></span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> sample_type, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Comparison of Prediction Errors"</span>,</span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"In-sample vs Out-of-sample Residual Distributions"</span>,</span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Prediction Error (Residual)"</span>,</span>
<span id="cb61-30"><a href="#cb61-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb61-31"><a href="#cb61-31" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb61-32"><a href="#cb61-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="eviction_data_analysis_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spdep)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>载入需要的程序包：spData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>To access larger datasets in this package, install the spDataLarge
package with: `install.packages('spDataLarge',
repos='https://nowosad.github.io/drat/', type='source')`</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare spatial neighbors from evictions_geo</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>nb <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(evictions_geo, <span class="at">queen =</span> <span class="cn">TRUE</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>lw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(nb, <span class="at">style =</span> <span class="st">"W"</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Get residuals from model</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>residuals_vec <span class="ot">&lt;-</span> eviction_model<span class="sc">$</span>residuals</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Add residuals to evictions_geo</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>evictions_geo<span class="sc">$</span>model_residual <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>evictions_geo<span class="sc">$</span>model_residual[<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(residuals_vec)] <span class="ot">&lt;-</span> residuals_vec</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Moran's I test with zero.policy = TRUE</span></span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>moran_result <span class="ot">&lt;-</span> <span class="fu">moran.test</span>(evictions_geo<span class="sc">$</span>model_residual, lw, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, <span class="at">na.action =</span> na.omit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in subset.nb(x = nb, subset = subset): subsetting caused increase in
subgraph count</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Moran's I Test on Model Residuals</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Moran's I Test on Model Residuals</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"===================================</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>===================================</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Moran's I statistic:"</span>, <span class="fu">round</span>(moran_result<span class="sc">$</span>statistic, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Moran's I statistic: -0.9178 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P-value:"</span>, <span class="fu">round</span>(moran_result<span class="sc">$</span>p.value, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>P-value: 0.8206 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Expected I (under null):"</span>, <span class="fu">round</span>(moran_result<span class="sc">$</span>estimate[<span class="dv">2</span>], <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Expected I (under null): -0.0476 </code></pre>
</div>
</div>
<section id="morans-i-test-results" class="level3">
<h3 class="anchored" data-anchor-id="morans-i-test-results">Moran’s I Test Results</h3>
<p>The Moran’s I test on model residuals yielded:</p>
<ul>
<li><strong>Moran’s I statistic</strong>: -0.9178</li>
<li><strong>P-value</strong>: 0.8206</li>
<li><strong>Expected I (under null hypothesis)</strong>: -0.0476</li>
</ul>
<p><strong>Interpretation</strong>: With a p-value of 0.8206 (&gt;&gt; 0.05), we <strong>fail to reject the null hypothesis of spatial independence</strong>. The residuals exhibit <strong>no significant spatial autocorrelation</strong> across Philadelphia census tracts. This indicates that prediction errors are randomly distributed geographically and do not show clustering patterns.</p>
<p><strong>Implication for OLS</strong>: This result supports the validity of OLS regression assumptions. Geographic factors not explicitly captured in the model (neighborhood effects, landlord networks, local housing market dynamics) are not systematically biasing predictions in spatially clustered ways. However, the negative Moran’s I value (-0.9178) slightly below the expected value suggests residuals may have a weak dispersal pattern, which warrants monitoring in future model refinements.</p>
</section>
</section>
<section id="bias-equity-considerations" class="level1">
<h1>Bias &amp; Equity Considerations</h1>
<section id="geographic-disparities-in-eviction-risk" class="level2">
<h2 class="anchored" data-anchor-id="geographic-disparities-in-eviction-risk">Geographic Disparities in Eviction Risk</h2>
<p>Eviction risk is unevenly distributed across Philadelphia, with the highest concentrations in historically Black neighborhoods facing long-term disinvestment, particularly North and West Philadelphia. A model that performs well citywide may still systematically mispredict in communities with atypical filing dynamics, landlord behavior, or underreported cases.</p>
</section>
</section>
<section id="implementation-recommendations" class="level1">
<h1>Implementation Recommendations</h1>
<section id="operationalizing-the-eviction-prediction-system" class="level2">
<h2 class="anchored" data-anchor-id="operationalizing-the-eviction-prediction-system">Operationalizing the Eviction Prediction System</h2>
<p>To translate this model into actionable policy, the City of Philadelphia could implement the following operational framework:</p>
</section>
<section id="monthly-forecast-dashboard" class="level2">
<h2 class="anchored" data-anchor-id="monthly-forecast-dashboard">Monthly Forecast Dashboard</h2>
<ul>
<li><strong>Automated updates</strong>: Model inputs (CPI, unemployment, filings) refresh automatically each month</li>
<li><strong>Forecast output</strong>: Display predicted eviction pressure for next month with confidence intervals</li>
<li><strong>Tract-level detail</strong>: Show which neighborhoods face elevated risk</li>
<li><strong>Stakeholder access</strong>: Share forecasts with Housing Authority, legal aid providers, and community organizations</li>
</ul>
</section>
<section id="targeted-eviction-prevention-strategy" class="level2">
<h2 class="anchored" data-anchor-id="targeted-eviction-prevention-strategy">Targeted Eviction Prevention Strategy</h2>
<p>When the model predicts elevated eviction pressure:</p>
<ol type="1">
<li><strong>Legal aid surge</strong>: Pre-position attorneys and paralegals in high-risk tracts</li>
<li><strong>Rental assistance outreach</strong>: Deploy ERA (Emergency Rental Assistance) and prevention funds to predicted hotspots</li>
<li><strong>Mediation services</strong>: Activate landlord-tenant negotiation programs</li>
<li><strong>Case management</strong>: Connect at-risk households to financial counseling and benefit enrollment</li>
</ol>
</section>
<section id="resource-allocation-timeline" class="level2">
<h2 class="anchored" data-anchor-id="resource-allocation-timeline">Resource Allocation Timeline</h2>
<ul>
<li><strong>Month 0</strong>: Model generates forecast for Month 1</li>
<li><strong>Weeks 1-2</strong>: City agencies receive and review predictions</li>
<li><strong>Weeks 3-4</strong>: Prevention resources (legal aid, mediation, ERA) deployed to predicted high-risk areas</li>
<li><strong>Month 1</strong>: Services available when filings anticipated to surge</li>
</ul>
</section>
<section id="safeguards-against-misuse" class="level2">
<h2 class="anchored" data-anchor-id="safeguards-against-misuse">Safeguards Against Misuse</h2>
<ol type="1">
<li><strong>Independent bias audits</strong>: Annual third-party review of prediction errors by neighborhood demographics</li>
<li><strong>Use restrictions</strong>: Model outputs explicitly prohibited from justifying policing, enforcement operations, or surveillance</li>
<li><strong>Community oversight board</strong>: Quarterly meetings with tenant advocates, legal aid, and neighborhood organizations</li>
<li><strong>Transparency reporting</strong>: Public dashboard of forecast accuracy, error rates by neighborhood, and resource allocation</li>
<li><strong>Sunset clause</strong>: Model contract includes review every 2 years with community input</li>
</ol>
<hr>
</section>
<section id="potential-harms-from-model-misspecification" class="level2">
<h2 class="anchored" data-anchor-id="potential-harms-from-model-misspecification">Potential Harms from Model Misspecification</h2>
<p><strong>Underprediction</strong> → Insufficient rental assistance allocated to high-risk neighborhoods, allowing preventable displacements</p>
<p><strong>Overprediction</strong> → Unnecessary targeting of resources that reinforces stigma, surveillance, or policing in vulnerable communities</p>
<p><strong>Macro-economic variables</strong> (unemployment, CPI) may reflect structural racism embedded in labor markets, potentially masking causal mechanisms</p>
<p><strong>Eviction filings themselves</strong> reflect unequal landlord-tenant power dynamics and enforcement variation across neighborhoods, not just tenant vulnerability</p>
</section>
<section id="safeguards-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="safeguards-recommendations">Safeguards &amp; Recommendations</h2>
<p>To mitigate these risks, implementation must include:</p>
<ol type="1">
<li><strong>Equity audits</strong>: Annual analysis of prediction errors by neighborhood race/income composition</li>
<li><strong>Community oversight</strong>: Advisory board with tenant advocates, legal aid providers, and community organizations</li>
<li><strong>Restricted use</strong>: Model outputs cannot be used to justify policing, enforcement, or surveillance</li>
<li><strong>Resource expansion</strong>: Forecasts must trigger <strong>expansion</strong> of prevention services, not rationing</li>
<li><strong>Transparency</strong>: Public reporting of model limitations and error rates by neighborhood</li>
</ol>
<hr>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>