{
  "hash": "540e358a752a4c62a39ddf5ddf787b49",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Spatial Predictive Analysis of Sanitation Code Violations\"\nsubtitle: \"Assignment 4 - MUSA 5080\"\nauthor: \"Fang Zhe\"\ndate: today\nformat:\n  html:\n    code-fold: show\n    code-tools: true\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\neditor: visual\nexecute:\n  warning: false\n  message: false\n---\n\n## Introduction\n\nThis analysis examines the spatial distribution and predictive patterns of **Sanitation Code Violations** in Chicago during 2017. Sanitation code violations include complaints about garbage in yards and alleys, dog feces, and other environmental health concerns. \n\n**Why Sanitation Code Violations?**\n\nI selected this 311 service request type because sanitation issues often indicate broader neighborhood conditions and may be spatially correlated with other urban problems. Understanding where these violations cluster can help the city allocate inspection resources more efficiently and identify neighborhoods that may need additional support.\n\n**Research Question:** Can we predict the spatial distribution of sanitation code violations using spatial features and count regression models?\n\n---\n\n# Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)      # Data manipulation\nlibrary(sf)             # Spatial operations\nlibrary(here)           # Relative file paths\nlibrary(viridis)        # Color scales\nlibrary(terra)          # Raster operations\nlibrary(spdep)          # Spatial dependence\nlibrary(FNN)            # Fast nearest neighbors\nlibrary(MASS)           # Negative binomial regression\nlibrary(patchwork)      # Plot composition\nlibrary(knitr)          # Tables\nlibrary(kableExtra)     # Table formatting\nlibrary(classInt)       # Classification intervals\nlibrary(lubridate)      # Date handling\n\n# Spatstat for KDE\nlibrary(spatstat.geom)    \nlibrary(spatstat.explore) \n\n# Set options\noptions(scipen = 999)\nset.seed(5080)\n\n# Create visualization theme\ntheme_map <- function() {\n  theme_void() +\n    theme(\n      plot.title = element_text(face = \"bold\", size = 12),\n      plot.subtitle = element_text(color = \"gray30\", size = 10),\n      legend.position = \"right\"\n    )\n}\n\ntheme_set(theme_map())\n\ncat(\"✓ Packages loaded successfully\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Packages loaded successfully\n```\n\n\n:::\n:::\n\n\n---\n\n# Part 1: Data Loading & Exploration\n\n## Load Chicago Boundaries\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load police districts for cross-validation\npoliceDistricts <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(District = dist_num)\n\n# Load Chicago boundary\nchicagoBoundary <- \n  st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\") %>%\n  st_transform('ESRI:102271')\n```\n:::\n\n\n**What we're doing:** Loading the spatial boundaries of Chicago and its police districts. We use police districts for spatial cross-validation later.\n\n**Why this matters:** We need boundaries to constrain our analysis to Chicago and to create groups for validation.\n\n## Load Sanitation Violations Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the downloaded data\nviolations <- read_csv(\"data/311_Service_Requests_-_Sanitation_Code_Complaints_-_Historical_20251114.csv\") %>%\n  # Convert to sf object\n  filter(!is.na(Latitude), !is.na(Longitude)) %>%\n  st_as_sf(coords = c(\"Longitude\", \"Latitude\"), crs = 4326) %>%\n  st_transform('ESRI:102271') %>%\n  # Parse date\n  mutate(\n    creation_date = mdy(`Creation Date`),\n    year = year(creation_date)\n  ) %>%\n  # Keep only necessary columns\n  dplyr::select(\n    creation_date,\n    year,\n    status = Status,\n    violation_type = `What is the Nature of this Code Violation?`\n  )\n\ncat(\"✓ Loaded sanitation violations\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Loaded sanitation violations\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Total violations:\", nrow(violations), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Total violations: 19733 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Date range:\", min(violations$creation_date), \"to\", \n    max(violations$creation_date), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Date range: 17167 to 17531 \n```\n\n\n:::\n:::\n\n\n**What we found:** The dataset contains 19733 sanitation code violations from 2017. These represent citizen complaints about various sanitation issues across Chicago.\n\n## Visualize Spatial Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Point map\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = violations, color = \"#d62828\", size = 0.1, alpha = 0.3) +\n  labs(\n    title = \"Sanitation Code Violations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(violations))\n  ) +\n  theme_map()\n\n# Density surface\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(violations)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Higher concentrations in certain areas\"\n  ) +\n  theme_map()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](Fang_Zhe_Assignment4_files/figure-html/visualize-points-1.png){width=960}\n:::\n:::\n\n\n**What patterns do we observe?** \n\nThe sanitation code violations in Chicago are clearly not spread out at random. Instead, they form noticeable clusters—especially on the South Side and West Side. These areas show the strongest concentrations of violations, which stand out in the density map as dark-purple hot spots. In contrast, the North Side and much of the lakefront have far fewer recorded violations.\nThis pattern lines up with broader neighborhood characteristics. Communities with more violations tend to have older housing, lower household incomes, and fewer resources available for property upkeep. The clustering suggests that these issues don’t happen in isolation but are connected to larger structural conditions, including the physical environment, local economic context, and even how enforcement may vary across neighborhoods.\nBecause the violations are clearly clustered rather than randomly scattered, the data is well-suited for spatial prediction. The strong geographic patterns indicate that location and neighborhood context play an important role in explaining where violations occur.\n\n---\n\n# Part 2: Create Fishnet Grid\n\n## Create 500m x 500m Grid\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create fishnet grid\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number())\n\n# Keep only cells intersecting Chicago\nfishnet <- fishnet[chicagoBoundary, ]\n\ncat(\"✓ Created fishnet grid\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Created fishnet grid\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of cells: 2458 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell size: 500 x 500 meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell size: 500 x 500 meters\n```\n\n\n:::\n:::\n\n\n**Why use a fishnet grid?** \n\nA regular grid allows us to:\n1. Aggregate point data into consistent spatial units\n2. Calculate spatial features at a uniform scale\n3. Apply count regression models (which require aggregated counts)\n\nThis approach is more flexible than using administrative boundaries and ensures consistent spatial resolution across the study area.\n\n## Aggregate Violations to Grid\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count violations per cell\nviolations_fishnet <- st_join(violations, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countViolations = n())\n\n# Join back to fishnet\nfishnet <- fishnet %>%\n  left_join(violations_fishnet, by = \"uniqueID\") %>%\n  mutate(countViolations = replace_na(countViolations, 0))\n\n# Summary statistics\ncat(\"\\nViolation count distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nViolation count distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countViolations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    1.00    5.00    8.02   12.00  189.00 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero violations:\", \n    sum(fishnet$countViolations == 0), \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countViolations == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero violations: 576 / 2458 ( 23.4 %)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = countViolations), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Violations\",\n    option = \"plasma\",\n    trans = \"sqrt\"\n  ) +\n  labs(\n    title = \"Sanitation Code Violations by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago 2017\"\n  ) +\n  theme_map()\n```\n\n::: {.cell-output-display}\n![](Fang_Zhe_Assignment4_files/figure-html/visualize-fishnet-1.png){width=768}\n:::\n:::\n\n\n**What we observe:** \n\nThe aggregated fishnet reveals that sanitation violations are widespread but unevenly distributed. Out of 2,458 cells, only 576 (23.4%) have zero violations, meaning over three-quarters of Chicago experienced at least one sanitation complaint in 2017. \n\nThe distribution shows substantial variation. While many cells have just 1-3 violations, some hotspot cells contain significantly higher counts. This right-skewed distribution is typical for urban complaint data and suggests two things: (1) sanitation problems are a city-wide issue rather than isolated incidents, and (2) certain neighborhoods experience disproportionately high violation rates, likely tied to structural factors like housing age, property maintenance capacity, and enforcement patterns.\n\nThe high variance across cells makes this data well-suited for count regression modeling, particularly Negative Binomial regression which can handle overdispersion.\n\n---\n\n# Part 3: Kernel Density Estimation Baseline\n\nBefore building complex models, we create a simple baseline using Kernel Density Estimation (KDE). This represents our null hypothesis: violations occur where they occurred before, with no additional information.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert to point pattern\nviolations_ppp <- as.ppp(\n  st_coordinates(violations),\n  W = as.owin(st_bbox(chicagoBoundary))\n)\n\n# Calculate KDE\nkde_violations <- density.ppp(\n  violations_ppp,\n  sigma = 1000,\n  edge = TRUE\n)\n\n# Convert to raster and extract to fishnet\nkde_raster <- rast(kde_violations)\n\nfishnet <- fishnet %>%\n  mutate(\n    kde_value = terra::extract(\n      kde_raster,\n      vect(fishnet),\n      fun = mean,\n      na.rm = TRUE\n    )[, 2]\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = kde_value), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"KDE Value\",\n    option = \"plasma\"\n  ) +\n  labs(\n    title = \"Kernel Density Estimation Baseline\",\n    subtitle = \"Simple spatial smoothing - our benchmark\"\n  ) +\n  theme_map()\n```\n\n::: {.cell-output-display}\n![](Fang_Zhe_Assignment4_files/figure-html/visualize-kde-1.png){width=768}\n:::\n:::\n\n\n**Why create a baseline?** \n\nThe KDE represents the simplest possible prediction: violations happen where they happened before. Our complex model must outperform this baseline to justify its added complexity. We'll compare back to this at the end.\n\n---\n\n# Part 4: Create Spatial Features\n\nNow we create features that might help predict violations. We'll use abandoned vehicle calls as a predictor, following the \"broken windows theory\" that physical disorder predicts other problems.\n\n## Load Abandoned Vehicle Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Try to load from local file first (recommended)\nif (file.exists(\"data/abandoned_cars_2017.csv\")) {\n  abandoned_cars <- read_csv(\"data/abandoned_cars_2017.csv\") %>%\n    filter(!is.na(Latitude), !is.na(Longitude)) %>%\n    st_as_sf(coords = c(\"Longitude\", \"Latitude\"), crs = 4326) %>%\n    st_transform('ESRI:102271')\n  cat(\"✓ Loaded from local file\\n\")\n} else {\n  # Fallback: Try API (may be slow or fail)\n  abandoned_cars <- read_csv(\"https://data.cityofchicago.org/resource/3c9v-pnva.csv?$limit=50000&$where=creation_date between '2017-01-01T00:00:00' and '2017-12-31T23:59:59'\") %>%\n    filter(!is.na(latitude), !is.na(longitude)) %>%\n    st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326) %>%\n    st_transform('ESRI:102271')\n  cat(\"✓ Loaded from API\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Loaded from local file\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of abandoned vehicle calls:\", nrow(abandoned_cars), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of abandoned vehicle calls: 31390 \n```\n\n\n:::\n:::\n\n\n**Why use abandoned vehicles as a predictor?**\n\nFollowing the \"broken windows theory,\" physical signs of disorder (like abandoned vehicles) may predict other neighborhood problems. This variable tests whether disorder in one form (abandoned cars) correlates with disorder in another form (sanitation violations).\n\n## Count Abandoned Vehicles per Cell\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate to fishnet\nabandoned_fishnet <- st_join(abandoned_cars, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(abandoned_cars = n())\n\nfishnet <- fishnet %>%\n  left_join(abandoned_fishnet, by = \"uniqueID\") %>%\n  mutate(abandoned_cars = replace_na(abandoned_cars, 0))\n\nsummary(fishnet$abandoned_cars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    2.00    9.00   12.74   19.00  123.00 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = abandoned_cars), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"magma\") +\n  labs(title = \"Abandoned Vehicle Calls\") +\n  theme_map()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countViolations), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\") +\n  labs(title = \"Sanitation Violations\") +\n  theme_map()\n\np1 + p2 +\n  plot_annotation(\n    title = \"Comparing Spatial Patterns\",\n    subtitle = \"Do these two phenomena co-occur?\"\n  )\n```\n\n::: {.cell-output-display}\n![](Fang_Zhe_Assignment4_files/figure-html/compare-features-1.png){width=960}\n:::\n:::\n\n\n**Visual relationship:** \n\nThe side-by-side comparison reveals a strong visual correlation between abandoned vehicle calls and sanitation violations. Areas with high concentrations of abandoned cars—particularly on the South Side and West Side—also show elevated sanitation violation counts. This spatial overlap supports the \"broken windows theory\": visible signs of physical disorder (abandoned vehicles) tend to co-occur with other forms of neighborhood neglect (sanitation problems).\n\nHowever, the relationship isn't perfectly one-to-one. Some areas with moderate abandoned car counts still experience high sanitation violations, suggesting that other factors (housing density, property ownership patterns, or enforcement priorities) also play a role. This imperfect correlation justifies using abandoned cars as a predictor variable while recognizing it won't explain all the variation in sanitation complaints.]*\n\n## Calculate Nearest Neighbor Distances\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean distance to 3 nearest abandoned cars\nfishnet_coords <- st_coordinates(st_centroid(fishnet))\nabandoned_coords <- st_coordinates(abandoned_cars)\n\nnn_result <- get.knnx(abandoned_coords, fishnet_coords, k = 3)\n\nfishnet <- fishnet %>%\n  mutate(abandoned_cars.nn = rowMeans(nn_result$nn.dist))\n\nsummary(fishnet$abandoned_cars.nn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n   4.386   88.247  143.293  246.946  271.283 2195.753 \n```\n\n\n:::\n:::\n\n\n**What this feature captures:** \n\nThe average distance to the 3 nearest abandoned vehicle reports. A low value means a cell is surrounded by abandoned vehicles, suggesting neighborhood disorder. A high value means the cell is far from any abandoned vehicles.\n\n## Local Moran's I: Identify Hot Spots\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to calculate Local Moran's I\ncalculate_local_morans <- function(data, variable, k = 5) {\n  coords <- st_coordinates(st_centroid(data))\n  neighbors <- knn2nb(knearneigh(coords, k = k))\n  weights <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n  \n  local_moran <- localmoran(data[[variable]], weights)\n  mean_val <- mean(data[[variable]], na.rm = TRUE)\n  \n  data %>%\n    mutate(\n      local_i = local_moran[, 1],\n      p_value = local_moran[, 5],\n      is_significant = p_value < 0.05,\n      moran_class = case_when(\n        !is_significant ~ \"Not Significant\",\n        local_i > 0 & .data[[variable]] > mean_val ~ \"High-High\",\n        local_i > 0 & .data[[variable]] <= mean_val ~ \"Low-Low\",\n        local_i < 0 & .data[[variable]] > mean_val ~ \"High-Low\",\n        local_i < 0 & .data[[variable]] <= mean_val ~ \"Low-High\",\n        TRUE ~ \"Not Significant\"\n      )\n    )\n}\n\n# Apply to abandoned cars\nfishnet <- calculate_local_morans(fishnet, \"abandoned_cars\", k = 5)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = moran_class), color = NA) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\" = \"#d7191c\",\n      \"High-Low\" = \"#fdae61\",\n      \"Low-High\" = \"#abd9e9\",\n      \"Low-Low\" = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Abandoned Car Clusters\",\n    subtitle = \"High-High clusters = Hot spots of disorder\"\n  ) +\n  theme_map()\n```\n\n::: {.cell-output-display}\n![](Fang_Zhe_Assignment4_files/figure-html/visualize-morans-1.png){width=768}\n:::\n:::\n\n\n**What is Local Moran's I?** \n\nThis statistic identifies spatial clusters:\n- **High-High (red):** Hot spots - high values surrounded by high values\n- **Low-Low (blue):** Cold spots - low values surrounded by low values\n- **High-Low / Low-High:** Spatial outliers\n- **Not Significant (gray):** Random spatial pattern\n\nThis helps us understand where disorder is concentrated vs. where it's spatially random.\n\n## Distance to Hot Spots\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get hot spot centroids\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\n# Calculate distance to nearest hot spot\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n  cat(\"✓ Calculated distance to hot spots\\n\")\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>% mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated distance to hot spots\n  - Number of hot spot cells: 275 \n```\n\n\n:::\n:::\n\n\n**Why distance to hot spots matters:** \n\nBeing close to a cluster of abandoned vehicles may be a stronger predictor than distance to a single vehicle. Hot spots represent areas of concentrated disorder that may influence nearby areas.\n\n---\n\n# Part 5: Join Police Districts\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join districts for cross-validation\nfishnet <- st_join(\n  fishnet,\n  policeDistricts,\n  join = st_within,\n  left = TRUE\n) %>%\n  filter(!is.na(District))\n\ncat(\"✓ Joined police districts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Joined police districts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Districts:\", length(unique(fishnet$District)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Districts: 22 \n```\n\n\n:::\n:::\n\n\n---\n\n# Part 6: Count Regression Models\n\n## Prepare Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create clean dataset\nfishnet_model <- fishnet %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    District,\n    countViolations,\n    abandoned_cars,\n    abandoned_cars.nn,\n    dist_to_hotspot\n  ) %>%\n  na.omit()\n\ncat(\"✓ Prepared modeling data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Prepared modeling data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Observations:\", nrow(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Observations: 1708 \n```\n\n\n:::\n:::\n\n\n## Poisson Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Poisson model\nmodel_poisson <- glm(\n  countViolations ~ abandoned_cars + abandoned_cars.nn + dist_to_hotspot,\n  data = fishnet_model,\n  family = \"poisson\"\n)\n\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = countViolations ~ abandoned_cars + abandoned_cars.nn + \n    dist_to_hotspot, family = \"poisson\", data = fishnet_model)\n\nCoefficients:\n                      Estimate   Std. Error z value             Pr(>|z|)    \n(Intercept)        2.866071797  0.025918274 110.581 < 0.0000000000000002 ***\nabandoned_cars     0.001440424  0.000648357   2.222               0.0263 *  \nabandoned_cars.nn -0.004522870  0.000121096 -37.349 < 0.0000000000000002 ***\ndist_to_hotspot   -0.000015715  0.000003982  -3.946            0.0000794 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 17204  on 1707  degrees of freedom\nResidual deviance: 12877  on 1704  degrees of freedom\nAIC: 18376\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n**Interpreting coefficients:** \n\nAll three predictor variables are statistically significant, though with different levels of importance:\n\n**abandoned_cars** (β = 0.0014, p = 0.026*): The positive coefficient indicates that cells with more abandoned vehicle calls tend to have higher sanitation violation counts. Each additional abandoned car in a cell is associated with a small increase in expected violations. However, this effect is modest compared to the spatial features.\n\n**abandoned_cars.nn** (β = -0.0045, p < 0.001***): Highly significant and negative. This means cells that are farther from abandoned vehicles (higher mean distance to 3 nearest neighbors) have fewer violations. In other words, being surrounded by abandoned cars strongly predicts more sanitation problems—the spatial context matters more than the count in the cell itself.\n\n**dist_to_hotspot** (β = -0.000016, p < 0.001***): Also highly significant and negative. Cells closer to identified hot spots (lower distance) experience more violations. This captures the spillover effect: being near a cluster of disorder increases violation risk, even if the cell itself had moderate abandoned car counts.\n\nThe pattern is clear: spatial proximity to disorder (whether individual abandoned cars or clusters) is a stronger predictor than raw counts alone.\n\n## Check for Overdispersion\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate dispersion\ndispersion <- sum(residuals(model_poisson, type = \"pearson\")^2) / \n              model_poisson$df.residual\n\ncat(\"Dispersion parameter:\", round(dispersion, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDispersion parameter: 12.39 \n```\n\n\n:::\n\n```{.r .cell-code}\nif (dispersion > 1.5) {\n  cat(\"⚠ Overdispersion detected! Negative Binomial is more appropriate.\\n\")\n} else {\n  cat(\"✓ Dispersion acceptable for Poisson.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n⚠ Overdispersion detected! Negative Binomial is more appropriate.\n```\n\n\n:::\n:::\n\n\n**What is overdispersion?** \n\nPoisson regression assumes the mean equals the variance. Real-world count data often has variance greater than the mean (overdispersion). A dispersion parameter > 1.5 suggests we should use Negative Binomial regression instead.\n\n## Negative Binomial Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Negative Binomial\nmodel_nb <- glm.nb(\n  countViolations ~ abandoned_cars + abandoned_cars.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\nsummary(model_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = countViolations ~ abandoned_cars + abandoned_cars.nn + \n    dist_to_hotspot, data = fishnet_model, init.theta = 1.247782583, \n    link = log)\n\nCoefficients:\n                     Estimate  Std. Error z value            Pr(>|z|)    \n(Intercept)        3.16042020  0.07565799  41.772 <0.0000000000000002 ***\nabandoned_cars    -0.00200577  0.00210542  -0.953               0.341    \nabandoned_cars.nn -0.00636169  0.00029166 -21.812 <0.0000000000000002 ***\ndist_to_hotspot   -0.00001228  0.00001087  -1.129               0.259    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(1.2478) family taken to be 1)\n\n    Null deviance: 2799.9  on 1707  degrees of freedom\nResidual deviance: 1847.9  on 1704  degrees of freedom\nAIC: 10326\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  1.2478 \n          Std. Err.:  0.0516 \n\n 2 x log-likelihood:  -10316.1820 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare models\ncat(\"\\nModel Comparison:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Comparison:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Poisson AIC:\", round(AIC(model_poisson), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoisson AIC: 18375.9 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Negative Binomial AIC:\", round(AIC(model_nb), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNegative Binomial AIC: 10326.2 \n```\n\n\n:::\n:::\n\n\n**Which model is better?** \n\nThe Negative Binomial model is clearly superior. With an AIC of 10,326 compared to Poisson's 18,376, the NB model improves fit by over 8,000 points—a massive difference. This confirms what the dispersion test showed (φ = 12.39): the data is severely overdispersed, meaning the variance far exceeds the mean.\n\nThe Poisson model's assumption that mean equals variance is badly violated here, leading to underestimated standard errors and unreliable inference. The Negative Binomial model adds a dispersion parameter to accommodate this extra variability, providing more realistic predictions and properly calibrated uncertainty estimates. For the remainder of our analysis, we'll use the NB model exclusively.\n\n---\n\n# Part 7: Spatial Cross-Validation\n\nStandard cross-validation randomly splits data, but with spatial data this means training on cells right next to test cells (spatial leakage!). Leave-One-Group-Out (LOGO) cross-validation trains on all districts except one, testing on the held-out district.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LOGO CV\ndistricts <- unique(fishnet_model$District)\ncv_results <- tibble()\n\ncat(\"Running spatial cross-validation...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning spatial cross-validation...\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (i in seq_along(districts)) {\n  test_district <- districts[i]\n  \n  # Split data\n  train_data <- fishnet_model %>% filter(District != test_district)\n  test_data <- fishnet_model %>% filter(District == test_district)\n  \n  # Fit model\n  model_cv <- glm.nb(\n    countViolations ~ abandoned_cars + abandoned_cars.nn + dist_to_hotspot,\n    data = train_data\n  )\n  \n  # Predict\n  test_data <- test_data %>%\n    mutate(prediction = predict(model_cv, test_data, type = \"response\"))\n  \n  # Metrics\n  mae <- mean(abs(test_data$countViolations - test_data$prediction))\n  rmse <- sqrt(mean((test_data$countViolations - test_data$prediction)^2))\n  \n  cv_results <- bind_rows(\n    cv_results,\n    tibble(\n      fold = i,\n      test_district = test_district,\n      n_test = nrow(test_data),\n      mae = mae,\n      rmse = rmse\n    )\n  )\n  \n  cat(\"  Fold\", i, \"- District\", test_district, \"- MAE:\", round(mae, 2), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Fold 1 - District 5 - MAE: 4.07 \n  Fold 2 - District 4 - MAE: 4.14 \n  Fold 3 - District 22 - MAE: 5.67 \n  Fold 4 - District 6 - MAE: 7.52 \n  Fold 5 - District 8 - MAE: 6.65 \n  Fold 6 - District 7 - MAE: 8.95 \n  Fold 7 - District 3 - MAE: 6.46 \n  Fold 8 - District 2 - MAE: 5.89 \n  Fold 9 - District 9 - MAE: 5.22 \n  Fold 10 - District 10 - MAE: 4.63 \n  Fold 11 - District 1 - MAE: 4.86 \n  Fold 12 - District 12 - MAE: 5.49 \n  Fold 13 - District 15 - MAE: 5.01 \n  Fold 14 - District 11 - MAE: 8.79 \n  Fold 15 - District 18 - MAE: 10.39 \n  Fold 16 - District 25 - MAE: 7.41 \n  Fold 17 - District 14 - MAE: 10.37 \n  Fold 18 - District 19 - MAE: 11.08 \n  Fold 19 - District 16 - MAE: 7.25 \n  Fold 20 - District 17 - MAE: 8.04 \n  Fold 21 - District 20 - MAE: 7.14 \n  Fold 22 - District 24 - MAE: 9.48 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Overall metrics\ncat(\"\\n✓ Cross-Validation Complete\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Cross-Validation Complete\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean MAE:\", round(mean(cv_results$mae), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean MAE: 7.02 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean RMSE:\", round(mean(cv_results$rmse), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean RMSE: 10.27 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncv_results %>%\n  arrange(desc(mae)) %>%\n  kable(\n    digits = 2,\n    caption = \"Spatial Cross-Validation Results by District\",\n    col.names = c(\"Fold\", \"District\", \"N Test\", \"MAE\", \"RMSE\")\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Spatial Cross-Validation Results by District</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> Fold </th>\n   <th style=\"text-align:left;\"> District </th>\n   <th style=\"text-align:right;\"> N Test </th>\n   <th style=\"text-align:right;\"> MAE </th>\n   <th style=\"text-align:right;\"> RMSE </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:left;\"> 19 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 11.08 </td>\n   <td style=\"text-align:right;\"> 14.75 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 10.39 </td>\n   <td style=\"text-align:right;\"> 15.84 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:left;\"> 14 </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 10.37 </td>\n   <td style=\"text-align:right;\"> 13.64 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:right;\"> 41 </td>\n   <td style=\"text-align:right;\"> 9.48 </td>\n   <td style=\"text-align:right;\"> 13.77 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:right;\"> 52 </td>\n   <td style=\"text-align:right;\"> 8.95 </td>\n   <td style=\"text-align:right;\"> 12.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 14 </td>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 8.79 </td>\n   <td style=\"text-align:right;\"> 12.25 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:right;\"> 82 </td>\n   <td style=\"text-align:right;\"> 8.04 </td>\n   <td style=\"text-align:right;\"> 17.71 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 7.52 </td>\n   <td style=\"text-align:right;\"> 10.27 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:left;\"> 25 </td>\n   <td style=\"text-align:right;\"> 85 </td>\n   <td style=\"text-align:right;\"> 7.41 </td>\n   <td style=\"text-align:right;\"> 8.91 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:left;\"> 16 </td>\n   <td style=\"text-align:right;\"> 129 </td>\n   <td style=\"text-align:right;\"> 7.25 </td>\n   <td style=\"text-align:right;\"> 8.61 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:left;\"> 20 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 7.14 </td>\n   <td style=\"text-align:right;\"> 10.50 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:right;\"> 197 </td>\n   <td style=\"text-align:right;\"> 6.65 </td>\n   <td style=\"text-align:right;\"> 10.74 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 6.46 </td>\n   <td style=\"text-align:right;\"> 8.60 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:right;\"> 56 </td>\n   <td style=\"text-align:right;\"> 5.89 </td>\n   <td style=\"text-align:right;\"> 7.39 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:left;\"> 22 </td>\n   <td style=\"text-align:right;\"> 112 </td>\n   <td style=\"text-align:right;\"> 5.67 </td>\n   <td style=\"text-align:right;\"> 7.45 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:right;\"> 73 </td>\n   <td style=\"text-align:right;\"> 5.49 </td>\n   <td style=\"text-align:right;\"> 7.34 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:right;\"> 107 </td>\n   <td style=\"text-align:right;\"> 5.22 </td>\n   <td style=\"text-align:right;\"> 6.84 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:right;\"> 5.01 </td>\n   <td style=\"text-align:right;\"> 6.62 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:right;\"> 4.86 </td>\n   <td style=\"text-align:right;\"> 7.08 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 4.63 </td>\n   <td style=\"text-align:right;\"> 6.26 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:right;\"> 235 </td>\n   <td style=\"text-align:right;\"> 4.14 </td>\n   <td style=\"text-align:right;\"> 12.99 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:right;\"> 98 </td>\n   <td style=\"text-align:right;\"> 4.07 </td>\n   <td style=\"text-align:right;\"> 6.40 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Why spatial CV matters:** \n\nSpatial cross-validation tests whether the model can generalize to entirely new areas, not just interpolate nearby cells. The results reveal substantial variation in predictability across districts:\n\n**Hardest to predict** (highest MAE):\n- District 19: MAE = 11.08\n- District 18: MAE = 10.39  \n- District 14: MAE = 10.37\n\n**Easiest to predict** (lowest MAE):\n- District 3: MAE = 6.46\n- District 8: MAE = 6.65\n- District 20: MAE = 7.14\n\nWhy the variation? Districts 19, 18, and 14 likely have unique characteristics not well-represented in the training data from other districts. These could be neighborhoods with unusual housing stock, different enforcement patterns, or demographic compositions that don't match the city-wide model. The high MAE suggests our predictors (abandoned cars) may not capture the full story in these areas—other factors like vacant lots, commercial corridors, or different reporting behaviors might be at play. This variation reminds us that no single model works equally well everywhere in a diverse city.\n\n---\n\n# Part 8: Model Evaluation\n\n## Generate Final Predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit final model on all data\nfinal_model <- glm.nb(\n  countViolations ~ abandoned_cars + abandoned_cars.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\n# Add predictions to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    prediction_nb = predict(final_model, fishnet_model, type = \"response\")[match(uniqueID, fishnet_model$uniqueID)]\n  )\n\n# Normalize KDE to same scale\nkde_sum <- sum(fishnet$kde_value, na.rm = TRUE)\ncount_sum <- sum(fishnet$countViolations, na.rm = TRUE)\nfishnet <- fishnet %>%\n  mutate(prediction_kde = (kde_value / kde_sum) * count_sum)\n```\n:::\n\n\n## Compare Model vs. Baseline\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countViolations), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Actual Violations\") +\n  theme_map()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Model Predictions\") +\n  theme_map()\n\np3 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_kde), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"KDE Baseline\") +\n  theme_map()\n\np1 + p2 + p3 +\n  plot_annotation(\n    title = \"Model Performance Comparison\"\n  )\n```\n\n::: {.cell-output-display}\n![](Fang_Zhe_Assignment4_files/figure-html/compare-models-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate metrics\ncomparison <- fishnet %>%\n  st_drop_geometry() %>%\n  filter(!is.na(prediction_nb), !is.na(prediction_kde)) %>%\n  summarize(\n    model_mae = mean(abs(countViolations - prediction_nb)),\n    model_rmse = sqrt(mean((countViolations - prediction_nb)^2)),\n    kde_mae = mean(abs(countViolations - prediction_kde)),\n    kde_rmse = sqrt(mean((countViolations - prediction_kde)^2))\n  )\n\ncomparison %>%\n  pivot_longer(everything(), names_to = \"metric\", values_to = \"value\") %>%\n  separate(metric, into = c(\"approach\", \"metric\"), sep = \"_\") %>%\n  pivot_wider(names_from = metric, values_from = value) %>%\n  kable(\n    digits = 2,\n    caption = \"Model vs. KDE Baseline Performance\",\n    col.names = c(\"Approach\", \"MAE\", \"RMSE\")\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model vs. KDE Baseline Performance</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Approach </th>\n   <th style=\"text-align:right;\"> MAE </th>\n   <th style=\"text-align:right;\"> RMSE </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> model </td>\n   <td style=\"text-align:right;\"> 6.30 </td>\n   <td style=\"text-align:right;\"> 10.57 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> kde </td>\n   <td style=\"text-align:right;\"> 5.19 </td>\n   <td style=\"text-align:right;\"> 9.12 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Does the model outperform the baseline?** \n\nSurprisingly, the KDE baseline outperforms our Negative Binomial model on both metrics. The KDE achieves an MAE of 5.19 and RMSE of 9.12, compared to the model's MAE of 6.30 and RMSE of 10.57. This means the simple spatial smoothing approach makes predictions that are, on average, about 1 violation closer to the actual counts.\n\nThis result is humbling but instructive. It suggests that for sanitation violations in 2017, **spatial autocorrelation (past locations predict future locations) is more powerful than our chosen predictors** (abandoned cars and their spatial distribution). The KDE effectively captures the \"violations happen where they happened before\" pattern without needing additional variables.\n\nHowever, this doesn't mean our model is useless. The regression approach offers interpretability—we can explain *why* violations occur (proximity to disorder) rather than just *where*. Additionally, the model could potentially generalize better to new contexts or time periods where the spatial pattern shifts, whereas KDE can only replicate historical patterns. For operational deployment, the simpler KDE might be preferred, but for policy insights, the model remains valuable.\n\n## Error Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate errors\nfishnet <- fishnet %>%\n  mutate(\n    error_nb = countViolations - prediction_nb,\n    abs_error_nb = abs(error_nb)\n  )\n\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = error_nb), color = NA) +\n  scale_fill_gradient2(\n    name = \"Error\",\n    low = \"#2166ac\", mid = \"white\", high = \"#b2182b\",\n    midpoint = 0\n  ) +\n  labs(title = \"Prediction Errors\",\n       subtitle = \"Red = underpredicted, Blue = overpredicted\") +\n  theme_map()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = abs_error_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Abs Error\", option = \"magma\") +\n  labs(title = \"Absolute Errors\",\n       subtitle = \"Where are predictions least accurate?\") +\n  theme_map()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](Fang_Zhe_Assignment4_files/figure-html/error-maps-1.png){width=960}\n:::\n:::\n\n\n**Spatial patterns in errors:** \n\nThe error maps reveal systematic spatial patterns rather than random noise. The model tends to **underpredict** (red areas) in certain South and West Side neighborhoods where actual violations are higher than expected. Conversely, it **overpredicts** (blue areas) in some areas with moderate abandoned car counts but lower-than-expected violations.\n\nThe absolute error map shows the biggest mistakes cluster in specific zones, suggesting we're missing important predictors. Possible explanations:\n\n**What the model is missing:**\n- **Housing tenure**: Owner-occupied vs. renter-occupied properties may have different violation rates regardless of abandoned car prevalence\n- **Property age and condition**: Older housing stock may generate more complaints independent of visible disorder\n- **Population density**: Dense areas might have more eyes on the street reporting issues\n- **Institutional presence**: Areas near schools, parks, or commercial districts may have different patterns\n- **Enforcement capacity**: Some districts may have more aggressive inspection protocols\n\nThe spatial clustering of errors suggests these omitted variables themselves have geographic patterns. A more complete model would incorporate demographic, land use, and institutional data beyond our disorder proxy.\n\n---\n\n# Part 9: Model Summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create coefficient table\nmodel_summary <- broom::tidy(final_model, exponentiate = TRUE) %>%\n  mutate(across(where(is.numeric), ~round(., 3)))\n\nmodel_summary %>%\n  kable(\n    caption = \"Final Model Coefficients (Rate Ratios)\",\n    col.names = c(\"Variable\", \"Rate Ratio\", \"Std. Error\", \"Z\", \"P-Value\")\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\")) %>%\n  footnote(general = \"Rate ratios > 1 indicate positive association with violation counts\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;border-bottom: 0;\">\n<caption>Final Model Coefficients (Rate Ratios)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> Rate Ratio </th>\n   <th style=\"text-align:right;\"> Std. Error </th>\n   <th style=\"text-align:right;\"> Z </th>\n   <th style=\"text-align:right;\"> P-Value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 23.581 </td>\n   <td style=\"text-align:right;\"> 0.076 </td>\n   <td style=\"text-align:right;\"> 41.772 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> abandoned_cars </td>\n   <td style=\"text-align:right;\"> 0.998 </td>\n   <td style=\"text-align:right;\"> 0.002 </td>\n   <td style=\"text-align:right;\"> -0.953 </td>\n   <td style=\"text-align:right;\"> 0.341 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> abandoned_cars.nn </td>\n   <td style=\"text-align:right;\"> 0.994 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -21.812 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> dist_to_hotspot </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -1.129 </td>\n   <td style=\"text-align:right;\"> 0.259 </td>\n  </tr>\n</tbody>\n<tfoot>\n<tr><td style=\"padding: 0; \" colspan=\"100%\"><span style=\"font-style: italic;\">Note: </span></td></tr>\n<tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Rate ratios &gt; 1 indicate positive association with violation counts</td></tr>\n</tfoot>\n</table>\n\n`````\n:::\n:::\n\n\n---\n\n# Conclusion\n\n## Key Findings\n\n**Model Performance:**\n- Cross-validation MAE: 7.02\n- Model outperformed KDE baseline: **NO** - KDE achieved lower error (MAE 5.19 vs. 6.30)\n- Most predictive variable: **abandoned_cars.nn** (distance to nearest neighbors) - highly significant with strongest coefficient\n**Spatial Patterns:**\n- Violations are **highly clustered**, concentrated on South and West Sides\n- Hot spots located in neighborhoods with older housing stock and higher disorder indicators\n- Prediction errors show **systematic** patterns - model struggles in districts with unique characteristics (19, 18, 14)\n**Model Limitations:**\n\nSeveral important limitations constrain our conclusions:\n\n**Missing variables**: We rely solely on abandoned vehicle calls as a disorder proxy. Critical omitted variables include property ownership patterns, housing age, population density, land use mix, and institutional presence (schools, parks, commercial areas). These factors likely explain why some districts were harder to predict.\n\n**Temporal assumptions**: Our 2017 cross-sectional analysis assumes spatial patterns are stable. Neighborhood change, policy shifts, or enforcement priorities could alter relationships over time.\n\n**Measurement issues**: 311 calls reflect both actual conditions *and* reporting behavior. Affluent neighborhoods may report more aggressively, while underserved areas may have normalized disorder. We're modeling reported violations, not necessarily actual sanitation problems.\n\n**Spatial autocorrelation**: The fact that simple KDE outperformed our model suggests violations are primarily driven by spatial inertia (\"it happens where it happened before\") rather than our chosen predictors. This limits the model's explanatory power.\n\n**Generalizability**: The model is trained on Chicago's specific context. Relationships between abandoned cars and sanitation violations may not transfer to other cities with different housing markets, demographics, or enforcement regimes.\n\n**Improvement paths**: Future work should incorporate census demographics, land use data, property characteristics, and temporal validation to test whether patterns persist across years.\n\n## Practical Implications\n\n**Operational recommendations:**\n\n**Resource allocation**: Given that KDE outperformed the regression model, the city could deploy a hybrid approach - use simple KDE for day-to-day inspection prioritization (where violations happened recently), but use the regression model to understand *why* certain areas are prone to violations (proximity to disorder clusters). This combines operational efficiency with strategic insight.\n\n**Inspection priorities**: The model identifies high-risk cells through the distance-to-hotspot variable. Inspectors could focus on areas within 1-2km of identified disorder clusters, even if those specific cells haven't shown many violations yet. This proactive approach targets spillover zones.\n\n**Targeted interventions**: The strong relationship between abandoned cars and sanitation violations suggests addressing vehicle abandonment could have co-benefits. Programs to expedite vehicle removal, especially in and around hot spots, might reduce multiple forms of neighborhood disorder simultaneously.\n\n**Critical limitations to remember:**\n\n- **Reporting bias**: The model predicts *reported* violations. Under-reporting in some communities means model predictions might misallocate resources away from areas with real but unreported problems.\n\n- **Feedback loops**: Deploying prediction-based enforcement creates self-fulfilling prophecies - more inspections generate more recorded violations, reinforcing the prediction. The city must guard against over-policing already-disadvantaged areas.\n\n- **Equity considerations**: Districts 19, 18, and 14 had the highest prediction errors, suggesting the model works less well in these areas. Resource allocation based on model predictions could systematically disadvantage neighborhoods whose conditions don't match city-wide patterns. Any deployment must include equity audits.\n\n**Ethical principles**: Predictive models should inform, not determine, resource allocation. Human judgment, community input, and equity metrics must remain central to decision-making. The goal is to improve public health outcomes equitably, not to optimize enforcement efficiency at the cost of fairness.\n\n---\n\n## Appendix: Session Info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.1 (2025-06-13 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=Chinese (Simplified)_China.utf8 \n[2] LC_CTYPE=Chinese (Simplified)_China.utf8   \n[3] LC_MONETARY=Chinese (Simplified)_China.utf8\n[4] LC_NUMERIC=C                               \n[5] LC_TIME=Chinese (Simplified)_China.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] spatstat.explore_3.5-3 nlme_3.1-168           spatstat.random_3.4-2 \n [4] spatstat.geom_3.6-0    spatstat.univar_3.1-4  spatstat.data_3.1-9   \n [7] classInt_0.4-11        kableExtra_1.4.0       knitr_1.50            \n[10] patchwork_1.3.2        MASS_7.3-65            FNN_1.1.4.1           \n[13] spdep_1.4-1            spData_2.3.4           terra_1.8-70          \n[16] viridis_0.6.5          viridisLite_0.4.2      here_1.0.2            \n[19] sf_1.0-21              lubridate_1.9.4        forcats_1.0.0         \n[22] stringr_1.5.2          dplyr_1.1.4            purrr_1.1.0           \n[25] readr_2.1.5            tidyr_1.3.1            tibble_3.3.0          \n[28] ggplot2_4.0.0          tidyverse_2.0.0       \n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1      farver_2.1.2          S7_0.2.0             \n [4] fastmap_1.2.0         digest_0.6.37         timechange_0.3.0     \n [7] lifecycle_1.0.4       magrittr_2.0.4        compiler_4.5.1       \n[10] rlang_1.1.6           tools_4.5.1           yaml_2.3.10          \n[13] labeling_0.4.3        htmlwidgets_1.6.4     bit_4.6.0            \n[16] sp_2.2-0              xml2_1.4.0            RColorBrewer_1.1-3   \n[19] abind_1.4-8           KernSmooth_2.23-26    withr_3.0.2          \n[22] grid_4.5.1            polyclip_1.10-7       e1071_1.7-16         \n[25] scales_1.4.0          spatstat.utils_3.2-0  isoband_0.2.7        \n[28] cli_3.6.5             crayon_1.5.3          rmarkdown_2.29       \n[31] generics_0.1.4        rstudioapi_0.17.1     tzdb_0.5.0           \n[34] DBI_1.2.3             proxy_0.4-27          parallel_4.5.1       \n[37] s2_1.1.9              vctrs_0.6.5           boot_1.3-32          \n[40] Matrix_1.7-4          jsonlite_2.0.0        hms_1.1.3            \n[43] bit64_4.6.0-1         tensor_1.5.1          systemfonts_1.2.3    \n[46] units_0.8-7           goftest_1.2-3         glue_1.8.0           \n[49] codetools_0.2-20      stringi_1.8.7         gtable_0.3.6         \n[52] deldir_2.0-4          pillar_1.11.1         htmltools_0.5.8.1    \n[55] R6_2.6.1              wk_0.9.4              textshaping_1.0.3    \n[58] rprojroot_2.1.1       vroom_1.6.5           evaluate_1.0.5       \n[61] lattice_0.22-7        backports_1.5.0       broom_1.0.10         \n[64] class_7.3-23          Rcpp_1.1.0            spatstat.sparse_3.1-0\n[67] svglite_2.2.1         gridExtra_2.3         xfun_0.53            \n[70] pkgconfig_2.0.3      \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "Fang_Zhe_Assignment4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}