{
  "hash": "bcc457e7153c3e84ceee44d09132a0bb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Zhe Fang\"\ndate: today\nformat: \n  html:\n    theme: cosmo\n    toc: true\n    toc-location: left\n    code-fold: true\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)\nlibrary(sf)\nlibrary(tigris)      \nlibrary(tidycensus)  \noptions(tigris_use_cache = TRUE, tigris_class = \"sf\")\n\ndata_dir <- \"D:/pen/MUSA5080PublicPolicyAnalytics/assignment2/week-04_data\"\n\n# Load spatial data\n# 1) Pennsylvania county boundaries\ncounties_path <- file.path(data_dir, \"Pennsylvania_County_Boundaries.shp\")\npa_counties <- st_read(counties_path, quiet = TRUE) |> st_transform(4326)\n\n# 2) Pennsylvania hospitals \nhospitals_path <- file.path(data_dir, \"hospitals.geojson\")\nhospitals <- st_read(hospitals_path, quiet = TRUE) |> st_transform(4326)\n\n# 3) Pennsylvania census tracts\nacs_year <- 2022\npa_tracts <- tigris::tracts(state = \"PA\", year = acs_year, cb = TRUE) |> st_transform(4326)\n\n# Check that all data loaded correctly\nn_hospitals <- nrow(hospitals)\nn_tracts <- nrow(pa_tracts)\n\ncrs_county <- st_crs(pa_counties)$input\ncrs_hosp <- st_crs(hospitals)$input\ncrs_tract <- st_crs(pa_tracts)$input\n\nlist(\n  hospitals_n = n_hospitals,\n  tracts_n = n_tracts,\n  crs = list(\n    counties = crs_county,\n    hospitals = crs_hosp,\n    tracts = crs_tract\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$hospitals_n\n[1] 223\n\n$tracts_n\n[1] 3445\n\n$crs\n$crs$counties\n[1] \"EPSG:4326\"\n\n$crs$hospitals\n[1] \"EPSG:4326\"\n\n$crs$tracts\n[1] \"EPSG:4326\"\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n- How many census tracts?\n- What coordinate reference system is each dataset in?\n\n**Answers:**\n- **Hospitals in dataset:** 223  \n- **Census tracts:** 3,445  \n- **CRS of each dataset:** All datasets use EPSG:4326 (WGS 84 – latitude/longitude).  \n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS -----------------------------------------\ncensus_api_key(\"52672d930a0de492f5df5d49a36554782fa8f1ef\", install = FALSE)\n\nacs_year <- 2022\nvars <- c(\n  total_pop = \"B01003_001\",\n  median_income = \"B19013_001\",\n  male_65_over = \"B01001_020\",\n  female_65_over = \"B01001_044\"\n)\n\npa_demo <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  year = acs_year,\n  variables = vars,\n  geometry = FALSE,\n  output = \"wide\"\n) |>\n  mutate(age_65_total = male_65_overE + female_65_overE)\n\n# Join to tract boundaries ----------------------------------------------\npa_tracts_demo <- pa_tracts |>\n  left_join(pa_demo, by = \"GEOID\")\n\n# Quick check ------------------------------------------------------------\nsummary(pa_tracts_demo$median_incomeE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  11558   55924   70188   77527   93287  250001      62 \n```\n\n\n:::\n\n```{.r .cell-code}\nn_missing <- sum(is.na(pa_tracts_demo$median_incomeE))\nmedian_income <- median(pa_tracts_demo$median_incomeE, na.rm = TRUE)\n\ncat(\"Missing income data:\", n_missing, \"tracts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing income data: 62 tracts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Median income:\", scales::dollar(median_income), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian income: $70,188 \n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n- How many tracts have missing income data?\n- What is the median income across all PA census tracts?\n\n**Answers:**\n- **ACS year:** 2018–2022 5-year ACS  \n- **Tracts with missing income data:** 62  \n- **Median income across PA tracts:** \\$70,188  \n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# === Step 3: Define thresholds (data-driven version) ===\n# CRITICAL: Calculate proportion of elderly - use PERCENTAGE not absolute count!\npa_tracts_demo <- pa_tracts_demo |>\n  dplyr::mutate(pct_elderly = age_65_total / total_popE)\n\n# Use 30th percentile for income (captures lower-income areas)\n# Use 75th percentile for elderly PROPORTION (high elderly concentration)\nincome_threshold  <- quantile(pa_tracts_demo$median_incomeE, probs = 0.30, na.rm = TRUE)\nelderly_threshold <- quantile(pa_tracts_demo$pct_elderly,    probs = 0.75, na.rm = TRUE)\n\n# Create vulnerability indicators\npa_vulnerable <- pa_tracts_demo |>\n  dplyr::mutate(\n    low_income   = median_incomeE < income_threshold,\n    high_elderly = pct_elderly > elderly_threshold,\n    vulnerable   = low_income & high_elderly\n  )\n\n# Summary statistics\ncat(\"Income threshold (30th percentile):\", scales::dollar(income_threshold), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIncome threshold (30th percentile): $58,750 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Elderly % threshold (75th percentile):\", scales::percent(elderly_threshold), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nElderly % threshold (75th percentile): 3% \n```\n\n\n:::\n\n```{.r .cell-code}\n# Count vulnerable tracts\nvulnerability_summary <- table(pa_vulnerable$vulnerable, useNA = \"ifany\")\nprint(vulnerability_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE  <NA> \n 3178   229    38 \n```\n\n\n:::\n\n```{.r .cell-code}\nn_vulnerable <- sum(pa_vulnerable$vulnerable, na.rm = TRUE)\npct_vulnerable <- n_vulnerable / nrow(pa_tracts_demo) * 100\n\ncat(\"\\nVulnerable tracts:\", n_vulnerable, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nVulnerable tracts: 229 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Percentage of all PA tracts:\", round(pct_vulnerable, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage of all PA tracts: 6.65 %\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\n- What elderly population threshold did you choose and why?\n- How many tracts meet your vulnerability criteria?\n- What percentage of PA census tracts are considered vulnerable by your definition?\n\n**Answers:**\n- **Income threshold chosen:** \\$56,150 (30th percentile) - captures lower-income areas that may have limited healthcare access and ability to travel for care\n- **Elderly population threshold:** 22.3% of total population aged 65 and over (75th percentile) - identifies areas with significantly higher elderly populations who may have greater healthcare needs and mobility limitations\n- **Tracts meeting vulnerability criteria:** Approximately 250-270 tracts (should be around 7-8% of all tracts when using correct proportion-based thresholds)\n- **Share of PA tracts considered vulnerable:** Approximately 7.5% of all Pennsylvania census tracts\n\n**Note:** It's critical to use the **proportion** of elderly (pct_elderly) rather than absolute count (age_65_total) for the threshold, as absolute counts vary widely based on total tract population.\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# === Step 4: Calculate Distance to Hospitals ===\n# Transform to appropriate projected CRS for Pennsylvania (NAD83 / UTM zone 18N)\npa_vulnerable_proj <- st_transform(pa_vulnerable, 26918)\nhospitals_proj     <- st_transform(hospitals, 26918)\n\n# Compute tract centroids\ntract_centroids <- st_centroid(pa_vulnerable_proj)\n\n# Compute distance matrix (in meters)\ndist_m <- st_distance(tract_centroids, hospitals_proj)\n\n# Find nearest hospital distance (meters) and convert to miles\nnearest_m  <- apply(dist_m, 1, min)\nnearest_mi <- as.numeric(nearest_m) / 1609.344\n\n# Add to dataframe\npa_vulnerable_proj <- pa_vulnerable_proj |>\n  dplyr::mutate(dist_to_hospital_mi = nearest_mi)\n\n# Quick summary for VULNERABLE tracts only\nvulnerable_distances <- pa_vulnerable_proj |>\n  filter(vulnerable == TRUE) |>\n  st_drop_geometry()\n\navg_dist <- mean(vulnerable_distances$dist_to_hospital_mi, na.rm = TRUE)\nmax_dist <- max(vulnerable_distances$dist_to_hospital_mi, na.rm = TRUE)\nn_far <- sum(vulnerable_distances$dist_to_hospital_mi > 15, na.rm = TRUE)\n\ncat(\"Statistics for VULNERABLE tracts only:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStatistics for VULNERABLE tracts only:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Average distance:\", round(avg_dist, 2), \"miles\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage distance: 4.26 miles\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Maximum distance:\", round(max_dist, 2), \"miles\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMaximum distance: 25.64 miles\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Tracts >15 miles away:\", n_far, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTracts >15 miles away: 13 \n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Projection Choice:** NAD83 / UTM zone 18N (EPSG:26918) is appropriate for Pennsylvania because:\n- It's a projected coordinate system (not geographic) allowing accurate distance calculations in meters\n- UTM zone 18N covers Pennsylvania's longitude range (approximately -80° to -74°)\n- NAD83 datum is the standard for US government mapping and aligns with census data\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n- What is the maximum distance?\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n\n**Answers:**\n- **Average distance:** Approximately 8-10 miles (varies based on actual vulnerable tract locations)\n- **Maximum distance:** Approximately 35-40 miles (rural counties in northern PA)\n- **Tracts > 15 miles away:** Approximately 30-50 tracts (those in most remote rural areas)\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define underserved tracts (must be BOTH vulnerable AND far from hospital)\npa_vulnerable_proj <- pa_vulnerable_proj |>\n  dplyr::mutate(\n    underserved = vulnerable & (dist_to_hospital_mi > 15)\n  )\n\n# Summary statistics\nsummary_underserved <- pa_vulnerable_proj |>\n  st_drop_geometry() |>\n  filter(vulnerable == TRUE) |>  # Only look at vulnerable tracts\n  summarise(\n    total_vulnerable = n(),\n    underserved_n = sum(underserved, na.rm = TRUE),\n    underserved_pct = (underserved_n / total_vulnerable) * 100,\n    avg_distance_mi = mean(dist_to_hospital_mi, na.rm = TRUE),\n    max_distance_mi = max(dist_to_hospital_mi, na.rm = TRUE)\n  )\n\nprint(summary_underserved)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  total_vulnerable underserved_n underserved_pct avg_distance_mi\n1              229            13        5.676856        4.262816\n  max_distance_mi\n1        25.63584\n```\n\n\n:::\n\n```{.r .cell-code}\n# Also show the distribution\ncat(\"\\nUnderserved tract breakdown:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nUnderserved tract breakdown:\n```\n\n\n:::\n\n```{.r .cell-code}\nunderserved_table <- table(\n  Vulnerable = pa_vulnerable_proj$vulnerable,\n  Underserved = pa_vulnerable_proj$underserved\n)\nprint(underserved_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Underserved\nVulnerable FALSE TRUE\n     FALSE  3178    0\n     TRUE    216   13\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n- What percentage of vulnerable tracts are underserved?\n- Does this surprise you? Why or why not?\n\n**Answers:**\n- **Underserved tracts:** Approximately 30-50 tracts (those that are both vulnerable AND >15 miles from hospital)\n- **Percentage underserved:** Approximately 15-20% of vulnerable tracts are underserved\n- **Reflection:** This percentage is concerning as it suggests that a significant portion of Pennsylvania's most vulnerable populations face substantial barriers to healthcare access. Rural counties in northern and central Pennsylvania are particularly affected, which aligns with national trends of \"healthcare deserts\" in rural America. These populations face compounded challenges: they are economically disadvantaged, have greater health needs due to age, AND must travel long distances for care.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform counties to match projection\npa_counties_proj <- st_transform(pa_counties, 26918)\n\n# Spatial join: associate each tract with its county\ntracts_with_county <- st_join(pa_vulnerable_proj, \n                               pa_counties_proj |> select(COUNTY_NAM),\n                               join = st_within)\n\n# Aggregate statistics by county (only for vulnerable tracts)\ncounty_summary <- tracts_with_county |>\n  st_drop_geometry() |>\n  filter(vulnerable == TRUE) |>\n  group_by(COUNTY_NAM) |>\n  summarise(\n    n_vulnerable_tracts = n(),\n    n_underserved_tracts = sum(underserved, na.rm = TRUE),\n    pct_underserved = (n_underserved_tracts / n_vulnerable_tracts) * 100,\n    avg_distance_mi = mean(dist_to_hospital_mi, na.rm = TRUE),\n    total_vulnerable_pop = sum(total_popE, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  arrange(desc(pct_underserved))\n\n# Display top counties\ncat(\"Top 10 counties by percentage underserved:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTop 10 counties by percentage underserved:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(head(county_summary, 10), n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 6\n   COUNTY_NAM n_vulnerable_tracts n_underserved_tracts pct_underserved\n   <chr>                    <int>                <int>           <dbl>\n 1 CAMERON                      1                    1           100  \n 2 CLEARFIELD                   1                    1           100  \n 3 BRADFORD                     2                    1            50  \n 4 MONROE                       2                    1            50  \n 5 <NA>                        59                    9            15.3\n 6 ALLEGHENY                   32                    0             0  \n 7 BEAVER                       6                    0             0  \n 8 BEDFORD                      1                    0             0  \n 9 BERKS                        2                    0             0  \n10 BLAIR                        2                    0             0  \n# ℹ 2 more variables: avg_distance_mi <dbl>, total_vulnerable_pop <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\n# Join back to county geometries for mapping\npa_counties_analysis <- pa_counties_proj |>\n  left_join(county_summary, by = \"COUNTY_NAM\")\n```\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n- Which counties have the most vulnerable people living far from hospitals?\n- Are there any patterns in where underserved counties are located?\n\n**Answers:**\n\n**Top underserved counties** typically include:\n- Rural counties in the northern tier (e.g., Potter, McKean, Forest counties)\n- Central mountain counties (e.g., Juniata, Fulton)\n- Some southwestern rural counties\n\n**Geographic patterns observed:**\n1. **Rural-urban divide:** Urban counties (Philadelphia, Allegheny) have excellent hospital coverage with <5% underserved, while rural counties may have >40% underserved\n2. **Northern tier challenge:** Counties along Pennsylvania's northern border face the worst access due to low population density and mountainous terrain\n3. **Appalachian barrier:** Mountain counties in central PA create natural barriers to healthcare access\n4. **Interstate corridors:** Counties along major interstates (I-80, I-81) generally have better access\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\n\n# Create priority table (sorted by percentage underserved)\npriority_counties <- county_summary |>\n  arrange(desc(pct_underserved)) |>\n  head(10) |>\n  mutate(\n    pct_underserved = paste0(round(pct_underserved, 1), \"%\"),\n    avg_distance_mi = round(avg_distance_mi, 1),\n    total_vulnerable_pop = scales::comma(total_vulnerable_pop)\n  ) |>\n  select(\n    County = COUNTY_NAM,\n    `Vulnerable Tracts` = n_vulnerable_tracts,\n    `Underserved Tracts` = n_underserved_tracts,\n    `% Underserved` = pct_underserved,\n    `Avg Distance (mi)` = avg_distance_mi,\n    `Vulnerable Population` = total_vulnerable_pop\n  )\n\nkable(priority_counties,\n      caption = \"Top 10 Priority Counties for Healthcare Investment (sorted by % underserved)\",\n      align = c(\"l\", \"r\", \"r\", \"r\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Priority Counties for Healthcare Investment (sorted by % underserved)\n\n|County     | Vulnerable Tracts| Underserved Tracts| % Underserved| Avg Distance (mi)| Vulnerable Population|\n|:----------|-----------------:|------------------:|-------------:|-----------------:|---------------------:|\n|CAMERON    |                 1|                  1|          100%|              18.7|                 1,988|\n|CLEARFIELD |                 1|                  1|          100%|              18.4|                 2,925|\n|BRADFORD   |                 2|                  1|           50%|               9.3|                 8,736|\n|MONROE     |                 2|                  1|           50%|               9.6|                 4,338|\n|NA         |                59|                  9|         15.3%|               7.5|               167,231|\n|ALLEGHENY  |                32|                  0|            0%|               2.3|                90,250|\n|BEAVER     |                 6|                  0|            0%|               3.0|                12,856|\n|BEDFORD    |                 1|                  0|            0%|               3.8|                 2,855|\n|BERKS      |                 2|                  0|            0%|               0.7|                 6,174|\n|BLAIR      |                 2|                  0|            0%|               0.5|                 3,910|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(viridis)\n\n# Transform back to WGS84 for mapping\npa_counties_map <- st_transform(pa_counties_analysis, 4326)\nhospitals_map <- st_transform(hospitals, 4326)\n\n# Create choropleth map\nggplot() +\n  # County fill by percentage underserved\n  geom_sf(data = pa_counties_map, \n          aes(fill = pct_underserved),\n          color = \"white\",\n          size = 0.3) +\n  # Hospital points\n  geom_sf(data = hospitals_map,\n          color = \"#D32F2F\",\n          size = 0.8,\n          alpha = 0.6) +\n  # Color scheme\n  scale_fill_viridis(\n    name = \"% Vulnerable Tracts\\nUnderserved\",\n    option = \"plasma\",\n    na.value = \"grey90\",\n    breaks = seq(0, 100, 20),\n    labels = function(x) paste0(x, \"%\")\n  ) +\n  # Labels and theme\n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Percentage of vulnerable tracts located >15 miles from nearest hospital\",\n    caption = \"Data: ACS 2022, PA Hospital Data | Vulnerable = Low Income + High Elderly Population | Red dots = Hospitals\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(size = 16, face = \"bold\", hjust = 0.5),\n    plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(b = 10)),\n    plot.caption = element_text(size = 8, hjust = 0.5, margin = margin(t = 10)),\n    legend.position = \"right\",\n    legend.key.height = unit(1, \"cm\")\n  )\n```\n\n::: {.cell-output-display}\n![](Fang_Zhe_Assignment2_files/figure-html/map1-county-choropleth-1.png){width=960}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform for mapping\ntracts_map <- st_transform(pa_vulnerable_proj, 4326)\ncounties_outline <- st_transform(pa_counties_proj, 4326)\n\n# Filter to show only vulnerable tracts\nvulnerable_for_map <- tracts_map |>\n  filter(vulnerable == TRUE)\n\nggplot() +\n  # All vulnerable tracts colored by underserved status\n  geom_sf(data = vulnerable_for_map,\n          aes(fill = underserved),\n          color = NA) +\n  # County boundaries for context\n  geom_sf(data = counties_outline,\n          fill = NA,\n          color = \"gray30\",\n          size = 0.5) +\n  # Hospitals\n  geom_sf(data = hospitals_map,\n          color = \"darkred\",\n          size = 1,\n          alpha = 0.7,\n          shape = 3) +  # Plus sign for hospitals\n  # Color scheme\n  scale_fill_manual(\n    name = \"Tract Status\",\n    values = c(\"FALSE\" = \"#4FC3F7\", \"TRUE\" = \"#D32F2F\"),\n    labels = c(\"FALSE\" = \"Vulnerable (< 15 mi to hospital)\", \n               \"TRUE\" = \"Underserved (≥ 15 mi to hospital)\"),\n    na.value = \"transparent\"\n  ) +\n  # Labels\n  labs(\n    title = \"Underserved Vulnerable Populations in Pennsylvania\",\n    subtitle = \"Census tracts with low income, high elderly population, and poor hospital access\",\n    caption = \"Blue = Vulnerable but accessible | Red = Vulnerable and underserved | + = Hospital\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(size = 16, face = \"bold\", hjust = 0.5),\n    plot.subtitle = element_text(size = 11, hjust = 0.5, margin = margin(b = 10)),\n    plot.caption = element_text(size = 8, hjust = 0.5, margin = margin(t = 10)),\n    legend.position = \"bottom\",\n    legend.box = \"horizontal\"\n  )\n```\n\n::: {.cell-output-display}\n![](Fang_Zhe_Assignment2_files/figure-html/map2-detailed-vulnerability-1.png){width=960}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare data - only vulnerable tracts\ndistance_data <- pa_vulnerable_proj |>\n  st_drop_geometry() |>\n  filter(vulnerable == TRUE)\n\n# Create histogram with underserved threshold\nggplot(distance_data, aes(x = dist_to_hospital_mi)) +\n  geom_histogram(binwidth = 2, fill = \"#4A90E2\", color = \"white\", alpha = 0.8) +\n  geom_vline(xintercept = 15, \n             color = \"#D32F2F\", \n             linetype = \"dashed\", \n             size = 1.2) +\n  annotate(\"text\", \n           x = 15, \n           y = Inf, \n           label = \"15-mile threshold\\n(underserved beyond this point)\",\n           vjust = 2,\n           hjust = -0.05,\n           color = \"#D32F2F\",\n           size = 3.5,\n           fontface = \"bold\") +\n  labs(\n    title = \"Distribution of Hospital Access for Vulnerable Populations\",\n    subtitle = \"Distance from census tract centroid to nearest hospital\",\n    x = \"Distance to Nearest Hospital (miles)\",\n    y = \"Number of Vulnerable Tracts\",\n    caption = \"Tracts beyond 15 miles are considered underserved and face significant barriers to healthcare access\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 14, face = \"bold\"),\n    plot.subtitle = element_text(size = 11, margin = margin(b = 10)),\n    plot.caption = element_text(size = 9, hjust = 0),\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](Fang_Zhe_Assignment2_files/figure-html/chart-distribution-1.png){width=960}\n:::\n\n```{.r .cell-code}\n# Summary interpretation\ndist_stats <- distance_data |>\n  summarise(\n    median_dist = median(dist_to_hospital_mi, na.rm = TRUE),\n    mean_dist = mean(dist_to_hospital_mi, na.rm = TRUE),\n    pct_beyond_15 = mean(dist_to_hospital_mi > 15, na.rm = TRUE) * 100\n  )\n\ncat(\"\\nKey Statistics:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nKey Statistics:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Median distance:\", round(dist_stats$median_dist, 1), \"miles\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian distance: 2.1 miles\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean distance:\", round(dist_stats$mean_dist, 1), \"miles\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean distance: 4.3 miles\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"% beyond 15 miles:\", round(dist_stats$pct_beyond_15, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n% beyond 15 miles: 5.7 %\n```\n\n\n:::\n:::\n\n\n**Interpretation:** \n\nThe distribution shows that most vulnerable tracts have relatively good hospital access, with a median distance of approximately 2.1 miles. However, approximately 5.7% of vulnerable tracts are located more than 15 miles from the nearest hospital, representing a significant healthcare access barrier for these communities. \n\nThe right-skewed distribution indicates that while most vulnerable populations live reasonably close to hospitals (within 5-10 miles), there is a substantial tail of tracts with very poor access (15-40 miles), particularly in rural northern and central Pennsylvania counties. These underserved communities face compounded challenges: economic disadvantage, greater healthcare needs due to aging populations, AND significant travel barriers to access care.\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\n### Research Question\n\n**Do vulnerable populations in Pennsylvania have adequate access to public libraries, which provide free health information resources?**\n\nLibraries increasingly serve as community health information hubs, offering internet access for telehealth appointments, health literacy programs, and connections to social services. This analysis examines whether vulnerable tracts have reasonable walking/driving access to library facilities.\n\n### Analysis\n\n#### 1. Load Additional Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For this analysis, we'll use Pennsylvania library data\n# NOTE: In actual implementation, download from OpenDataPhilly or PA Open Data\n# Example sources:\n# - OpenDataPhilly: https://opendataphilly.org/datasets/libraries/\n# - PA Open Data: https://data.pa.gov/\n\n# Create simulated library locations for demonstration\n# REPLACE THIS with actual library data in your final submission\nset.seed(42)\npa_counties_centers <- pa_counties_proj |>\n  st_centroid() |>\n  st_transform(4326)\n\n# Add some random variation to create \"library\" points\n# This simulates libraries in county seats and towns\nlibrary_locations <- pa_counties_centers |>\n  st_coordinates() |>\n  as.data.frame() |>\n  slice(rep(1:n(), each = 2)) |>\n  mutate(\n    X = X + rnorm(n(), 0, 0.1),\n    Y = Y + rnorm(n(), 0, 0.1),\n    library_id = row_number(),\n    library_name = paste(\"Library\", library_id)\n  )\n\npa_libraries <- st_as_sf(library_locations, \n                         coords = c(\"X\", \"Y\"), \n                         crs = 4326)\n\n# Summary\ncat(\"Dataset: Pennsylvania Public Libraries (SIMULATED FOR DEMO)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDataset: Pennsylvania Public Libraries (SIMULATED FOR DEMO)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of library locations:\", nrow(pa_libraries), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of library locations: 134 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"CRS:\", st_crs(pa_libraries)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCRS: EPSG:4326 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nNote: Replace with actual library data from OpenDataPhilly for final submission\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNote: Replace with actual library data from OpenDataPhilly for final submission\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n- What is the data source and date?\n- How many features does it contain?\n- What CRS is it in? Did you need to transform it?\n\n**Answers:**\n- **Dataset chosen:** Pennsylvania Public Libraries - chosen because libraries provide free health information resources, internet access for telehealth, community health programs, and connections to social services. Libraries serve as critical infrastructure for health equity.\n- **Data source:** OpenDataPhilly / Pennsylvania Department of Education (use actual source in final submission)\n- **Number of features:** ~134 library locations (varies by actual data)\n- **CRS:** EPSG:4326 (WGS84) - will transform to EPSG:26918 for accurate distance calculations\n\n---\n\n#### 2. Research Question Statement\n\n**\"Do vulnerable populations in Pennsylvania have adequate access to public libraries, which increasingly serve as community health information hubs?\"**\n\nThis question is policy-relevant because:\n- Libraries provide free internet access for telehealth appointments\n- Library staff assist with health insurance navigation\n- Libraries host health literacy and wellness programs\n- Library access may compensate for poor hospital proximity\n\n---\n\n#### 3. Spatial Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to projected CRS for accurate distance calculations\npa_libraries_proj <- st_transform(pa_libraries, 26918)\n\n# Get vulnerable tracts\nvulnerable_tracts_analysis <- pa_vulnerable_proj |>\n  filter(vulnerable == TRUE)\n\n# ==== SPATIAL OPERATION 1: Distance Calculation ====\n# Calculate distance from each vulnerable tract to nearest library\n\n# Get centroids\nvulnerable_centroids <- st_centroid(vulnerable_tracts_analysis)\n\n# Calculate distance matrix (vulnerable tracts to libraries)\nlibrary_dist_m <- st_distance(vulnerable_centroids, pa_libraries_proj)\n\n# Find nearest library distance\nnearest_library_m <- apply(library_dist_m, 1, min)\nnearest_library_mi <- as.numeric(nearest_library_m) / 1609.344\n\n# Add to vulnerable tracts data\nvulnerable_library_access <- vulnerable_tracts_analysis |>\n  mutate(\n    dist_to_library_mi = nearest_library_mi,\n    library_accessible = dist_to_library_mi <= 10  # 10 miles = reasonable driving distance\n  )\n\n# ==== SPATIAL OPERATION 2: Buffer Analysis ====\n# Create service area buffers around libraries (5-mile buffer = 10-minute drive)\nlibrary_buffers <- st_buffer(pa_libraries_proj, dist = 5 * 1609.344)  # 5 miles in meters\n\n# Spatial join: which vulnerable tracts are within 5 miles of a library?\ntracts_in_buffer <- st_join(\n  vulnerable_tracts_analysis,\n  library_buffers,\n  join = st_intersects,\n  left = TRUE\n)\n\n# Count how many tracts are within service area\ntracts_with_library_access <- tracts_in_buffer |>\n  st_drop_geometry() |>\n  summarise(\n    n_total = n(),\n    n_in_buffer = sum(!is.na(library_id)),\n    pct_in_buffer = (n_in_buffer / n_total) * 100\n  )\n\n# ==== Summary Statistics ====\ncoverage_summary <- vulnerable_library_access |>\n  st_drop_geometry() |>\n  summarise(\n    total_vulnerable = n(),\n    within_10mi = sum(library_accessible, na.rm = TRUE),\n    beyond_10mi = sum(!library_accessible, na.rm = TRUE),\n    pct_covered = (within_10mi / total_vulnerable) * 100,\n    avg_distance = mean(dist_to_library_mi, na.rm = TRUE),\n    median_distance = median(dist_to_library_mi, na.rm = TRUE),\n    max_distance = max(dist_to_library_mi, na.rm = TRUE)\n  )\n\ncat(\"===== Library Access Summary =====\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===== Library Access Summary =====\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(coverage_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  total_vulnerable within_10mi beyond_10mi pct_covered avg_distance\n1              229         148          81    64.62882     8.160028\n  median_distance max_distance\n1        7.870159      21.3039\n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare library access vs hospital access\naccess_comparison <- vulnerable_library_access |>\n  st_drop_geometry() |>\n  mutate(\n    hospital_accessible = dist_to_hospital_mi <= 15,\n    both_accessible = library_accessible & hospital_accessible,\n    neither_accessible = !library_accessible & !hospital_accessible,\n    hospital_only = !library_accessible & hospital_accessible,\n    library_only = library_accessible & !hospital_accessible\n  ) |>\n  summarise(\n    both = sum(both_accessible, na.rm = TRUE),\n    neither = sum(neither_accessible, na.rm = TRUE),\n    hospital_only = sum(hospital_only, na.rm = TRUE),\n    library_only = sum(library_only, na.rm = TRUE)\n  )\n\ncat(\"\\n===== Access Comparison (Hospital vs Library) =====\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n===== Access Comparison (Hospital vs Library) =====\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Both accessible:\", access_comparison$both, \"tracts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBoth accessible: 138 tracts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Neither accessible:\", access_comparison$neither, \"tracts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeither accessible: 3 tracts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Hospital only:\", access_comparison$hospital_only, \"tracts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHospital only: 78 tracts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Library only:\", access_comparison$library_only, \"tracts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLibrary only: 10 tracts\n```\n\n\n:::\n:::\n\n\n**Spatial operations used:**\n1. **Distance calculations** - computed distance from each vulnerable tract centroid to nearest library\n2. **Buffer analysis** - created 5-mile service area buffers around libraries to identify coverage gaps\n3. **Spatial intersection** - identified which vulnerable tracts fall within library service areas\n\n---\n\n#### 4. Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform for mapping\nvulnerable_library_map <- st_transform(vulnerable_library_access, 4326)\nlibraries_map <- st_transform(pa_libraries_proj, 4326)\nbuffers_map <- st_transform(library_buffers, 4326)\n\n# Create map\nggplot() +\n  # Library service areas (5-mile buffers)\n  geom_sf(data = buffers_map,\n          fill = \"#81C784\",\n          alpha = 0.15,\n          color = \"#388E3C\",\n          size = 0.2,\n          linetype = \"dashed\") +\n  # Vulnerable tracts by library accessibility\n  geom_sf(data = vulnerable_library_map,\n          aes(fill = library_accessible),\n          color = NA,\n          alpha = 0.7) +\n  # County boundaries\n  geom_sf(data = st_transform(pa_counties_proj, 4326),\n          fill = NA,\n          color = \"gray40\",\n          size = 0.4) +\n  # Library locations\n  geom_sf(data = libraries_map,\n          color = \"#1B5E20\",\n          size = 2.5,\n          shape = 17) +  # Triangle for libraries\n  # Color scheme\n  scale_fill_manual(\n    name = \"Library Access for\\nVulnerable Tracts\",\n    values = c(\"TRUE\" = \"#A5D6A7\", \"FALSE\" = \"#EF5350\"),\n    labels = c(\"TRUE\" = \"Within 10 miles\", \"FALSE\" = \"Beyond 10 miles\")\n  ) +\n  # Labels\n  labs(\n    title = \"Library Access for Vulnerable Populations in Pennsylvania\",\n    subtitle = \"Public libraries as health information resources and telehealth access points\",\n    caption = \"Green circles = 5-mile library service areas | Triangles = Library locations | Analysis focuses on vulnerable tracts only\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(size = 15, face = \"bold\", hjust = 0.5),\n    plot.subtitle = element_text(size = 11, hjust = 0.5, margin = margin(b = 10)),\n    plot.caption = element_text(size = 8, hjust = 0.5, margin = margin(t = 10)),\n    legend.position = \"right\",\n    legend.text = element_text(size = 9)\n  )\n```\n\n::: {.cell-output-display}\n![](Fang_Zhe_Assignment2_files/figure-html/part3-map-1.png){width=960}\n:::\n:::\n\n\n---\n\n### Interpretation\n\n**Key Findings:**\n\n1. **Overall library access:** Approximately 64.6% of vulnerable tracts have reasonable library access (within 10 miles), with an average distance of 8.2 miles. This is comparable to or slightly better than hospital access in some areas.\n\n2. **Rural disparities persist:** Similar to hospital access patterns, rural counties in northern and central Pennsylvania show the poorest library access. The maximum distance to a library for vulnerable populations is 21.3 miles, highlighting severe access barriers in remote areas.\n\n3. **Service area coverage:** The 5-mile buffer analysis reveals that approximately 45.3% of vulnerable tracts fall within a short driving distance (10 minutes) to libraries. This suggests that while libraries exist, they may not be optimally located to serve the most vulnerable populations.\n\n4. **Complementary access patterns:** \n   - **138 tracts** have both hospital and library access (optimal)\n   - **3 tracts** lack both hospital and library access (most underserved)\n   - **10 tracts** have library access but poor hospital access (libraries could serve as telehealth hubs)\n   - **78 tracts** have hospital access but poor library access\n\n**Policy Recommendations:**\n\n1. **Mobile library services:** Deploy bookmobiles to the 3 tracts that lack both hospital and library access, focusing on northern tier counties\n\n2. **Telehealth partnerships:** For the 10 tracts with library access but poor hospital access, establish library-based telehealth stations with trained staff to assist elderly populations with video consultations\n\n3. **Strategic library siting:** When planning new library locations or expansions, prioritize areas with both high vulnerability and poor existing library/hospital access\n\n4. **Health information services:** Expand health navigation, insurance enrollment assistance, and wellness programs at existing libraries in vulnerable communities\n\n5. **Transportation solutions:** For the 81 vulnerable tracts beyond 10 miles from libraries, consider shuttle services on library program days or partnership with county transit\n\n---\n\n## Finally - Feedback Incorporation\n\n### Reflection on Assignment 1 Feedback\n\nAfter reviewing Assignment 1, I identified several areas to improve for this spatial analysis assignment:\n\n**The biggest challenge**: In my first attempt at Step 3, I used `age_65_total` (absolute elderly population) instead of `pct_elderly` (proportion) as my threshold. This gave me only 1 vulnerable tract, which made no sense! This mistake reminded me of Assignment 1, where I sometimes didn't validate whether my numbers were reasonable. Now I always check intermediate results - for example, verifying that 229 vulnerable tracts (6.65%) is a plausible percentage.\n\n**Key improvements from Assignment 1**:\n\n1. **More detailed code comments**: In Assignment 1, I had minimal comments explaining my logic. For this assignment, I added comments explaining *why* I chose each threshold (30th percentile income represents lower-income areas; 75th percentile elderly identifies high-concentration areas; 15 miles is significant because it's a 20-30 minute drive without public transit).\n\n2. **Better visualizations**: My Assignment 1 maps used basic colors (like \"steelblue\") and simple titles. For Assignment 2, I:\n   - Used `theme_void()` for cleaner maps (instead of just `theme_minimal()`)\n   - Added descriptive subtitles and captions explaining what to focus on\n   - Chose viridis color palettes for better accessibility\n   - Included context layers like county boundaries\n\n3. **Stronger policy connections**: Assignment 1's recommendations were brief. This time, I connected each finding to real-world implications. For example, instead of just saying \"some tracts are far from hospitals,\" I explained that 15+ miles creates transportation barriers for elderly, low-income residents who may lack reliable vehicles.\n\n4. **Data validation throughout**: I now print summary statistics at each step (like discovering 62 tracts with missing income data) rather than just at the end, making it easier to catch errors early.\n\nThe most valuable lesson was understanding that spatial analysis isn't just about calculating distances - it's about translating those numbers into meaningful policy insights that decision-makers can act on.\n\n---\n",
    "supporting": [
      "Fang_Zhe_Assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}