{
  "hash": "b66160fb5d8655a084ddd0a3b1d11ca4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Eviction Predictor\"\nauthor: \"\"\ndate: \"2025-12-01\"\noutput: html_document\n---\n\n# Project Setup and Environment\n\nThis code chunk loads all required R packages and sets a global chunk option for reproducibility. Tidyverse and dplyr are used for data cleaning, reshaping, and merging multiple datasets, which is key given the integration of eviction records, economic indicators, and demographic data. Spatial components are handled using sf and tigris to manipulate census geographies and enable tract-level analysis, while tidycensus facilitates the integration of standardized Census attributes where applicable. Visualization and diagnostic tasks rely on ggplot2, patchwork, and scales, allowing for consistent exploratory data analysis and error assessment. Finally, broom supports tidy model output for interpretation, and readxl is used to import Excel-formatted documents that could not be reliably converted to CSV. Together.\n\n\n\n# Policy Problem & Research Question\n\n## Problem Statement\n\nPhiladelphia faces persistent, geographically concentrated eviction pressure that disproportionately affects low-income communities, particularly historically Black neighborhoods in North and West Philadelphia. Evictions destabilize families, increase homelessness risk, and strain municipal services including emergency shelter systems, legal aid, and social support networks. Despite the severity of this problem, city officials currently lack a reliable, predictive mechanism to anticipate spikes in eviction activity and pre-position prevention resources.\n\n## Stakeholders Affected\n\n- **Renters at risk**: Low-income households vulnerable to displacement\n- **Community-based organizations**: Nonprofits providing legal aid, mediation, and rental assistance\n- **Philadelphia Housing Authority**: Public housing and housing support programs\n- **Office of Homeless Services**: Emergency shelter and prevention coordination\n- **City Council & Policy Staff**: Resource allocation and program design\n\n## Decision Use Case\n\nA month-ahead forecast of eviction pressure enables city officials to:\n\n1. Anticipate demand surges for rental assistance, legal aid, and mediation services\n2. Allocate prevention resources equitably across neighborhoods before filings occur\n3. Intervene before households reach eviction, rather than responding after displacement\n\n\n\n# Data Overview and Data Imports\n\nThis code chunk imports all primary datasets used in the analysis, bringing together eviction records, demographic context, economic indicators, and measures of household financial vulnerability. The core eviction data are sourced from evictionlab.org . Multiple eviction tables are loaded to support different analytical needs, including raw filing counts (tract_filings), normalized filing rates (tract_filing_rate), and citywide temporal patterns relative to historical baselines (eviction_trends). These complementary formats allow the project to examine evictions at both the spatial (tract-level) and temporal (month-to-month) scales, which is critical for understanding changes in eviction activity.\n\nTo contextualize eviction behavior within broader economic and social conditions, the project incorporates several external data sources. Monthly unemployment rates and Consumer Price Index (CPI) data capture macroeconomic conditions that directly affect households’ ability to meet rent obligations. This data is sourced from the Bureau of Labor Statistics. The Urban Institute financial health dataset provides indicators of underlying financial vulnerability, such as debt burdens, housing cost stress, and labor market engagement. Additional datasets from the eviction lab describing neighborhood demographics, eviction hotspots, and deviations from historical filing baselines support exploratory analysis and feature engineering during later modeling stages. These datasets enable a transparent, multi-source approach to integrate diverse data sources in support of a policy-relevant predictive model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Changes in Claim Amount\nclaim_change <- read.csv(\"eviction_data/changes_claims.csv\")\n\n# Demographics\ndemographics <- read.csv(\"eviction_data/demographics.csv\")\n\n# Hotspots\nhotspots <- read.csv(\"eviction_data/eviction_hotspots.csv\")\n\n# Evictions Relative to Baseline\nevictions_baseline <- read.csv(\"eviction_data/filings_relative_baseline.csv\")\n\n# Tract Level Filings\ntract_filings <- read.csv(\"eviction_data/tract_level_filings.csv\")\n\n# Tract Level Filing Rate\ntract_filing_rate <- read.csv(\"eviction_data/tract_level_filing_rate.csv\")\n\n# Eviction Trends\neviction_trends <- read.csv(\"eviction_data/trends_eviction.csv\")\n\n# Monthly Unemployment Rates\nunemployment_monthly <- read_xlsx(\"eviction_data/unemployment_rate_montly.xlsx\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNew names:\n• `` -> `...2`\n• `` -> `...3`\n• `` -> `...4`\n• `` -> `...5`\n• `` -> `...6`\n• `` -> `...7`\n• `` -> `...8`\n• `` -> `...9`\n• `` -> `...10`\n• `` -> `...11`\n• `` -> `...12`\n• `` -> `...13`\n```\n\n\n:::\n\n```{.r .cell-code}\n# Consumer Price Index\nconsumer_price_index <- read_xlsx(\"eviction_data/consumer_price_index_monthly.xlsx\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNew names:\n• `` -> `...2`\n• `` -> `...3`\n• `` -> `...4`\n• `` -> `...5`\n• `` -> `...6`\n• `` -> `...7`\n• `` -> `...8`\n• `` -> `...9`\n• `` -> `...10`\n• `` -> `...11`\n• `` -> `...12`\n• `` -> `...13`\n• `` -> `...14`\n• `` -> `...15`\n• `` -> `...16`\n```\n\n\n:::\n\n```{.r .cell-code}\n#Financial Health Data\nfinancial_health <- read_xlsx(\"eviction_data/financial-health-of-residents-data.xlsx\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNew names:\n• `` -> `...2`\n• `` -> `...3`\n• `` -> `...4`\n• `` -> `...5`\n• `` -> `...6`\n• `` -> `...7`\n• `` -> `...8`\n• `` -> `...9`\n• `` -> `...10`\n• `` -> `...11`\n• `` -> `...12`\n• `` -> `...13`\n• `` -> `...14`\n• `` -> `...15`\n• `` -> `...16`\n• `` -> `...17`\n• `` -> `...18`\n```\n\n\n:::\n:::\n\n\n# Exploratory Data Analysis - Tract Fillings, and Predictors\n\nTo begin we examine tract filing data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Investigate the data set\n\nhead(tract_filings, 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           id month_date month_filings  month_rate month_rate_scale_max\n1  4.2101e+10 01/11/2024            11 0.012835473            0.1248843\n2  4.2101e+10 01/11/2024             8 0.006950478            0.1248843\n3  4.2101e+10 01/11/2024             5 0.008503401            0.1248843\n4  4.2101e+10 01/11/2024            51 0.030520646            0.1248843\n5  4.2101e+10 01/11/2024             9 0.007594937            0.1248843\n6  4.2101e+10 01/11/2024             3 0.013761468            0.1248843\n7  4.2101e+10 01/11/2024             6 0.005067568            0.1248843\n8  4.2101e+10 01/11/2024            37 0.038988409            0.1248843\n9  4.2101e+10 01/11/2024            24 0.028846154            0.1248843\n10 4.2101e+10 01/11/2024            11 0.011022044            0.1248843\n11 4.2101e+10 01/11/2024             7 0.005723630            0.1248843\n12 4.2101e+10 01/11/2024             9 0.014876033            0.1248843\n13 4.2101e+10 01/11/2024            11 0.009548611            0.1248843\n14 4.2101e+10 01/11/2024             2 0.001339585            0.1248843\n15 4.2101e+10 01/11/2024            16 0.014311270            0.1248843\n16 4.2101e+10 01/11/2024            18 0.012775018            0.1248843\n17 4.2101e+10 01/11/2024             6 0.005016722            0.1248843\n18 4.2101e+10 01/11/2024             1 0.001876173            0.1248843\n19 4.2101e+10 01/11/2024            12 0.018237082            0.1248843\n20 4.2101e+10 01/11/2024            10 0.006925208            0.1248843\n21 4.2101e+10 01/11/2024             5 0.006345178            0.1248843\n22 4.2101e+10 01/11/2024             2 0.001863933            0.1248843\n23 4.2101e+10 01/11/2024             3 0.003787879            0.1248843\n24 4.2101e+10 01/11/2024            11 0.008849558            0.1248843\n25 4.2101e+10 01/11/2024             7 0.025547445            0.1248843\n26 4.2101e+10 01/11/2024             5 0.005917160            0.1248843\n27 4.2101e+10 01/11/2024             3 0.003070624            0.1248843\n28 4.2101e+10 01/11/2024             8 0.011004127            0.1248843\n29 4.2101e+10 01/11/2024             3 0.004587156            0.1248843\n30 4.2101e+10 01/11/2024             1 0.001956947            0.1248843\n31 4.2101e+10 01/11/2024            14 0.016990291            0.1248843\n32 4.2101e+10 01/11/2024            18 0.025862069            0.1248843\n33 4.2101e+10 01/11/2024            14 0.032183908            0.1248843\n34 4.2101e+10 01/11/2024             2 0.006410256            0.1248843\n35 4.2101e+10 01/11/2024            22 0.036974790            0.1248843\n36 4.2101e+10 01/11/2024             7 0.012433393            0.1248843\n37 4.2101e+10 01/11/2024            21 0.016733068            0.1248843\n38 4.2101e+10 01/11/2024            18 0.022304833            0.1248843\n39 4.2101e+10 01/11/2024             6 0.007662835            0.1248843\n40 4.2101e+10 01/11/2024             4 0.007207207            0.1248843\n41 4.2101e+10 01/11/2024             1 0.001288660            0.1248843\n42 4.2101e+10 01/11/2024             2 0.001970443            0.1248843\n43 4.2101e+10 01/11/2024             3 0.003880983            0.1248843\n44 4.2101e+10 01/11/2024             3 0.005145798            0.1248843\n45 4.2101e+10 01/11/2024             5 0.008833922            0.1248843\n46 4.2101e+10 01/11/2024            25 0.030637255            0.1248843\n47 4.2101e+10 01/11/2024            43 0.064275037            0.1248843\n48 4.2101e+10 01/11/2024            69 0.046030687            0.1248843\n49 4.2101e+10 01/11/2024            56 0.053639847            0.1248843\n50 4.2101e+10 01/11/2024            25 0.028280543            0.1248843\n   month_diff pct_white  pct_black pct_hispanic\n1   0.6315789 0.7502917 0.03733956  0.075845974\n2   0.6428571 0.7801911 0.07819288  0.078192876\n3   1.0000000 0.3163265 0.00000000  0.224489796\n4   1.2380952 0.5188510 0.04727708  0.052663076\n5   0.4444444 0.5021097 0.25485232  0.033755274\n6   1.0000000 0.9128440 0.00000000  0.000000000\n7   0.7000000 0.6748311 0.06081081  0.016891892\n8   0.8941176 0.4868282 0.14963119  0.050579557\n9   1.6666667 0.6826923 0.08293269  0.049278846\n10  0.6857143 0.7785571 0.02304609  0.050100200\n11  1.2307692 0.3924775 0.05887163  0.080948487\n12  1.3333333 0.7504132 0.00000000  0.069421488\n13  0.7500000 0.6545139 0.03472222  0.072048611\n14  0.4615385 0.6945747 0.00000000  0.050904220\n15  1.2142857 0.7504472 0.01967800  0.057245081\n16  1.1875000 0.7537260 0.08161817  0.044712562\n17  1.0000000 0.6446488 0.07692308  0.040133779\n18  0.5000000 0.9249531 0.00000000  0.016885553\n19  1.5294118 0.9270517 0.02127660  0.031914894\n20  0.9166667 0.6821330 0.10595568  0.038088643\n21  0.9230769 0.7677665 0.05837563  0.015228426\n22  0.7500000 0.8462255 0.05684995  0.027027027\n23  2.0000000 0.7462121 0.02146465  0.157828283\n24  1.1428571 0.7272727 0.05390185  0.049074819\n25  0.9411765 0.5510949 0.35766423  0.000000000\n26  1.2000000 0.6071006 0.25562130  0.056804734\n27  0.5333333 0.5527124 0.36028659  0.015353122\n28  1.2857143 0.5997249 0.14305365  0.038514443\n29  0.5000000 0.8562691 0.09174312  0.000000000\n30  0.2666667 0.7534247 0.13894325  0.086105675\n31  1.1538462 0.7257282 0.14563107  0.009708738\n32  1.1515152 0.5775862 0.34339080  0.040229885\n33  0.8333333 0.2068966 0.69425287  0.011494253\n34  0.3750000 0.4679487 0.38782051  0.060897436\n35  1.0000000 0.4672269 0.42352941  0.013445378\n36  1.0666667 0.7353464 0.01776199  0.177619893\n37  1.2941176 0.6199203 0.18486056  0.075697211\n38  0.5671642 0.3308550 0.48946716  0.099132590\n39  0.6086957 0.5683269 0.07279693  0.204342273\n40  0.7142857 0.7747748 0.13333333  0.082882883\n41  0.4444444 0.4909794 0.01159794  0.295103093\n42  0.4285714 0.7517241 0.12807882  0.150738916\n43  1.0000000 0.8201811 0.02846054  0.119016818\n44  0.7272727 0.4322470 0.14236707  0.174957118\n45  0.8000000 0.5812721 0.30565371  0.070671378\n46  0.9122807 0.2132353 0.60416667  0.064950980\n47  1.2054795 0.1793722 0.72944694  0.065769806\n48  0.9333333 0.5150100 0.36691127  0.099399600\n49  0.9421488 0.1475096 0.83429119  0.000000000\n50  0.8125000 0.2692308 0.58597285  0.083710407\n```\n\n\n:::\n:::\n\n\nNext We import census geometry to join and visualize tract filing data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import Census Tract Geometry\noptions(tigris_use_cache = TRUE)\n\n# Import for Philadelphia \nphiladelphia_tracts <- tracts(state = \"PA\", county = \"Philadelphia\", year = 2022)\n\n# Look at Results\nplot(philadelphia_tracts$geometry)\n```\n\n::: {.cell-output-display}\n![](eviction_data_analysis_files/figure-html/Census Tracts-1.png){width=672}\n:::\n:::\n\n# Join Tracts to Filings\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make Sure Format Matches\nphiladelphia_tracts$GEOID <- as.character(philadelphia_tracts$GEOID)\ntract_filings$id <- as.character(tract_filings$id)\n\n# Join\nevictions_geo <- philadelphia_tracts %>%\n  left_join(tract_filings, by = c(\"GEOID\" = \"id\"))\n```\n:::\n\n\nHere a map is made of tract filings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(evictions_geo) +\n  geom_sf(aes(fill = month_rate), color = NA) +\n  scale_fill_viridis_c(option = \"magma\") +\n  labs(\n    title = \"Eviction Rate by Census Tract\",\n    fill = \"Eviction Rate\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](eviction_data_analysis_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nOTHER EDAS GO HERE\n\n\n#Hotspots\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(ggplot2)\nlibrary(readr)\nlibrary(dplyr)\nlibrary(sf)\nlibrary(ggplot2)\n\n# 1. Read CSV\nhotspots <- read_csv(\"hotspots/philadelphia_hotspots_media_report.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 75 Columns: 9\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (4): time_period, end_date, xplaintiff, xstreet_clean\ndbl (5): position, filings, top100, lat, lon\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Convert to sf object\nhotspots_sf <- st_as_sf(\n  hotspots,\n  coords = c(\"lon\", \"lat\"),\n  crs = 4326\n)\n# 1. Read tract boundary\ntracts <- st_read(\"border/Census_Blocks_2010.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Census_Blocks_2010' from data source \n  `D:\\pen\\MUSA5080PublicPolicyAnalytics\\portfolio-setup-Mayaano\\assignments\\final_project_analysis_process\\border\\Census_Blocks_2010.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 408 features and 27 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -75.28027 ymin: 39.86705 xmax: -74.95578 ymax: 40.13799\nGeodetic CRS:  NAD83\n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Reproject hotspots to match tracts CRS\nhotspots_sf <- st_transform(hotspots_sf, st_crs(tracts))\n\n# 3. Map tracts + hotspots\nggplot() +\n  geom_sf(data = tracts, fill = \"grey95\", color = \"white\") +\n  geom_sf(\n    data = hotspots_sf,\n    aes(size = filings),\n    alpha = 0.7\n  ) +\n  scale_size_continuous(name = \"Eviction filings\") +\n  labs(\n    title = \"Eviction Hotspots over Census Tracts\",\n    subtitle = \"Top 100 buildings in Philadelphia\",\n    caption = \"Source: Eviction Tracking System, ACS, Census tracts\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](eviction_data_analysis_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\nEviction filings exhibit marked geographic concentration in Philadelphia. North Philadelphia (40.05°N-40.15°N) shows the densest clustering with 100+ filings, reflecting historically disinvested, predominantly Black neighborhoods. West Philadelphia and South Philadelphia display secondary hotspots (50-75 filings), while Northeast suburbs show minimal activity. This stark contrast demonstrates housing instability is geographically concentrated among vulnerable populations. For predictive modeling, spatial clustering indicates temporal lag effects and racialized patterns reflecting structural inequality. The geographic specificity enables targeted prevention interventions in highest-need areas, though we acknowledge filings may reflect both tenant vulnerability and landlord enforcement variation.\n\n# trends\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](trends.png){fig-align='center' width=100px}\n:::\n:::\n\n\nDataset contains 72 monthly observations from January 2020 to December 2024 (5 years) with eviction filing counts, historical averages, and deviation metrics.\nKey Findings\nTemporal Trends: Eviction filings show clear recovery pattern post-2020. 2020-2021 experienced dramatic suppression (COVID-19 moratoriums), with filings dropping to near-zero in April-June 2020. Recovery accelerated from 2022 onwards, stabilizing around 1,000-1,200 filings monthly by 2023-2024.\nSeasonality: Weak seasonal pattern exists—January and August show slightly elevated filings (1.55× and 1.55× of average), while April-May show lower activity (0.20× and 0.16× of average 2020-2021 data). This reflects policy implementation timing.\nYear-over-Year Comparison: 2024 average (1,061 filings) closely mirrors 2023 (1,059 filings), indicating market stabilization post-recovery. 2025 preliminary data suggests continued stability with minor volatility.\nVolatility: Coefficient of variation decreased over time, showing market normalization after pandemic disruptions. Recent years exhibit more predictable patterns than 2020-2021 volatility.\nImplications\nData supports stable eviction environment with predictable monthly volumes suitable for forecasting models.\n\n# trends\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](price.png){fig-align='center' width=100px}\n:::\n:::\n\n\nhiladelphia Census Tracts: Geospatial Analysis\nThese choropleth maps visualize key socioeconomic indicators across Philadelphia's census tracts, revealing significant spatial disparities in poverty rates, unemployment, rent burden, and demographic composition. The darker regions indicate higher concentrations of economic vulnerability, with notable clustering in North and West Philadelphia tracts showing elevated poverty, unemployment, and rental cost burdens exceeding 30% of household income. Demographic analysis reveals stark residential segregation patterns, with distinct geographic concentrations of racial and ethnic populations. These spatial patterns align with historical inequities in housing access, economic opportunity, and community investment, providing critical context for understanding eviction vulnerability and housing instability across the city.\n\n\n# Choice of Dependent Variable\nThe dependent variable in this analysis is percentage_diff, which measures the monthly deviation of eviction filings from a long-term baseline. Rather than modeling raw eviction counts, this transformation captures relative change in eviction activity, allowing the analysis to focus on fluctuations around typical levels. This is particularly important in Philadelphia and other large cities, where eviction volumes vary seasonally and were disrupted by major economic disruptions such as the COVID-19. By using a normalized measure, the model isolates meaningful economic variation instead of conflating structural patterns with short-term dynamics.\n\nFrom an economic perspective, percentage_diff is better suited than raw counts because it reflects marginal responses to changing conditions, which is the core interest of applied economic analysis. Labor market shocks, inflation, and household financial stress do not directly determine how many eviction cases exist in absolute terms; instead, they influence whether eviction pressure rises or falls relative to normal conditions. Modeling deviations from a baseline aligns the dependent variable with economic theory on cyclical stress, making the results more applicable for policy analysis and more appropriate for regression-based inference.\n\n\n# Data Cleaning\n\nThis restructures the economic and financial datasets to make them analytically compatible with monthly eviction data. The Urban Institute financial health dataset comes in a report-style format rather than a machine-ready table, with multiple header and metadata rows embedded in the file. To correct this, we make row 4 the column headers, replace missing or blank column names with placeholders to allow selection and filtering, remove non-data rows, and isolate the row corresponding to Philadelphia. All remaining variables are then changed to numeric format, ensuring that these indicators—such as debt burden, housing cost stress, and labor force participation—can be used in regression-based modeling. These steps are necessary because model estimation and validation require numeric, consistently formatted inputs.\n\nThe Consumer Price Index and unemployment datasets require a different but similar cleaning approach because both are come in wide, month-column formats with extensive metadata. We identify the true header rows, remove non-data rows, convert month columns to numeric values, and reshape each dataset into a long format with one row per year–month observation. These transformations are important because the eviction outcome is measured monthly, and predictive modeling requires all time-varying variables to align. A month lookup table is made to convert month names into numeric values, ensuring consistent joins across datasets. The cleaned CPI and unemployment data are then merged into the monthly eviction trend dataset using year and month keys.\n\nFinally, the cleaned Urban Institute financial indicators are appended to the eviction trends dataset using a dummy join, reflecting the fact that these measures describe baseline household financial vulnerability rather than month-specific disruptions. Lagged versions of key eviction outcome variables are then constructed to capture temporal lag in eviction activity, a main feature of eviction processes given legal delays and accumulated financial stress. These lag variables enable the model to distinguish between short-term economic fluctuations and ongoing eviction patterns.\n\n***Note: Thus far we had not had any issues with the Urban Institute Data, later will reveal why it is more difficult for this analysis***\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data Cleaning\n\n\n# Clean Financial Health Data\nfinancial_health_clean <- financial_health\n\n# Use row 4 as header\nnames(financial_health_clean) <- as.character(unlist(financial_health_clean[4, ]))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The `value` argument of `names<-()` can't be empty as of tibble 3.0.0.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Replace blank/NA column names with placeholders\nbad_name_index <- which(is.na(names(financial_health_clean)) | names(financial_health_clean) == \"\")\nif (length(bad_name_index) > 0) {\n  names(financial_health_clean)[bad_name_index] <- paste0(\"col_\", seq_along(bad_name_index))\n}\n\n# Remove metadata rows 1–4, keep Philadelphia only\nfinancial_health_clean <- financial_health_clean[-(1:4), ] %>%\n  filter(City == \"Philadelphia, PA\")\n\n# Convert all but City to numeric\nfinancial_health_numeric_columns <- setdiff(names(financial_health_clean), \"City\")\nfinancial_health_clean[financial_health_numeric_columns] <-\n  lapply(financial_health_clean[financial_health_numeric_columns], as.numeric)\n\n\n\n# Clean CPI Data\ncpi_wide <- consumer_price_index\n\n# Real header is row 11\nnames(cpi_wide) <- as.character(unlist(cpi_wide[11, ]))\ncpi_wide <- cpi_wide[-(1:11), ]\n\ncpi_wide$Year <- as.integer(as.numeric(cpi_wide$Year))\n\ncpi_month_names <- c(\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\",\n                     \"Jul\",\"Aug\",\"Sep\",\"Oct\",\"Nov\",\"Dec\")\n\n# Convert month columns to numeric\nfor (col in cpi_month_names) {\n  if (col %in% names(cpi_wide)) {\n    cpi_wide[[col]] <- as.numeric(cpi_wide[[col]])\n  }\n}\n\n# Month lookup table\nmonth_lookup <- data.frame(\n  month_name = cpi_month_names,\n  month = 1:12\n)\n\n# Convert CPI to long format\ncpi_long <- cpi_wide %>%\n  select(Year, all_of(cpi_month_names)) %>%\n  pivot_longer(cols = all_of(cpi_month_names),\n               names_to = \"month_name\",\n               values_to = \"cpi\") %>%\n  filter(!is.na(cpi)) %>%\n  left_join(month_lookup, by = \"month_name\") %>%\n  rename(year = Year)\n\n\n\n# Clean Unemployment Data\nunemployment_wide <- unemployment_monthly\n\n# Row 10 is the real header\nnames(unemployment_wide) <- as.character(unlist(unemployment_wide[10, ]))\nunemployment_wide <- unemployment_wide[-(1:10), ]\n\nunemployment_wide$Year <- as.integer(as.numeric(unemployment_wide$Year))\n\nunemployment_month_names <- c(\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\",\n                              \"Jul\",\"Aug\",\"Sep\",\"Oct\",\"Nov\",\"Dec\")\n\n# Convert month columns to numeric\nfor (col in unemployment_month_names) {\n  if (col %in% names(unemployment_wide)) {\n    unemployment_wide[[col]] <- as.numeric(unemployment_wide[[col]])\n  }\n}\n\n# Convert unemployment data to long format\nunemployment_long <- unemployment_wide %>%\n  select(Year, all_of(unemployment_month_names)) %>%\n  pivot_longer(cols = all_of(unemployment_month_names),\n               names_to = \"month_name\",\n               values_to = \"unemployment_rate\") %>%\n  filter(!is.na(unemployment_rate)) %>%\n  left_join(month_lookup, by = \"month_name\") %>%\n  rename(year = Year)\n\n\n\n# Clean Monthly Eviction Trend Data\n# Parse month and year\neviction_trends_clean <- eviction_trends %>%\n  mutate(\n    month_num = as.integer(substr(month, 1, 2)),\n    year      = as.integer(substr(month, 4, 7)),\n    month_date = paste0(year, \"-\", month_num, \"-01\")\n  )\n\n# Merge with unemployment and CPI\neviction_trends_merged <- eviction_trends_clean %>%\n  left_join(unemployment_long,\n            by = c(\"year\" = \"year\", \"month_num\" = \"month\")) %>%\n  left_join(cpi_long,\n            by = c(\"year\" = \"year\", \"month_num\" = \"month\"))\n\n# Attach Urban Institute financial variables\neviction_trends_merged <- eviction_trends_merged %>%\n  mutate(dummy = 1) %>%\n  left_join(financial_health_clean %>% mutate(dummy = 1), by = \"dummy\") %>%\n  select(-dummy)\n\n# Add lag variables\neviction_trends_final <- eviction_trends_merged %>%\n  arrange(year, month_num) %>%\n  mutate(\n    l1_filings = lag(month_filings, 1),\n    l1_percentage_diff = lag(percentage_diff, 1)\n  )\n```\n:::\n\n\n\n# Assess if Data Cleaning Worked\n\nHere we check to see if our new data sets are how we intended them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check Financial Health\ncat(\"Financial Health Clean\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFinancial Health Clean\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(str(financial_health_clean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [1 × 18] (S3: tbl_df/tbl/data.frame)\n $ City                                 : chr \"Philadelphia, PA\"\n $ Overall                              : num 628\n $ White areas                          : num 703\n $ Nonwhite areas                       : num 571\n $ col_1                                : num NA\n $ % with                               : num 0.466\n $ Median amount among those with       : num 1476\n $ col_2                                : num NA\n $ % with home foreclosure              : num 0.00435\n $ % housing-cost burdened, low-income  : num 0.68\n $ % unbanked, metro area               : num 0.041\n $ % with health insurance coverage     : num 0.857\n $ % received EITC, low-income          : num 0.415\n $ Unemployment rate                    : num 0.109\n $ Labor force participation rate       : num 0.604\n $ % below 200% of federal poverty level: num 0.46\n $ % population change, 2000–15         : num 0.0329\n $ Gini index of income inequality      : num 0.505\nNULL\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(head(financial_health_clean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 18\n  City             Overall `White areas` `Nonwhite areas` col_1 `% with`\n  <chr>              <dbl>         <dbl>            <dbl> <dbl>    <dbl>\n1 Philadelphia, PA     628           703              571    NA    0.466\n# ℹ 12 more variables: `Median amount among those with` <dbl>, col_2 <dbl>,\n#   `% with home foreclosure` <dbl>,\n#   `% housing-cost burdened, low-income` <dbl>,\n#   `% unbanked, metro area` <dbl>, `% with health insurance coverage` <dbl>,\n#   `% received EITC, low-income` <dbl>, `Unemployment rate` <dbl>,\n#   `Labor force participation rate` <dbl>,\n#   `% below 200% of federal poverty level` <dbl>, …\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check CPI Long Format\ncat(\"CPI Long Format\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCPI Long Format\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(str(cpi_long))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [64 × 4] (S3: tbl_df/tbl/data.frame)\n $ year      : int [1:64] 2015 2015 2015 2015 2015 2015 2016 2016 2016 2016 ...\n $ month_name: chr [1:64] \"Feb\" \"Apr\" \"Jun\" \"Aug\" ...\n $ cpi       : num [1:64] 242 244 246 245 244 ...\n $ month     : int [1:64] 2 4 6 8 10 12 2 4 6 8 ...\nNULL\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(head(cpi_long))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n   year month_name   cpi month\n  <int> <chr>      <dbl> <int>\n1  2015 Feb         242.     2\n2  2015 Apr         244.     4\n3  2015 Jun         246.     6\n4  2015 Aug         245.     8\n5  2015 Oct         244.    10\n6  2015 Dec         242.    12\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check Unemployment Long Format\ncat(\"Unemployment Long Format\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnemployment Long Format\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(str(unemployment_long))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [128 × 4] (S3: tbl_df/tbl/data.frame)\n $ year             : int [1:128] 2015 2015 2015 2015 2015 2015 2015 2015 2015 2015 ...\n $ month_name       : chr [1:128] \"Jan\" \"Feb\" \"Mar\" \"Apr\" ...\n $ unemployment_rate: num [1:128] 6.2 6 5.7 5.2 5.7 5.7 6.1 5.7 5.1 4.9 ...\n $ month            : int [1:128] 1 2 3 4 5 6 7 8 9 10 ...\nNULL\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(head(unemployment_long))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n   year month_name unemployment_rate month\n  <int> <chr>                  <dbl> <int>\n1  2015 Jan                      6.2     1\n2  2015 Feb                      6       2\n3  2015 Mar                      5.7     3\n4  2015 Apr                      5.2     4\n5  2015 May                      5.7     5\n6  2015 Jun                      5.7     6\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check Eviction Data\ncat(\"Eviction Trends Final After Macro UI Merge & Lag\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEviction Trends Final After Macro UI Merge & Lag\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(str(eviction_trends_final))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t70 obs. of  32 variables:\n $ month                                : chr  \"01/2020\" \"02/2020\" \"03/2020\" \"04/2020\" ...\n $ month_last_day                       : logi  NA NA NA NA NA NA ...\n $ month_filings                        : int  2015 1720 813 0 0 0 198 176 701 792 ...\n $ avg_filings                          : num  1294 1194 1142 925 1065 ...\n $ percentage_diff                      : num  1.557 1.441 0.712 0 0 ...\n $ month_num                            : int  1 2 3 4 5 6 7 8 9 10 ...\n $ year                                 : int  2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 ...\n $ month_date                           : chr  \"2020-1-01\" \"2020-2-01\" \"2020-3-01\" \"2020-4-01\" ...\n $ month_name.x                         : chr  \"Jan\" \"Feb\" \"Mar\" \"Apr\" ...\n $ unemployment_rate                    : num  4.3 4.2 4.9 13.9 13.4 12.9 12 10.4 8.6 7.4 ...\n $ month_name.y                         : chr  NA \"Feb\" NA \"Apr\" ...\n $ cpi                                  : num  NA 260 NA 256 NA ...\n $ City                                 : chr  \"Philadelphia, PA\" \"Philadelphia, PA\" \"Philadelphia, PA\" \"Philadelphia, PA\" ...\n $ Overall                              : num  628 628 628 628 628 628 628 628 628 628 ...\n $ White areas                          : num  703 703 703 703 703 703 703 703 703 703 ...\n $ Nonwhite areas                       : num  571 571 571 571 571 571 571 571 571 571 ...\n $ col_1                                : num  NA NA NA NA NA NA NA NA NA NA ...\n $ % with                               : num  0.466 0.466 0.466 0.466 0.466 ...\n $ Median amount among those with       : num  1476 1476 1476 1476 1476 ...\n $ col_2                                : num  NA NA NA NA NA NA NA NA NA NA ...\n $ % with home foreclosure              : num  0.00435 0.00435 0.00435 0.00435 0.00435 ...\n $ % housing-cost burdened, low-income  : num  0.68 0.68 0.68 0.68 0.68 ...\n $ % unbanked, metro area               : num  0.041 0.041 0.041 0.041 0.041 ...\n $ % with health insurance coverage     : num  0.857 0.857 0.857 0.857 0.857 ...\n $ % received EITC, low-income          : num  0.415 0.415 0.415 0.415 0.415 ...\n $ Unemployment rate                    : num  0.109 0.109 0.109 0.109 0.109 ...\n $ Labor force participation rate       : num  0.604 0.604 0.604 0.604 0.604 ...\n $ % below 200% of federal poverty level: num  0.46 0.46 0.46 0.46 0.46 ...\n $ % population change, 2000–15         : num  0.0329 0.0329 0.0329 0.0329 0.0329 ...\n $ Gini index of income inequality      : num  0.505 0.505 0.505 0.505 0.505 ...\n $ l1_filings                           : int  NA 2015 1720 813 0 0 0 198 176 701 ...\n $ l1_percentage_diff                   : num  NA 1.557 1.441 0.712 0 ...\nNULL\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(head(eviction_trends_final))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    month month_last_day month_filings avg_filings percentage_diff month_num\n1 01/2020             NA          2015      1294.5       1.5565856         1\n2 02/2020             NA          1720      1193.5       1.4411395         2\n3 03/2020             NA           813      1142.5       0.7115974         3\n4 04/2020             NA             0       925.0       0.0000000         4\n5 05/2020             NA             0      1065.0       0.0000000         5\n6 06/2020             NA             0      1032.0       0.0000000         6\n  year month_date month_name.x unemployment_rate month_name.y     cpi\n1 2020  2020-1-01          Jan               4.3         <NA>      NA\n2 2020  2020-2-01          Feb               4.2          Feb 259.694\n3 2020  2020-3-01          Mar               4.9         <NA>      NA\n4 2020  2020-4-01          Apr              13.9          Apr 256.353\n5 2020  2020-5-01          May              13.4         <NA>      NA\n6 2020  2020-6-01          Jun              12.9          Jun 257.983\n              City Overall White areas Nonwhite areas col_1    % with\n1 Philadelphia, PA     628         703            571    NA 0.4660742\n2 Philadelphia, PA     628         703            571    NA 0.4660742\n3 Philadelphia, PA     628         703            571    NA 0.4660742\n4 Philadelphia, PA     628         703            571    NA 0.4660742\n5 Philadelphia, PA     628         703            571    NA 0.4660742\n6 Philadelphia, PA     628         703            571    NA 0.4660742\n  Median amount among those with col_2 % with home foreclosure\n1                           1476    NA             0.004345603\n2                           1476    NA             0.004345603\n3                           1476    NA             0.004345603\n4                           1476    NA             0.004345603\n5                           1476    NA             0.004345603\n6                           1476    NA             0.004345603\n  % housing-cost burdened, low-income % unbanked, metro area\n1                           0.6803305                  0.041\n2                           0.6803305                  0.041\n3                           0.6803305                  0.041\n4                           0.6803305                  0.041\n5                           0.6803305                  0.041\n6                           0.6803305                  0.041\n  % with health insurance coverage % received EITC, low-income\n1                        0.8566335                   0.4151677\n2                        0.8566335                   0.4151677\n3                        0.8566335                   0.4151677\n4                        0.8566335                   0.4151677\n5                        0.8566335                   0.4151677\n6                        0.8566335                   0.4151677\n  Unemployment rate Labor force participation rate\n1         0.1093104                      0.6044449\n2         0.1093104                      0.6044449\n3         0.1093104                      0.6044449\n4         0.1093104                      0.6044449\n5         0.1093104                      0.6044449\n6         0.1093104                      0.6044449\n  % below 200% of federal poverty level % population change, 2000–15\n1                             0.4603734                   0.03287668\n2                             0.4603734                   0.03287668\n3                             0.4603734                   0.03287668\n4                             0.4603734                   0.03287668\n5                             0.4603734                   0.03287668\n6                             0.4603734                   0.03287668\n  Gini index of income inequality l1_filings l1_percentage_diff\n1                          0.5049         NA                 NA\n2                          0.5049       2015          1.5565856\n3                          0.5049       1720          1.4411395\n4                          0.5049        813          0.7115974\n5                          0.5049          0          0.0000000\n6                          0.5049          0          0.0000000\n```\n\n\n:::\n:::\n\n# Creating the Model\n\n\n# Step 1: Creating the Model Data Set\n\nThis step constructs the modeling dataset used for regression analysis. Each row in the resulting dataset represents a single month, with aligned economic, financial, and temporal predictors. The dependent variable, percentage_diff, measures how eviction filings in a given month deviate from a historical average, making it a continuous outcome well suited for linear regression. Predictor variables include lagged eviction activity (l1_percentage_diff) to capture temporal lag, macroeconomic indicators (unemployment_rate, cpi) to reflect short-term economic conditions, and Urban Institute financial health indicators that quantify underlying household vulnerability. Observations with missing outcome values are removed to ensure valid model estimation and consistent sample sizes across all predictors.\n\nOrdinary Least Squares (OLS) regression is an appropriate and intentional modeling choice for this dataset given both the structure of the outcome and the nature of the predictors. The dependent variable is continuous and approximately symmetric around its mean, rather than binary or integer-count based, ruling out logistic and Poisson-style models. The predictors are a mix of continuous economic measures and proportion-based indicators, all of which naturally conform to the linear framework assumed by OLS. OLS also offers transparent coefficient interpretation, allowing each variable’s association with eviction deviations to be directly assessed, an important requirement for a policy-focused project. Additionally, OLS performs well with moderate sample sizes and does not impose unnecessary distribution assumptions beyond linearity and conditional independence. This makes OLS regression suitable for evaluating how economic disruptions and financial vulnerability jointly shape month-to-month eviction dynamics.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare modeling dataset \n\nmodel_df <- eviction_trends_final %>%\n  select(\n    year, month_num,\n    month_filings,\n    percentage_diff,\n    l1_percentage_diff,\n    unemployment_rate,\n    cpi,\n    Overall,\n    `White areas`,\n    `Nonwhite areas`,\n    `% with`,\n    `Median amount among those with`,\n    `% housing-cost burdened, low-income`,\n    `% with home foreclosure`,\n    `% unbanked, metro area`,\n    `% received EITC, low-income`,\n    `Labor force participation rate`,\n    `% below 200% of federal poverty level`,\n    `Gini index of income inequality`\n  ) %>%\n  filter(!is.na(percentage_diff))\n```\n:::\n\n\n\n# Step 2: Fit Regression Model\n\nHere the model is fit with the predictors.\n\n# Important Finding\n\nThe regression results revealed an important characteristic of the Urban Institute (UI) financial health variables. Although they are meaningful, they do not vary within the temporal unit used for modeling. Because remain constant across all rows in the monthly dataset, these variables are perfectly collinear with the model intercept and are therefore dropped during estimation due to singularities. This behavior is expected under Ordinary Least Squares. More time would be needed to fully assess and correct this issue or to source new data with the same measures. Despite not receiving individual coefficient estimates, the UI variables still play an important conceptual role in the analysis. They provide context for the economic environment in which evictions occur, anchoring short-term fluctuations in broader measures of financial vulnerability such as housing cost burden, foreclosure prevalence, and income inequality. Rather than being interpreted as predictors, these variables help frame the limits of month-to-month responsiveness by describing the underlying baseline risk faced by households in Philadelphia.\n\n## Why Predict Percentage Diff? Why OLS?\n\n### Choice of Dependent Variable\n\nSeveral outcome variables were considered:\n- Raw filing counts (absolute numbers)\n- Filing rates (filings per capita)\n- Binary spike indicators (above/below threshold)\n\nWe selected `percentage_diff` (monthly deviation from historical baseline) because:\n\n1. **Removes seasonality**: Isolates economic stress changes from structural seasonal patterns\n2. **Continuous & symmetric**: Produces normally distributed outcomes suitable for OLS regression\n3. **Policy interpretability**: Allows decision-makers to compare current risk to typical conditions\n4. **Comparable across time**: Baseline adjustment ensures year-to-year comparisons are meaningful\n\n### Why OLS is Appropriate\n\nOLS regression is the appropriate model because:\n\n1. **Continuous outcome**: `percentage_diff` is a continuous, unbounded variable (not count, not binary)\n2. **Macroeconomic predictors**: Our features (unemployment, CPI, financial vulnerability) are standard in linear economic models\n3. **Interpretability over prediction**: Policy use requires transparent coefficient estimates, not black-box predictions\n4. **Sufficient sample size**: 72 months of observations supports reliable OLS estimation\n\nAlternative models were rejected:\n- Logistic/probit: Not suitable for continuous percentage outcomes\n- Poisson/negative binomial: Designed for count data, not percentage deviations\n- Machine learning (random forest, neural nets): Sacrifices interpretability needed for policy briefings\n\n## Feature Engineering Strategy\n\n### Features Implemented\n\n1. **Lagged eviction pressure** (`l1_percentage_diff`): 1-month lag captures procedural delays in eviction filings and accumulation of financial strain across months\n\n2. **Macroeconomic indicators** (`unemployment_rate`, `cpi`): Month-aligned predictors of household financial stress and purchasing power\n\n3. **Household financial vulnerability** (Urban Institute indicators):\n   - `% housing-cost burdened, low-income`: Direct measure of rent burden\n   - `% with home foreclosure`: Proxy for credit stress\n   - `% unbanked, metro area`: Financial system exclusion\n   - `% received EITC, low-income`: Indicator of low-income status\n   - `Labor force participation rate`: Employment access\n   - `% below 200% of federal poverty level`: Poverty concentration\n   - `Gini index of income inequality`: Income distribution stress\n\n4. **Claim amount** (`Median amount among those with`): Direct measure of eviction filing severity\n\n### Features Tested but Excluded\n\nThe following feature engineering approaches were explored but ultimately excluded:\n\n1. **Spatial lags** (adjacency-weighted filing pressure from neighboring tracts): High multicollinearity with baseline unemployment; excluded to preserve model interpretability\n2. **Interaction terms** (unemployment × financial burden): Overfitting concerns with limited sample size (n=72); would require out-of-sample validation\n3. **K-means neighborhood clusters**: Redundant with macroeconomic controls; added complexity without predictive gain\n4. **Seasonality dummies** (month fixed effects): Already removed by percentage_diff baseline adjustment\n5. **ARIMA-style autoregressive terms beyond lag-1**: Temporal autocorrelation was minimal post-lag inclusion\n\n### Justification\n\nThe final feature set balances **model parsimony** (avoid overfitting with 72 observations) with **policy relevance** (interpretable economic mechanisms). Future work should explore spatial clustering and interaction effects with larger datasets or longer time series.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\neviction_model <- lm(\n  percentage_diff ~ \n    l1_percentage_diff +\n    unemployment_rate +\n    cpi +\n    `Median amount among those with` +\n    `% housing-cost burdened, low-income` +\n    `% with home foreclosure` +\n    `% unbanked, metro area` +\n    `% received EITC, low-income` +\n    `Labor force participation rate` +\n    `% below 200% of federal poverty level` +\n    `Gini index of income inequality`,\n  data = model_df\n)\n\nsummary(eviction_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = percentage_diff ~ l1_percentage_diff + unemployment_rate + \n    cpi + `Median amount among those with` + `% housing-cost burdened, low-income` + \n    `% with home foreclosure` + `% unbanked, metro area` + `% received EITC, low-income` + \n    `Labor force participation rate` + `% below 200% of federal poverty level` + \n    `Gini index of income inequality`, data = model_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.39521 -0.06102 -0.00346  0.09482  0.57471 \n\nCoefficients: (8 not defined because of singularities)\n                                          Estimate Std. Error t value Pr(>|t|)\n(Intercept)                              0.5103766  0.6122573   0.834 0.411096\nl1_percentage_diff                       0.5408035  0.1254763   4.310 0.000162\nunemployment_rate                       -0.0663023  0.0192283  -3.448 0.001694\ncpi                                      0.0006943  0.0019027   0.365 0.717740\n`Median amount among those with`                NA         NA      NA       NA\n`% housing-cost burdened, low-income`           NA         NA      NA       NA\n`% with home foreclosure`                       NA         NA      NA       NA\n`% unbanked, metro area`                        NA         NA      NA       NA\n`% received EITC, low-income`                   NA         NA      NA       NA\n`Labor force participation rate`                NA         NA      NA       NA\n`% below 200% of federal poverty level`         NA         NA      NA       NA\n`Gini index of income inequality`               NA         NA      NA       NA\n                                           \n(Intercept)                                \nl1_percentage_diff                      ***\nunemployment_rate                       ** \ncpi                                        \n`Median amount among those with`           \n`% housing-cost burdened, low-income`      \n`% with home foreclosure`                  \n`% unbanked, metro area`                   \n`% received EITC, low-income`              \n`Labor force participation rate`           \n`% below 200% of federal poverty level`    \n`Gini index of income inequality`          \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1821 on 30 degrees of freedom\n  (因为不存在，36个观察量被删除了)\nMultiple R-squared:  0.7975,\tAdjusted R-squared:  0.7773 \nF-statistic: 39.39 on 3 and 30 DF,  p-value: 1.59e-10\n```\n\n\n:::\n:::\n\n\n\n# Calculating Errors - Root Mean Squared Error and Mean Average Error - This evaluates in sample error\n\n# Model Validation and Error Analysis\n\nIn-sample prediction error metrics were performed because the model includes lagged outcomes and economic predictors that are not observed for all periods, the regression was estimated using complete cases only. Validation was therefore first conducted on the same set of observations used in model estimation to ensure consistency between predicted and observed outcomes. Fitted values and residuals were extracted directly from the regression object to avoid misalignment caused by missing values.\n\nTwo standard error metrics were used to summarize model accuracy: Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE). MAE provides a measure of average deviation between predicted and observed eviction pressure, while RMSE penalizes larger errors more heavily and highlights sensitivity to extreme under- or over-prediction. Together, these metrics provide a concise assessment of model fit and establish a baseline level of predictive performance prior to out-of-sample validation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model Validation: RMSE and MAE\n\n# Extract the data actually used by the model because of UI data issues\nmodel_used <- eviction_model$model\n\n# Extract fitted values and residuals \npredicted <- eviction_model$fitted.values\nresiduals <- eviction_model$residuals\n\n# Compute MAE\nmae <- mean(abs(residuals))\n\n# Compute RMSE\nrmse <- sqrt(mean(residuals^2))\n\n# Output results\ncat(\"Model Performance Metrics:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel Performance Metrics:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"MAE  =\", round(mae, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMAE  = 0.1225 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"RMSE =\", round(rmse, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRMSE = 0.1711 \n```\n\n\n:::\n:::\n\n\n# Test Train Split Validation - this is our control for out of sample validation\n\n# Step 1 - Create Train and Test Splits\n\nThis step implements a time-based train–test split to evaluate the model’s out-of-sample predictive performance. Observations are first ordered chronologically using numeric year and month variables. The dataset is then divided such that all observations prior to 2023 are used for model training, while observations from 2023 onward are reserved for testing. This corresponds to using approximately 75–80% of the available time series for training and the remaining 20–25% for out-of-sample evaluation, depending on the exact temporal coverage of the dataset. Unlike random splits, this approach mirrors real-world forecasting conditions by ensuring the model is evaluated only on future observations it has not seen during estimation.\n\nThis time-based split is intentionally chosen because the outcome of interest, (monthly changes in eviction activity) is inherently temporal. Randomly assigning observations to training and testing would risk temporal leakage, where the model indirectly learns from future data points. By training on earlier years and testing on later ones, this validation strategy provides a more realistic assessment of how well the model generalizes to new economic conditions. After splitting, complete-case filtering is applied consistently to both training and test sets to ensure the same variables are available in each, preventing estimation or prediction errors caused by missing values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Train–Test Split\n\n# Make numeric time variables\nmodel_df_tt <- model_df %>%\n  mutate(\n    year_num  = as.integer(year),\n    month_num = if (\"month_num\" %in% names(.)) month_num else as.integer(substr(month, 1, 2))\n  ) %>%\n  arrange(year_num, month_num)\n\n# Train–test split by time\ntrain_df <- model_df_tt %>% filter(year_num < 2023)\ntest_df  <- model_df_tt %>% filter(year_num >= 2023)\n\n# Variables used in the model\nmodel_vars <- c(\n  \"percentage_diff\",\n  \"l1_percentage_diff\",\n  \"unemployment_rate\",\n  \"cpi\",\n  \"Median amount among those with\",\n  \"% housing-cost burdened, low-income\",\n  \"% with home foreclosure\",\n  \"% unbanked, metro area\",\n  \"% received EITC, low-income\",\n  \"Labor force participation rate\",\n  \"% below 200% of federal poverty level\",\n  \"Gini index of income inequality\"\n)\n\n# Keep only complete cases\ntrain_df_clean <- train_df %>%\n  filter(if_all(all_of(model_vars), ~ !is.na(.)))\n\ntest_df_clean <- test_df %>%\n  filter(if_all(all_of(model_vars), ~ !is.na(.)))\n```\n:::\n\n\n\n# Step 2 - Fit Model on Training Data\n\nWe now fit the new split data on a model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Model on Training Data\n\neviction_model_train <- lm(\n  percentage_diff ~ \n    l1_percentage_diff +\n    unemployment_rate +\n    cpi +\n    `Median amount among those with` +\n    `% housing-cost burdened, low-income` +\n    `% with home foreclosure` +\n    `% unbanked, metro area` +\n    `% received EITC, low-income` +\n    `Labor force participation rate` +\n    `% below 200% of federal poverty level` +\n    `Gini index of income inequality`,\n  data = train_df_clean\n)\n```\n:::\n\n\n# Step 3 - Predict on Test Data\n\nThis step evaluates the predictive accuracy of the trained eviction model using the test dataset, which contains observations not used during model estimation. The model is applied to the test data to generate predicted values of monthly eviction changes, and these predictions are then compared to the observed outcomes. The differences between predicted and actual values (residuals) quantify how far the model’s forecasts deviate from reality when applied out of sample.\n\nTo summarize prediction error, we calculate Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE). MAE captures the average size of prediction mistakes, while RMSE places greater weight on larger errors, highlighting periods where the model performs particularly poorly. Reporting both metrics provides a robust assessment of out-of-sample performance and demonstrates that the model is not only statistically meaningful in-sample but also useful for forecasting future eviction trends.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Out-of-Sample Validation - Test Set\n\n# Predict on test set\ntest_predictions <- predict(\n  eviction_model_train,\n  newdata = test_df_clean\n)\n\n# Residuals\ntest_residuals <- test_df_clean$percentage_diff - test_predictions\n\n# MAE\nmae_test <- mean(abs(test_residuals))\n\n# RMSE\nrmse_test <- sqrt(mean(test_residuals^2))\n\n# Output\ncat(\"Out-of-Sample Model Performance:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOut-of-Sample Model Performance:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"MAE  =\", round(mae_test, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMAE  = 0.1532 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"RMSE =\", round(rmse_test, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRMSE = 0.1833 \n```\n\n\n:::\n:::\n\n\n\n# Comparison of in-sample and out-of-sample Errors\n\nHere a new data frame is created to chart the difference between the in-sample, and out-of-sample error analyses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare error data for comparison\n\n# In-sample errors\nin_sample_errors <- data.frame(\n  residual = eviction_model$residuals,\n  sample_type = \"In-sample\"\n)\n\n# Out-of-sample errors\nout_sample_errors <- data.frame(\n  residual = test_residuals,\n  sample_type = \"Out-of-sample\"\n)\n\n# Combine\nerror_compare_df <- rbind(in_sample_errors, out_sample_errors)\n\n# Plot\nggplot(error_compare_df, aes(x = residual, fill = sample_type)) +\n  geom_histogram(\n    alpha = 0.6,\n    bins = 30,\n    position = \"identity\"\n  ) +\n  facet_wrap(~ sample_type, scales = \"free_y\") +\n  labs(\n    title = \"Comparison of Prediction Errors\",\n    subtitle = \"In-sample vs Out-of-sample Residual Distributions\",\n    x = \"Prediction Error (Residual)\",\n    y = \"Count\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](eviction_data_analysis_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(spdep)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n载入需要的程序包：spData\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nTo access larger datasets in this package, install the spDataLarge\npackage with: `install.packages('spDataLarge',\nrepos='https://nowosad.github.io/drat/', type='source')`\n```\n\n\n:::\n\n```{.r .cell-code}\n# Prepare spatial neighbors from evictions_geo\nnb <- poly2nb(evictions_geo, queen = TRUE)\nlw <- nb2listw(nb, style = \"W\", zero.policy = TRUE)\n\n# Get residuals from model\nresiduals_vec <- eviction_model$residuals\n\n# Add residuals to evictions_geo\nevictions_geo$model_residual <- NA\nevictions_geo$model_residual[1:length(residuals_vec)] <- residuals_vec\n\n# Moran's I test with zero.policy = TRUE\nmoran_result <- moran.test(evictions_geo$model_residual, lw, zero.policy = TRUE, na.action = na.omit)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in subset.nb(x = nb, subset = subset): subsetting caused increase in\nsubgraph count\n```\n\n\n:::\n\n```{.r .cell-code}\n# Print results\ncat(\"Moran's I Test on Model Residuals\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMoran's I Test on Model Residuals\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"===================================\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n===================================\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Moran's I statistic:\", round(moran_result$statistic, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMoran's I statistic: -0.9178 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P-value:\", round(moran_result$p.value, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP-value: 0.8206 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Expected I (under null):\", round(moran_result$estimate[2], 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExpected I (under null): -0.0476 \n```\n\n\n:::\n:::\n\n### Moran's I Test Results\n\nThe Moran's I test on model residuals yielded:\n\n- **Moran's I statistic**: -0.9178\n- **P-value**: 0.8206\n- **Expected I (under null hypothesis)**: -0.0476\n\n**Interpretation**: With a p-value of 0.8206 (>> 0.05), we **fail to reject the null hypothesis of spatial independence**. The residuals exhibit **no significant spatial autocorrelation** across Philadelphia census tracts. This indicates that prediction errors are randomly distributed geographically and do not show clustering patterns.\n\n**Implication for OLS**: This result supports the validity of OLS regression assumptions. Geographic factors not explicitly captured in the model (neighborhood effects, landlord networks, local housing market dynamics) are not systematically biasing predictions in spatially clustered ways. However, the negative Moran's I value (-0.9178) slightly below the expected value suggests residuals may have a weak dispersal pattern, which warrants monitoring in future model refinements.\n\n# Bias & Equity Considerations\n\n## Geographic Disparities in Eviction Risk\n\nEviction risk is unevenly distributed across Philadelphia, with the highest concentrations in historically Black neighborhoods facing long-term disinvestment, particularly North and West Philadelphia. A model that performs well citywide may still systematically mispredict in communities with atypical filing dynamics, landlord behavior, or underreported cases.\n\n# Implementation Recommendations\n\n## Operationalizing the Eviction Prediction System\n\nTo translate this model into actionable policy, the City of Philadelphia could implement the following operational framework:\n\n## Monthly Forecast Dashboard\n\n- **Automated updates**: Model inputs (CPI, unemployment, filings) refresh automatically each month\n- **Forecast output**: Display predicted eviction pressure for next month with confidence intervals\n- **Tract-level detail**: Show which neighborhoods face elevated risk\n- **Stakeholder access**: Share forecasts with Housing Authority, legal aid providers, and community organizations\n\n## Targeted Eviction Prevention Strategy\n\nWhen the model predicts elevated eviction pressure:\n\n1. **Legal aid surge**: Pre-position attorneys and paralegals in high-risk tracts\n2. **Rental assistance outreach**: Deploy ERA (Emergency Rental Assistance) and prevention funds to predicted hotspots\n3. **Mediation services**: Activate landlord-tenant negotiation programs\n4. **Case management**: Connect at-risk households to financial counseling and benefit enrollment\n\n## Resource Allocation Timeline\n\n- **Month 0**: Model generates forecast for Month 1\n- **Weeks 1-2**: City agencies receive and review predictions\n- **Weeks 3-4**: Prevention resources (legal aid, mediation, ERA) deployed to predicted high-risk areas\n- **Month 1**: Services available when filings anticipated to surge\n\n## Safeguards Against Misuse\n\n1. **Independent bias audits**: Annual third-party review of prediction errors by neighborhood demographics\n2. **Use restrictions**: Model outputs explicitly prohibited from justifying policing, enforcement operations, or surveillance\n3. **Community oversight board**: Quarterly meetings with tenant advocates, legal aid, and neighborhood organizations\n4. **Transparency reporting**: Public dashboard of forecast accuracy, error rates by neighborhood, and resource allocation\n5. **Sunset clause**: Model contract includes review every 2 years with community input\n\n---\n\n## Potential Harms from Model Misspecification\n\n**Underprediction** → Insufficient rental assistance allocated to high-risk neighborhoods, allowing preventable displacements\n\n**Overprediction** → Unnecessary targeting of resources that reinforces stigma, surveillance, or policing in vulnerable communities\n\n**Macro-economic variables** (unemployment, CPI) may reflect structural racism embedded in labor markets, potentially masking causal mechanisms\n\n**Eviction filings themselves** reflect unequal landlord-tenant power dynamics and enforcement variation across neighborhoods, not just tenant vulnerability\n\n\n## Safeguards & Recommendations\n\nTo mitigate these risks, implementation must include:\n\n1. **Equity audits**: Annual analysis of prediction errors by neighborhood race/income composition\n2. **Community oversight**: Advisory board with tenant advocates, legal aid providers, and community organizations\n3. **Restricted use**: Model outputs cannot be used to justify policing, enforcement, or surveillance\n4. **Resource expansion**: Forecasts must trigger **expansion** of prevention services, not rationing\n5. **Transparency**: Public reporting of model limitations and error rates by neighborhood\n\n---",
    "supporting": [
      "eviction_data_analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}